<?php
return [
    'subtitle_2' => 'Integrazzjonijiet ta\' partijiet terzi',
    'intro_1' => 'Aħna nirrispettaw il-privatezza tiegħek u nirrikonoxxu li rridu nżommu u nużaw l-informazzjoni tiegħek b\'mod responsabbli.',
    'line_2_1' => 'Commit Global juża Google Analytics biex jifhmu aħjar kif il-viżitaturi jinnavigaw il-websajt tagħna biex itejbu l-esperjenza ġenerali tagħhom. Google Analytics ma jiġbor l-ebda informazzjoni identifikabbli dwar il-viżitaturi tagħha u aħna ma nipproċessawx id-dejta miġbura permezz tal-formoli tagħna flimkien mad-dejta pprovduta minn Google Analytics.',
    'title' => 'Politika tal-Privatezza',
    'intro_2' => 'wevote4.eu hija websajt maħluqa minn Commit Global (“Commit Global”, “aħna”, “lilna”, “tagħna”) bl-iskop li tinforma lill-pubbliku dwar l-elezzjonijiet Ewropej.',
    'subtitle_3' => 'X\'inhuma l-cookies',
    'line_3_4' => 'Hemm cookies li jintużaw esklussivament għal sessjoni waħda - dawn ma jibqgħux maħżuna wara li l-utent ikun ħalla l-websajt. Il-cookies permanenti jinħażnu u jintużaw mill-ġdid kull darba li l-utent jirritorna għal dik il-websajt iżda jistgħu jitħassru fi kwalunkwe ħin mill-utent.',
    'line_4_3' => 'Tista \'twaqqaf il-browser tiegħek biex tirrifjuta l-cookies awtomatikament jew tista\' tagħżel biss xi websajts fejn il-cookies huma attivati. Iżda, per eżempju, jekk inti itfi cookies fuq din il-websajt inti ma tistax issegwi permezz mal-passi li jmiss fil-mili tal-formola.',
    'line_3_3' => '- Cookies tas-sessjoni - huma cookies maħżuna temporanjament fl-istorja tal-browser fejn jinħażnu sakemm l-utent jitlaq minn dik il-websajt jew jagħlaq it-tieqa tal-browser.
- Cookies persistenti - Dawn huma maħżuna, għal tul ta \'żmien predeterminat, fuq hard drive tal-kompjuter jew tagħmir simili. Il-cookies persistenti jinkludu dawk imqiegħda minn websajt differenti minn dik li l-utent qed iżur dak iż-żmien, l-hekk imsejħa “cookies ta\' partijiet terzi” - li jistgħu jintużaw b\'mod anonimu biex isegwu l-interessi ta\' utent - li jippermettulhom jirċievu reklami aktar rilevanti għall-interessi tagħhom.',
    'line_3_1' => 'Cookie (“cookie tal-browser” jew “cookie HTTP”) hija fajl żgħir, suċċessjoni ta\' ittri u numri, li jinħażen fuq kwalunkwe terminal b\'aċċess għall-Internet (kompjuters, mowbajls, pilloli eċċ.) u jiġi installat fuq talba minn server għal browser (ex: Internet Explorer, Chrome). “Cookies” ma fihom l-ebda programm tas-softwer, viruses jew spyware u ma jistgħux jaċċessaw informazzjoni fuq il-hard drive tal-utent. Cookie tikkonsisti f\'isem u kontenut, it-tul tal-eżistenza tagħha huwa limitat, u jista \'jiġi aċċessat mill-ġdid mill-webserver meta utent jirritorna fuq il-websajt assoċjata ma\' dak is-server.',
    'subtitle_4' => 'Kif timblokkja/toqgħod mill-użu tal-cookies',
    'line_6_1' => 'Id-diżattivazzjoni tal-cookies mhux se tibqa\' tippermetti l-aċċess tal-utent għal uħud mill-aktar websajts importanti bħal Youtube, Gmail, Yahoo u oħrajn. Hawn xi pariri li jistgħu jgħinuk tibbrawżja b\'mod sikur filwaqt li żżomm il-cookies:',
    'line_7_5' => 'Din il-verżjoni tat-Termini u Kundizzjonijiet wevotefor.eu hija effettiva mit-23 ta\' Mejju 2024. ',
    'subtitle_6' => 'Pariri għal ibbrawżjar sikur u responsabbli bbażat fuq il-cookies',
    'line_5_1' => 'Jista\' jkun hemm sitwazzjonijiet fejn, kif meħtieġ mil-liġi, nistgħu nkunu mitluba niżvelaw informazzjoni personali miġbura permezz ta\' din il-websajt. Aħna nistgħu naċċessaw, nippreservaw u jiżvelaw l-informazzjoni tiegħek jekk mitluba sabiex tikkonforma mar-rekwiżiti tal-infurzar tal-liġi u l-proċessi legali, bħal ordnijiet tal-qorti jew jekk issottomessi, jew jekk dan jista\' jipproteġi lilek jew id-drittijiet, il-proprjetà jew is-sigurtà ġenerali ta\' ħaddieħor.',
    'line_6_3' => 'Il-cookies huma kullimkien u ma jistgħux jiġu evitati jekk tixtieq taċċessa xi wħud mill-akbar u l-aħjar websajts fuq l-internet, kemm lokali jew internazzjonali. Il-fehim ċar tal-mod kif jaħdmu l-cookies u l-benefiċċji li jġibu magħkom tista\' tieħu l-miżuri ta\' sigurtà meħtieġa sabiex dejjem ikollok esperjenza ta\' browser bla periklu u sodisfaċenti.',
    'line_1_2' => 'Malli nżuru wevote4.eu aħna awtomatikament niġbru u naħżnu dejta dwar iż-żjara attwali tiegħek. Din l-informazzjoni mhix identifikabbli personalment. L-informazzjoni li nistgħu niġbru hija: sistema operattiva fuq it-tagħmir tiegħek, il-browser li qed tuża, paġni f\'wevote4.eu li żort, is-sors taż-żjara tiegħek (ex: Google, Facebook), id-data u l-ħin taż-żjara tiegħek u d-dominju minn fejn taċċessa l-internet. Din l-informazzjoni kollha tintuża biex tkompli ttejjeb l-esperjenza tan-navigazzjoni fuq il-websajt tagħna u biex tifhem il-preferenzi tal-viżitaturi tagħna. Aħna mhux se niġbru l-ebda informazzjoni personali permezz ta \'din il-websajt mingħajr il-kunsens espress tiegħek.',
    'line_1_1' => '- Aħna niġbru informazzjoni mingħandek jekk taċċessa din il-websajt permezz ta \'browser regolari.
- Din il-websajt tagħmel użu minn cookies (ex: Google Analytics) biex ikejjel u jottimizza l-esperjenza għall-utenti kollha.
- Commit Global mhux se jiżvela jew ibiegħ id-dejta personali tiegħek lil xi parti terza, ħlief is-sitwazzjonijiet legalment vinkolanti deskritti f\'din il-Politika tal-Privatezza.
- Commit Global se tieħu l-miżuri kollha raġonevoli biex jipproteġu l-informazzjoni personali tiegħek peress li dan huwa tħassib ewlieni għalina.',
    'line_4_1' => 'Il-cookies huma waħda mill-aktar għodod importanti għal esperjenza tal-Internet bla xkiel u effiċjenti, li jgħinu biex jiġġeneraw esperjenzi ta \'browser faċli mfassla għall-bżonnijiet ta\' kull utent. Ir-rifjut li taċċetta l-cookies jew id-diżattivahom jista\' jagħmel xi websajts impossibbli biex jintużaw. Li tirrifjuta li taċċetta l-cookies jew id-diżattivahom ma jfissirx li ma tibqax tirċievi reklami onlajn, biss li dawn ir-reklami ma jibqgħux jieħdu inkunsiderazzjoni l-interessi jew il-preferenzi tiegħek kif determinat mill-imġieba tal-ibbrawżjar tiegħek.',
    'line_4_5' => 'Għal aktar informazzjoni ġenerali dwar il-cookies u kif tiddiżattivahom, tista\' żżur www.aboutcookies.org.',
    'line_2_2' => 'Google Analytics se tpoġġi cookie fuq il-browser tiegħek sabiex din tidentifika inti bħala viżitatur uniku u biex tiġbor informazzjoni dwar in-navigazzjoni tiegħek kif xieraq. Din il-cookie tintuża esklussivament minn Google li min-naħa tagħha hija ristretta milli taqsam u tuża din id-dejta mit-Termini ta \'Użu ta\' Google Analytics tagħha stess u l-Politika tal-Privatezza ta\' Google.',
    'intro_3' => 'Din il-Politika ta\' Privatezza tiddeskrivi kif niġbru, nużaw, u nipproteġu l-informazzjoni personali tiegħek fuq din il-websajt. Billi tissottometti l-informazzjoni personali tiegħek fuq din il-websajt, inti taqbel mat-termini f\'din il-Politika tal-Privatezza. Jekk ma taqbilx ma \'dawn it-termini, jekk jogħġbok tużax il-websajt tagħna.',
    'line_7_4' => 'Commit Global jirriserva d-dritt li tirrevedi u taġġorna din il-politika fi kwalunkwe ħin, mingħajr avviż jew aċċettazzjoni minn qabel tal-utenti. Jekk għandek xi mistoqsijiet rigward l-informazzjoni li tinsab f\'din il-paġna, jekk jogħġbok ikteb lilna fuq ',
    'subtitle_5' => 'Qsim tad-dejta',
    'line_7_3' => 'Din il-politika tikkostitwixxi, fl-intier tagħha, ftehim konkluż bejnek u Commit Global rigward l-użu ta\' dan is-sit.',
    'line_6_2' => '- Ippersonalizza l-issettjar tal-cookie tal-browser tiegħek biex jippermettu livell ta \'sigurtà komdu. Jekk il-cookies mhumiex problema għalik u int l-unika persuna li tuża dak l-apparat tista \'tistabbilixxi intervalli twal ta\' żamma tal-cookies sabiex taħżen l-istorja tal-ibbrawżjar tiegħek u d-dejta tal-aċċess personali tiegħek.
- Jekk taqsam it-tagħmir jew il-kompjuter inti tista \'tixtieq li twaqqaf il-browser biex tħassar id-data tiegħek ibbrawżjar individwali kull darba li tkun magħluqa. Dan huwa mod wieħed biex taċċessa websajts li jqiegħdu cookies fuq il-kompjuter maqsum tiegħek waqt li tħassar id-dejta kollha tal-ibbrawżjar tiegħek meta tagħlaq is-sessjoni.
- tinstalla app anti-spyware u żommha aġġornata. Ħafna apps anti-spyware jinkludu sejbien ta \'attakk tal-websajt. Dawn l-apps jipprevjenu lill-browser milli jaċċessa websajts li jistgħu jisfruttaw il-vulnerabbiltajiet tal-browser jew iniżżlu softwer perikoluż. Żgura li l-browser tiegħek huwa aġġornat. Ħafna attakki bbażati fuq il-cookies jisfruttaw il-punti dgħajfa tal-verżjonijiet tal-browser qodma.',
    'subtitle_1' => 'Ġbir tad-dejta',
    'line_4_2' => 'Ir-rifjut li taċċetta l-cookies jew id-diżattivahom jista\' jagħmel xi websajts diffiċli jew impossibbli biex jinnavigaw jew jintużaw. Li tirrifjuta li taċċetta cookies ukoll ma jfissirx li ma tibqax tirċievi reklami onlajn.',
    'line_3_2' => 'Il-cookies jiffrankaw l-informazzjoni f\'fajl test żgħir li jippermetti websajt tirrikonoxxi browser. Is-server tal-web jirrikonoxxi l-browser sakemm il-cookie tiskadi jew titħassar. Il-cookie taħżen informazzjoni importanti li ttejjeb l-esperjenza tal-ibbrawżjar (eż. numru tas-serje għad-donazzjoni tiegħek). Il-cookies ma jitolbux informazzjoni personali u lanqas ma jidentifikaw personalment lill-utenti tal-internet.',
    'line_4_4' => 'Il-brawżers moderni joffru l-abbiltà li jibdlu l-issettjar tal-cookies. Normalment tista\' ssib settings tal-cookies taħt it-tab “għażliet” jew il-menu “preferenzi” tal-browser tiegħek.',
    'subtitle_7' => 'Id-drittijiet tiegħek',
    'line_7_1' => 'Bħala utent tal-websajt wevote4.eu għandek id-drittijiet li ġejjin:',
    'line_7_2' => '- Id-dritt għal informazzjoni rigward l-ipproċessar ta\' data personali minn Commit Global;
- Id-dritt għal aċċess għad-dejta personali, fuq talba u mingħajr ħlas għal talba waħda fis-sena;
- Id-dritt ta\' intervent, rettifika, tħassir jew portabbiltà tad-data personali, fuq talba u mingħajr ħlas;
- Id-dritt li tindirizza kwalunkwe awtorità kompetenti rigward kwistjonijiet dwar il-privatezza tad-dejta b\'rabta mal-użu tad-dejta personali tiegħek
- Id-dritt għall-oppożizzjoni u l-proċess awtomatizzat tat-teħid tad-deċiżjonijiet individwali kif ukoll id-dritt li jiġi ristrett l-ipproċessar.',
];
