<?php
return [
    'title' => 'O projektu',
    'line_1' => 'Zamislite jedinstveni, živahni izborni događaj koji ujedinjuje više od 400 milijuna građana diljem Europske unije. Izbori za EU nisu samo niz nacionalnih glasova, već zajedničko slavlje našeg zajedničkog identiteta i demokratskih vrijednosti. Kao građani EU-a okupljamo se kako bismo oblikovali našu zajedničku budućnost, prelazili granice i prihvaćali snagu naše raznolikosti. Ovaj projekt svjedoči o našem jedinstvu, olakšavajući svakom građaninu, bez obzira gdje se nalazi u EU-u, sudjelovanje u ovom snažnom demokratskom procesu.',
    'line_2' => 'Kako bi podržao ovu viziju jedinstvenog izbornog procesa, Commit Global stvorio je platformu "Glasujemo za EU**", koja utjelovljuje ideju jedinstva i suradnje. Ova platforma svim građanima EU-a pruža bitne informacije o tome kako brzo glasovati i pronaći biračka mjesta bez obzira na njihovu lokaciju.',
    'subtitle' => 'Što ovu platformu čini posebnom?',
    'line_3' => '**Format stabla odluka: ** Platforma koristi format stabla odlučivanja kojim se građani EU-a izravno upućuju na specifične informacije koje su im potrebne.',
    'line_4' => '**Sveobuhvatne informacije: ** Konačne informacije su sveobuhvatne i obuhvaćaju zahtjeve za registraciju (ako ih ima), različite načine glasovanja (punomoćnik, online, poštansko, biračko mjesto), potrebnu dokumentaciju za glasovanje i pomoć biračima s invaliditetom ili drugim ograničenjima.',
    'line_5' => '**Provjerene informacije: ** Informacije prikazane na internetskoj stranici unakrsno se provjeravaju iz više različitih izvora, uključujući nacionalna ministarstva i organizacije odgovorne za pravila i postupke glasovanja, kao i platformu Europskog parlamenta.',
    'line_6' => '**Višejezična dostupnost: ** Osiguravamo da svaki građanin EU-a može pristupiti potrebnim informacijama na svom jeziku. Platforma je dostupna na 26 jezika, a stablo odluka svake zemlje nalazi se na službenim jezicima i na engleskom jeziku. Time se osigurava da svi, bez obzira na jezično podrijetlo, mogu bez napora kretati se procesom glasovanja.',
    'line_7' => '**Međusobno povezane smjernice: ** Bez obzira na državljanstvo EU-a birača, zemlju prebivališta ili mjesto na dan izbora, platforma pruža precizne, prilagođene upute i informacije relevantne za njihovu jedinstvenu situaciju. To je kao da imate personaliziranog pomoćnika za glasanje koji proces čini glatkim i nadahnjujućim.',
    'line_8' => 'We Vote for EU platforma je koju je stvorio i upravljao **Commit Global**, prva globalna nevladina organizacija za građanske tehnologije na svijetu. Sa sjedištem u Haagu (Nizozemska), Commit Global konsolidira, održava i pruža slobodan pristup kritičnoj digitalnoj tehnologiji, **Infrastructure for Good**, organizacijama civilnog društva i pogođenom stanovništvu diljem svijeta. Za dodatne informacije o našem radu posjetite [našu web stranicu] (https://www.commitglobal.org).',
];
