<?php
return [
    'line_6_1' => 'Deaktiviranje kolačića više neće omogućiti korisnicima pristup nekim od najvažnijih web stranica kao što su Youtube, Gmail, Yahoo i drugi. Evo nekoliko savjeta koji vam mogu pomoći u sigurnom pregledavanju dok zadržavate kolačiće:',
    'line_7_5' => 'Ova verzija Uvjeta i odredbi wevotefor.eu stupa na snagu 23. svibnja 2024. ',
    'subtitle_6' => 'Savjeti za sigurno i odgovorno pregledavanje temeljeno na kolačićima',
    'line_5_1' => 'Mogu postojati situacije u kojima se od nas, prema zahtjevu zakona, može tražiti da otkrijemo osobne podatke prikupljene putem ove web stranice. Možemo pristupiti vašim podacima, sačuvati i otkriti ako se to zatraži radi ispunjavanja zahtjeva provedbe zakona i zakonskih postupaka, kao što su sudski nalozi ili ako su upućeni sudski poziv, ili ako to može zaštititi vaša ili tuđa prava, imovinu ili opću sigurnost.',
    'line_4_5' => 'Za općenitije informacije o kolačićima i načinu njihovog deaktiviranja možete posjetiti www.aboutcookies.org.',
    'subtitle_5' => 'Dijeljenje podataka',
    'line_3_4' => 'Postoje kolačići koji se koriste isključivo za jednu sesiju - oni se više ne pohranjuju nakon što korisnik napusti web stranicu. Trajni kolačići pohranjuju se i ponovno koriste svaki put kada se korisnik vrati na tu web stranicu, ali ih korisnik može izbrisati u bilo kojem trenutku.',
    'subtitle_4' => 'Kako blokirati/isključiti korištenje kolačića',
    'subtitle_2' => 'Integracije trećih strana',
    'line_4_3' => 'Možete postaviti svoj preglednik da automatski odbija kolačiće ili možete odabrati samo neke web stranice na kojima su kolačići omogućeni. Ali, na primjer, ako isključite kolačiće na ovoj web stranici, ne možete slijediti sljedeće korake u popunjavanju obrasca.',
    'line_3_3' => '- Kolačići sesije - kolačići su privremeno pohranjeni u povijesti preglednika gdje se pohranjuju sve dok korisnik ne napusti tu web stranicu ili zatvori prozor preglednika.
- Trajni kolačići - pohranjuju se, na unaprijed određeno vrijeme, na tvrdom disku računala ili sličnoj opremi. Trajni kolačići uključuju one koje postavlja druga web stranica od one koju korisnik posjećuje u to vrijeme, takozvane "kolačiće treće strane" - koji se mogu anonimno koristiti za praćenje interesa korisnika - omogućujući im primanje oglasa relevantnijih za njegove interese.',
    'intro_1' => 'Poštujemo vašu privatnost i priznajemo da moramo odgovorno održavati i koristiti vaše podatke.',
    'line_3_1' => 'Kolačić ("kolačić preglednika" ili "HTTP kolačić") je mala datoteka, niz slova i brojeva, koja se pohranjuje na bilo kojem terminalu s pristupom internetu (računala, mobilni telefoni, tableti itd.) i instalira se na zahtjev poslužitelja na preglednik (npr. Internet Explorer, Chrome). "Kolačići" ne sadrže nikakve softverske programe, viruse ili špijunski softver i ne mogu pristupiti informacijama na tvrdom disku korisnika. Kolačić se sastoji od imena i sadržaja, duljina njegova postojanja je ograničena, a web-poslužitelj mu može ponovno pristupiti kada se korisnik vrati na web stranicu povezanu s tim poslužiteljem.',
    'line_2_1' => 'Commit Global koristi Google Analytics kako bi bolje razumio kako posjetitelji kreću našim web stranicama kako bi poboljšali svoje cjelokupno iskustvo. Google Analytics ne prikuplja nikakve identifikacijske podatke o svojim posjetiteljima i ne obrađujemo podatke prikupljene putem naših obrazaca zajedno s podacima koje pruža Google Analytics.',
    'line_1_2' => 'Nakon posjeta wevote4.eu automatski ćemo prikupljati i pohraniti podatke o Vašem trenutnom posjetu. Te se informacije ne mogu osobno identificirati. Podaci koje možemo prikupiti su: operativni sustav na vašem uređaju, preglednik koji koristite, stranice na wevote4.eu koje ste posjetili, izvor vašeg posjeta (npr. Google, Facebook), datum i vrijeme vašeg posjeta te domena s koje pristupate internetu. Sve ove informacije koriste se za daljnje poboljšanje navigacijskog iskustva na našoj web stranici i razumijevanje preferencija naših posjetitelja. Nećemo prikupljati nikakve osobne podatke putem ove web stranice bez vašeg izričitog pristanka.',
    'title' => 'Politika privatnosti',
    'line_1_1' => '- Prikupljamo informacije od vas ako pristupate ovoj web stranici putem običnog preglednika.
- Ova web stranica koristi kolačiće (npr. Google Analytics) za mjerenje i optimizaciju iskustva za sve korisnike.
- Commit Global neće otkriti ili prodavati vaše osobne podatke bilo kojoj trećoj strani, osim pravno obvezujućih situacija opisanih u ovim Pravilima o privatnosti.
- Commit Global poduzet će sve razumne mjere kako bi zaštitio vaše osobne podatke jer je to velika briga za nas.',
    'line_6_3' => 'Kolačići su posvuda i ne mogu se izbjeći ako želite pristupiti nekim od najvećih i najboljih web stranica na internetu, bilo lokalnim ili međunarodnim. Jasno razumijevanje načina rada kolačića i prednosti koje oni donose možete poduzeti potrebne sigurnosne mjere kako biste uvijek imali sigurno i zadovoljavajuće iskustvo pregledavanja.',
    'line_4_1' => 'Kolačići su jedan od najvažnijih alata za besprijekorno i učinkovito iskustvo interneta, pomažući u stvaranju prijateljskih iskustava pregledavanja prilagođenih potrebama svakog korisnika. Odbijanje prihvaćanja kolačića ili njihovo deaktiviranje može onemogućiti korištenje nekih web stranica. Odbijanje prihvaćanja kolačića ili njihovo deaktiviranje ne znači da više nećete primati online oglase, već samo da ti oglasi više neće uzeti u obzir vaše interese ili postavke kako je određeno vašim ponašanjem pregledavanja.',
    'intro_2' => 'wevote4.eu je web stranica koju je stvorio Commit Global ("Commit Global", "mi", "nas", "naš") s ciljem informiranja javnosti o europskim izborima.',
    'line_2_2' => 'Google Analytics postavit će kolačić u vaš preglednik kako bi vas identificirao kao jedinstvenog posjetitelja i prikupio podatke o vašoj navigaciji u skladu s tim. Ovaj kolačić koristi isključivo Google koji je zauzvrat ograničen dijeljenje i korištenje tih podataka vlastitim Uvjetima korištenja Google Analytics i Googleovim pravilima o privatnosti.',
    'intro_3' => 'Ova Pravila o privatnosti opisuju kako prikupljamo, koristimo i štitimo vaše osobne podatke na ovoj web stranici. Slanjem vaših osobnih podataka na ovoj web stranici pristajete na uvjete u ovoj Politici privatnosti. Ako se ne slažete s ovim uvjetima, nemojte koristiti našu web stranicu.',
    'line_7_4' => 'Commit Global zadržava pravo revidirati i ažurirati ovu politiku u bilo kojem trenutku, bez prethodne najave ili prethodnog prihvaćanja korisnika. Ako imate bilo kakvih pitanja u vezi s informacijama sadržanim na ovoj stranici, pišite nam na ',
    'subtitle_3' => 'Što su kolačići',
    'line_7_3' => 'Ova politika predstavlja, u cijelosti, ugovor sklopljen između vas i Commit Global u vezi s korištenjem ove web stranice.',
    'line_6_2' => '- Prilagodite postavke kolačića preglednika kako biste omogućili ugodnu razinu sigurnosti. Ako vam kolačići ne predstavljaju problem i vi ste jedina osoba koja koristi taj uređaj, možete postaviti duge intervale zadržavanja kolačića kako biste pohranili svoju povijest pregledavanja i vaše osobne podatke o pristupu.
- Ako dijelite uređaj ili računalo, možda ćete htjeti postaviti preglednik za brisanje vaših pojedinačnih podataka pregledavanja svaki put kada se zatvori. Ovo je jedan od načina pristupa web stranicama koje postavljaju kolačiće na vaše zajedničko računalo dok brišu sve podatke pregledavanja prilikom zatvaranja sesije.
- instalirajte aplikaciju protiv špijunskog softvera i ažurirajte je. Mnoge aplikacije protiv špijunskog softvera uključuju otkrivanje napada na web stranice. Te aplikacije sprječavaju pregledniku pristup web stranicama koje bi mogle iskoristiti ranjivosti preglednika ili preuzeti opasan softver. Pobrinite se da je vaš preglednik ažuriran. Mnogi napadi temeljeni na kolačićima iskorištavaju slabe točke starih verzija preglednika.',
    'subtitle_1' => 'Prikupljanje podataka',
    'line_4_2' => 'Odbijanje prihvaćanja kolačića ili njihovo deaktiviranje može otežati ili onemogućiti navigaciju ili korištenje nekih web stranica. Odbijanje prihvaćanja kolačića također ne znači da više nećete primati online oglase.',
    'line_3_2' => 'Kolačići pohranjuju podatke u malu tekstualnu datoteku omogućujući web stranici da prepozna preglednik. Web poslužitelj će prepoznati preglednik sve dok kolačić ne istekne ili ne bude izbrisan. Kolačić pohranjuje važne informacije koje poboljšavaju iskustvo pregledavanja (npr. serijski broj za vašu donaciju). Kolačići ne traže osobne podatke niti osobno identificiraju korisnike interneta.',
    'line_4_4' => 'Moderni preglednici nude mogućnost promjene postavki kolačića. Postavke kolačića obično možete pronaći na kartici "opcije" ili izborniku "postavke" vašeg preglednika.',
    'subtitle_7' => 'Vaša prava',
    'line_7_1' => 'Kao korisnik web stranice wevote4.eu imate sljedeća prava:',
    'line_7_2' => '- Pravo na informacije u vezi s obradom osobnih podataka od strane Commit Global;
- Pravo na pristup osobnim podacima, na zahtjev i besplatno za jedan zahtjev godišnje;
- pravo intervencije, ispravljanja, brisanja ili prenosivosti osobnih podataka, na zahtjev i besplatno;
- Pravo obraćanja bilo kojem nadležnom tijelu u vezi s pitanjima privatnosti podataka u vezi s korištenjem vaših osobnih podataka
- Pravo na prigovor i automatizirani pojedinačni postupak donošenja odluka, kao i pravo na ograničavanje obrade.',
];
