<?php
return [
    'line_2_2' => 'Google Analytics ievieto sīkfailu jūsu pārlūkprogrammā, lai tas identificētu jūs kā unikālu apmeklētāju un attiecīgi apkopotu informāciju par jūsu navigāciju. Šo sīkfailu izmanto tikai Google, kurai savukārt ir ierobežota šo datu koplietošana un izmantošana saskaņā ar saviem Google Analytics lietošanas noteikumiem un Google konfidencialitātes politiku.',
    'subtitle_2' => 'Trešo pušu integrācija',
    'line_7_5' => 'Šī wevotefor.eu Noteikumu un nosacījumu versija stājas spēkā 2024. gada 23. maijā. ',
    'line_7_1' => 'Jums kā wevote4.eu tīmekļa vietnes lietotājam ir šādas tiesības:',
    'line_6_1' => 'Sīkdatņu deaktivizēšana vairs neļaus lietotājam piekļūt dažām svarīgākajām vietnēm, piemēram, Youtube, Gmail, Yahoo un citām. Šeit ir daži padomi, kas var palīdzēt droši pārlūkot, saglabājot sīkdatnes:',
    'line_3_4' => 'Ir sīkdatnes, kuras tiek izmantotas tikai vienai sesijai - tās vairs netiek saglabātas pēc tam, kad lietotājs ir pametījis tīmekļa vietni. Pastāvīgās sīkdatnes tiek saglabātas un atkārtoti izmantotas katru reizi, kad lietotājs atgriežas šajā tīmekļa vietnē, bet lietotājs tos jebkurā laikā var izdzēst.',
    'subtitle_4' => 'Kā bloķēt/atteikties no sīkdatņu izmantošanas',
    'line_4_3' => 'Jūs varat iestatīt savu pārlūkprogrammu, lai automātiski noraidītu sīkfailus, vai arī varat izvēlēties tikai dažas vietnes, kurās ir iespējotas sīkdatnes. Bet, piemēram, ja jūs izslēdzat sīkdatnes šajā vietnē, jūs nevarat sekot līdzi nākamajām darbībām, aizpildot veidlapu.',
    'subtitle_6' => 'Padomi drošai un atbildīgai pārlūkošanai uz sīkdatnēm',
    'line_3_3' => '- Sesijas sīkdatnes - ir sīkdatnes, kas uz laiku tiek saglabātas pārlūkprogrammas vēsturē, kur tās tiek saglabātas līdz brīdim, kad lietotājs pamet šo vietni vai aizver pārlūkprogrammas logu.
- Pastāvīgās sīkdatnes - tās iepriekš noteiktu laiku tiek saglabātas datora cietajā diskā vai līdzīgā aprīkojumā. Pastāvīgās sīkdatnes ietver sīkdatnes, ko ievietojusi cita tīmekļa vietne nekā tā, kuru lietotājs tajā laikā apmeklē, tā saucamās “trešās puses sīkdatnes”, kuras var anonīmi izmantot, lai izsekotu lietotāja interesēm, kas ļauj saņemt reklāmas, kas ir atbilstošākas viņu interesēm.',
    'intro_1' => 'Mēs cienām jūsu privātumu un atzīstam, ka mums ir atbildīgi jāuztur un jāizmanto jūsu informācija.',
    'line_3_1' => 'Sīkdatne (“pārlūka sīkdatne” vai “HTTP sīkdatne”) ir neliels fails, burtu un ciparu secība, kas tiek glabāta jebkurā terminālā ar piekļuvi internetam (datoros, mobilajos tālruņos, planšetdatoros utt.) un tiek instalēts pēc servera pieprasījuma uz pārlūkprogrammu (piemēram, Internet Explorer, Chrome). “Sīkdatnes” nesatur nekādas programmatūras programmas, vīrusus vai spiegprogrammatūru un nevar piekļūt informācijai lietotāja cietajā diskā. Sīkdatne sastāv no nosaukuma un satura, tā pastāvēšanas ilgums ir ierobežots, un tīmekļa serveris tam atkal var piekļūt, kad lietotājs atgriežas vietnē, kas saistīta ar šo serveri.',
    'line_2_1' => 'Commit Global izmanto Google Analytics, lai labāk izprastu, kā apmeklētāji pārvietojas mūsu vietnē, lai uzlabotu savu vispārējo pieredzi. Google Analytics neapkopo nekādu identificējamu informāciju par saviem apmeklētājiem, un mēs neapstrādājam datus, kas savākti, izmantojot mūsu veidlapas, kopā ar Google Analytics sniegtajiem datiem.',
    'line_5_1' => 'Var rasties situācijas, kad, kā to pieprasa likums, mums var lūgt izpaust personisko informāciju, kas savākta, izmantojot šo tīmekļa vietni. Mēs varam piekļūt jūsu informācijai, saglabāt un izpaust, ja to pieprasa, lai izpildītu tiesībaizsardzības prasības un juridiskus procesus, piemēram, tiesas rīkojumus vai ja tiek izsaukta, vai ja tas var aizsargāt jūsu vai citas personas tiesības, īpašumu vai vispārējo drošību.',
    'line_1_2' => 'Apmeklējot wevote4.eu, mēs automātiski apkoposim un saglabāsim datus par jūsu pašreizējo apmeklējumu. Šī informācija nav personīgi identificējama. Informācija, ko mēs varam apkopot, ir šāda: operētājsistēma jūsu ierīcē, jūsu izmantotā pārlūkprogramma, vietnes wevote4.eu lapas, kuras esat apmeklējis, jūsu apmeklējuma avots (piemēram, Google, Facebook), apmeklējuma datums un laiks, kā arī domēns, no kura piekļūstat internetam. Visa šī informācija tiek izmantota, lai vēl vairāk uzlabotu navigācijas pieredzi mūsu tīmekļa vietnē un izprastu mūsu apmeklētāju vēlmes. Mēs neapkoposim nekādu personisko informāciju, izmantojot šo tīmekļa vietni bez jūsu skaidras piekrišanas.',
    'title' => 'Privātuma politika',
    'line_1_1' => '- Mēs apkopojam informāciju no jums, ja jūs piekļūstat šai vietnei, izmantojot parasto pārlūkprogrammu.
- Šī vietne izmanto sīkdatnes (piemēram, Google Analytics), lai izmērītu un optimizētu pieredzi visiem lietotājiem.
- Commit Global neizpauž un nepārdos jūsu personas datus trešajai pusei, izņemot juridiski saistošās situācijas, kas aprakstītas šajā Privātuma politikā.
- Commit Global veiks visus saprātīgos pasākumus, lai aizsargātu jūsu personisko informāciju, jo tas mums rada lielas bažas.',
    'line_6_3' => 'Sīkdatnes ir visur, un no tām nevar izvairīties, ja vēlaties piekļūt dažām lielākajām un labākajām vietnēm internetā, gan vietējām, gan starptautiskām. Skaidra izpratne par sīkdatņu darbību un ieguvumiem, ko tie sniedz, var veikt nepieciešamos drošības pasākumus, lai jums vienmēr būtu droša un apmierinoša pārlūkošanas pieredze.',
    'line_4_1' => 'Sīkdatnes ir viens no svarīgākajiem instrumentiem nevainojamai un efektīvai interneta pieredzei, palīdzot radīt draudzīgu pārlūkošanas pieredzi, kas pielāgota katra lietotāja vajadzībām. Atteikšanās pieņemt sīkfailus vai to deaktivizēšana dažu tīmekļa vietņu izmantošanu var padarīt neiespējamu. Atteikšanās pieņemt sīkfailus vai to deaktivizēšana nenozīmē, ka jūs vairs nesaņemsit tiešsaistes reklāmas, bet tikai to, ka šajās reklāmās vairs netiks ņemtas vērā jūsu intereses vai preferences, ko nosaka jūsu pārlūkošanas rīcība.',
    'intro_2' => 'wevote4.eu ir vietne, kuru izveidoja Commit Global (“Commit Global”, “mēs”, “mūs”, “mūsu”) ar mērķi informēt sabiedrību par Eiropas vēlēšanām.',
    'line_7_2' => '- Tiesības uz informāciju par personas datu apstrādi, ko veic Commit Global;
- Tiesības piekļūt personas datiem pēc pieprasījuma un bez maksas par vienu pieprasījumu gadā;
- tiesības iejaukties, labot, dzēst vai pārnēsāt personas datus pēc pieprasījuma un bez maksas;
- Tiesības vērsties jebkurai kompetentajai iestādei attiecībā uz datu privātuma jautājumiem saistībā ar jūsu personas datu izmantošanu
- Tiesības iebilst un automatizēts individuālais lēmumu pieņemšanas process, kā arī tiesības ierobežot apstrādi.',
    'line_4_5' => 'Lai iegūtu vispārīgāku informāciju par sīkdatnēm un to deaktivizēšanu, varat apmeklēt vietni www.aboutcookies.org.',
    'intro_3' => 'Šajā privātuma politikā ir aprakstīts, kā mēs apkopojam, izmantojam un aizsargājam jūsu personisko informāciju šajā tīmekļa vietnē. Iesniedzot savu personisko informāciju šajā tīmekļa vietnē, jūs piekrītat šīs privātuma politikas noteikumiem. Ja jūs nepiekrītat šiem noteikumiem, lūdzu, nelietojiet mūsu tīmekļa vietni.',
    'line_7_4' => 'Commit Global patur tiesības jebkurā laikā pārskatīt un atjaunināt šo politiku bez iepriekšēja lietotāju paziņojuma vai iepriekšējas piekrišanas. Ja jums ir kādi jautājumi par šajā lapā ietverto informāciju, lūdzu, rakstiet mums uz ',
    'subtitle_5' => 'Datu koplietošana',
    'subtitle_3' => 'Kas ir sīkdatnes',
    'line_7_3' => 'Šī politika kopumā ir līgums, kas noslēgts starp jums un Commit Global par šīs vietnes izmantošanu.',
    'line_6_2' => '- Pielāgojiet pārlūkprogrammas sīkfailu iestatījumus, lai nodrošinātu ērtu drošības līmeni. Ja sīkdatnes jums nerada problēmas un jūs esat vienīgā persona, kas izmanto šo ierīci, varat iestatīt ilgus sīkfailu saglabāšanas intervālus, lai saglabātu jūsu pārlūkošanas vēsturi un personas piekļuves datus.
- Ja kopīgojat ierīci vai datoru, iespējams, vēlēsities iestatīt pārlūkprogrammu, lai dzēstu jūsu individuālos pārlūkošanas datus katru reizi, kad tas tiek aizvērts. Tas ir viens no veidiem, kā piekļūt vietnēm, kas izvieto sīkfailus jūsu koplietotajā datorā, vienlaikus dzēšot visus pārlūkošanas datus, noslēdzot sesiju.
- instalējiet pretspiegprogrammatūras lietotni un atjauniniet to. Daudzās pretspiegprogrammatūras lietotnēs ir iekļauta vietņu uzbrukuma noteikšana. Šīs lietotnes neļauj pārlūkprogrammai piekļūt vietnēm, kas varētu izmantot pārlūkprogrammas ievainojamības vai lejupielādēt bīstamu programmatūru. Pārliecinieties, ka jūsu pārlūkprogramma ir atjaunināta. Daudzi uz sīkdatnēm balstīti uzbrukumi izmanto veco pārlūkprogrammas versiju vājās vietas.',
    'subtitle_1' => 'Datu vākšana',
    'line_4_2' => 'Atteikšanās pieņemt sīkfailus vai to deaktivizēšana dažās vietnēs var apgrūtināt vai padarīt neiespējamu pārvietošanos vai lietošanu. Atteikšanās pieņemt sīkfailus arī nenozīmē, ka jūs vairs nesaņemsit tiešsaistes reklāmas.',
    'line_3_2' => 'Sīkdatnes saglabā informāciju nelielā teksta failā, kas ļauj vietnei atpazīt pārlūkprogrammu. Tīmekļa serveris atpazīs pārlūkprogrammu līdz brīdim, kad sīkdatne beidzas vai tiks dzēsta. Sīkdatne saglabā svarīgu informāciju, kas uzlabo pārlūkošanas pieredzi (piemēram, jūsu ziedojuma sērijas numurs). Sīkdatnes nepieprasa personisku informāciju un neidentificē interneta lietotājus.',
    'line_4_4' => 'Mūsdienu pārlūkprogrammas piedāvā iespēju mainīt sīkfailu iestatījumus. Sīkdatņu iestatījumus parasti varat atrast pārlūkprogrammas cilnē “Opcijas” vai izvēlnē “preferences”.',
    'subtitle_7' => 'Jūsu tiesības',
];
