<?php

declare(strict_types=1);

return [
    's1' => '<p>Czy w dniu głosowania masz ukończone 18 lat?</p>',
    's1.1' => '<p>Mam mniej niż 18 lat</p>',
    's2' => '<p>Nie możesz głosować: Dziękujemy za zainteresowanie zaangażowaniem! Z niecierpliwością czekamy na kolejne wybory. W międzyczasie bądź aktywnym obywatelem!</p>',
    's1.2' => '<p>Mam 18 lub więcej lat</p>',
    's3' => '<p>W dniu wyborów, z którego kraju chcesz głosować?</p>',
    's3.1' => '<p>Polska</p>',
    's3.2' => '<p>Inny kraj UE</p>',
    's3.3' => '<p>Poza UE</p>',
    's4' => '<p>Czy 1. zamierzasz głosować w obwodowej komisji wyborczej właściwej dla miejsca stałego zamieszkania 2. zmieniłeś adres zamieszkania i chcesz być dopisany do spisu wyborców w danej gminie lub 3. chcesz głosować poza miejscem stałego zamieszkania?</p>',
    's4.1' => '<p>Zamierzam głosować w okręgu komisji wyborczej mojego stałego miejsca zamieszkania.</p>',
    's4.2' => '<p>Zmienił się mój adres zamieszkania i chcę zostać dopisany do spisu wyborców w danej gminie</p>',
    's4.3' => '<p>Chcę głosować poza moim miejscem zamieszkania</p>',
    's5' => '<p>Czy jesteś osobą niepełnosprawną lub doświadczasz ograniczeń uniemożliwiających Ci dotarcie do lokalu wyborczego?</p>',
    's5.1' => '<p>Tak</p>',
    's5.2' => '<p>nie</p>',
    's6' => '<p><em>Dla obywateli Polski i innych krajów UE:</em></p>
<p><strong>Gdzie mogę głosować?</strong> Nie musisz rejestrować swojego zamiaru głosowania w wyborach. Zostajesz wpisany do spisu wyborców na podstawie miejsca stałego zamieszkania i głosujesz w <strong>obwodowej komisji wyborczej w miejscu stałego zamieszkania</strong>.</p>
<p>Dodatkowe informacje_ <strong><em>dla obywateli UE</em></strong> <em>głosowanie w polskich wyborach do UE:</em> Każdy obywatel UE, który spełnia określone warunki, ma prawo do głosowania w wyborach do Parlamentu Europejskiego we wszystkich krajach Unii Europejskiej. W Polsce obywatele UE niebędący obywatelami polskimi stale zamieszkujący na obszarze gminy są wpisywani do rejestru wyborców, część B. Obywatele UE niebędący obywatelami polskimi muszą być wpisani do rejestru wyborców w gminie, w której mieszkają. Przepisy nie wskazują terminu, do którego należy złożyć wniosek o wpisanie do rejestru wyborców. Trzeba jednak wziąć pod uwagę, że wójt ma trzy dni na rozpatrzenie wniosku. Na podstawie rejestru wyborców tworzony jest spis wyborców. Obywatele UE niebędący obywatelami polskimi (tak samo jak obywatele polscy) mogą głosować w wybranym lokalu wyborczym pod warunkiem złożenia pisemnego wniosku o dopisanie do spisu wyborców. Pisemny wniosek należy złożyć w gminie nie później niż pięć dni przed wyborami.
<strong>Jakie dokumenty należy zabrać ze sobą?</strong> <em>Dowód osobisty lub paszport</em>
<strong>Informacje dotyczące dostępności:</strong> Jeśli osoba niepełnosprawna zdecyduje się głosować osobiście:</p>
<ol>
<li>Ma prawo dostępu do pełnej informacji o lokalizacji najbliższych lokali wyborczych dostosowanych do jej potrzeb na terenie swojej gminy.</li>
<li>Lokale wyborcze powinny być specjalnie przygotowane do potrzeb osób z niepełnosprawnościami.</li>
<li>Obwieszczenia wyborcze i wyniki wyborów muszą być umieszczone w miejscach łatwo dostępnych dla osób o ograniczonej sprawności ruchowej.</li>
<li>Na prośbę wyborcy z niepełnosprawnością pracownik lokalu wyborczego jest zobowiązany do ustnego przekazania treści poszczególnych obwieszczeń wyborczych.</li>
<li>Wyborca z niepełnosprawnością może również skorzystać z nakładek na karty do głosowania sporządzonych w alfabecie Braille\'a.</li>
</ol>
<p>Osoby z niepełnosprawnościami chcące głosować mają do dyspozycji dwie dodatkowe formy głosowania: <strong>głosowanie korespondencyjne i głosowanie przez pełnomocnika</strong>.</p>
<p><strong>Głosowanie korespondencyjne:</strong> Głosowanie korespondencyjne jest dostępne wyłącznie dla wyborców z orzeczonym znacznym lub umiarkowanym stopniem niepełnosprawności głosujących w stałych obwodowych komisjach wyborczych w Polsce. Aby zagłosować korespondencyjnie, wyborca musi zgłosić to komisarzowi wyborczemu najpóźniej w 15. dniu przed dniem wyborów, ustnie, pisemnie, telefaksem lub w formie elektronicznej. Zgłoszenie powinno zawierać dane osobowe, informacje o wpisaniu do rejestru wyborców, oznaczenie wyborów oraz adres, na który ma być wysłany pakiet wyborczy. Do wniosku należy dołączyć kopię aktualnego orzeczenia o niepełnosprawności. Wyborca może zażądać nakładki na kartę do głosowania w alfabecie Braille\'a. Pakiet wyborczy jest wysyłany nie później niż 7 dni przed wyborami. Po wypełnieniu karty do głosowania wyborca zakleja ją w kopercie, umieszcza w kopercie zwrotnej wraz z podpisanym oświadczeniem i wysyła do okręgowej komisji wyborczej.</p>
<p><strong>Głosowanie przez pełnomocnika:</strong> Głosowanie przez pełnomocnika jest dostępne dla wyborców z orzeczonym znacznym lub umiarkowanym stopniem niepełnosprawności lub wyborców w wieku 60 lat lub starszych w dniu wyborów. Pełnomocnik musi być zarejestrowanym wyborcą w tej samej gminie lub posiadać zaświadczenie o prawie do głosowania. Pełnomocnika wyznacza burmistrz lub upoważniony pracownik gminy na wniosek wyborcy złożony co najmniej dziewięć dni przed wyborami. Wniosek powinien zawierać dane osobowe zarówno wyborcy, jak i pełnomocnika, a także wyraźny dokument tożsamości.</p>',
    's7' => '<p><em>Dla obywateli Polski i innych krajów UE:</em></p>
<p><strong>Gdzie mogę głosować?</strong> Nie musisz rejestrować swojego zamiaru głosowania w wyborach. Zostajesz wpisany do spisu wyborców na podstawie miejsca stałego zamieszkania i głosujesz w <strong>obwodowej komisji wyborczej w miejscu stałego zamieszkania</strong>.</p>
<p>Dodatkowe informacje_ <strong><em>dla obywateli UE</em></strong> <em>głosowanie w polskich wyborach do UE:</em> Każdy obywatel UE, który spełnia określone warunki, ma prawo do głosowania w wyborach do Parlamentu Europejskiego we wszystkich krajach Unii Europejskiej. W Polsce obywatele UE niebędący obywatelami polskimi stale zamieszkujący na obszarze gminy są wpisywani do rejestru wyborców, część B. Obywatele UE niebędący obywatelami polskimi muszą być wpisani do rejestru wyborców w gminie, w której mieszkają. Przepisy nie wskazują terminu, do którego należy złożyć wniosek o wpisanie do rejestru wyborców. Trzeba jednak wziąć pod uwagę, że wójt ma trzy dni na rozpatrzenie wniosku. Na podstawie rejestru wyborców tworzony jest spis wyborców. Obywatele UE niebędący obywatelami polskimi (tak samo jak obywatele polscy) mogą głosować w wybranym lokalu wyborczym pod warunkiem złożenia pisemnego wniosku o dopisanie do spisu wyborców. Pisemny wniosek należy złożyć w gminie nie później niż pięć dni przed wyborami.
**Jakie dokumenty należy zabrać ze sobą?</p>',
    's8' => '<p>Czy jesteś osobą niepełnosprawną lub doświadczasz ograniczeń uniemożliwiających Ci dotarcie do lokalu wyborczego?</p>',
    's8.1' => '<p>Tak</p>',
    's8.2' => '<p>Nie</p>',
    's9' => '<p>Dla obywateli Polski i innych państw UE:_.</p>
<p><strong>Gdzie mogę głosować?</strong>
Jeśli chcesz zostać dopisany do spisu wyborców w danej gminie, musisz zgłosić się do urzędu gminy, w której chcesz głosować, możesz też pobrać zaświadczenie o prawie do głosowania i zanieść je do wybranej przez siebie komisji wyborczej. W urzędzie gminy można <strong>sprawdzić</strong>, czy zostało się dopisanym do spisu wyborców, a jeśli nie, to najpóźniej w 5. dniu przed dniem wyborów można złożyć wniosek o dopisanie.</p>
<p>Dodatkowe informacje_ <strong><em>dla obywateli UE</em></strong> <em>głosowanie w polskich wyborach do UE:</em> Każdy obywatel UE, który spełnia określone warunki, ma prawo głosować w wyborach do Parlamentu Europejskiego we wszystkich krajach Unii Europejskiej. W Polsce obywatele UE niebędący obywatelami polskimi stale zamieszkujący na obszarze gminy są wpisywani do rejestru wyborców, część B. Obywatele UE niebędący obywatelami polskimi muszą być wpisani do rejestru wyborców w gminie, w której mieszkają. Przepisy nie wskazują terminu, do którego należy złożyć wniosek o wpisanie do rejestru wyborców. Trzeba jednak wziąć pod uwagę, że wójt ma trzy dni na rozpatrzenie wniosku. Na podstawie rejestru wyborców tworzony jest spis wyborców. Obywatele UE niebędący obywatelami polskimi (tak samo jak obywatele polscy) mogą głosować w wybranym lokalu wyborczym pod warunkiem złożenia pisemnego wniosku o dopisanie do spisu wyborców. Pisemny wniosek należy złożyć w gminie nie później niż pięć dni przed wyborami</p>
<p><strong><em>Jakie dokumenty należy zabrać ze sobą?</em></strong> <em>Dowód osobisty lub paszport.</em></p>
<p><strong>Informacje dotyczące dostępności:</strong> Jeśli osoba niepełnosprawna zdecyduje się głosować osobiście:</p>
<ol>
<li>Ma prawo dostępu do pełnej informacji o lokalizacji najbliższych lokali wyborczych dostosowanych do jej potrzeb na terenie swojej gminy.</li>
<li>Lokale wyborcze powinny być specjalnie przygotowane do potrzeb osób z niepełnosprawnościami.</li>
<li>Obwieszczenia wyborcze i wyniki wyborów muszą być umieszczone w miejscach łatwo dostępnych dla osób o ograniczonej sprawności ruchowej.</li>
<li>Na prośbę wyborcy z niepełnosprawnością pracownik lokalu wyborczego jest zobowiązany do ustnego przekazania treści poszczególnych obwieszczeń wyborczych.</li>
<li>Wyborca niepełnosprawny może również skorzystać z nakładek na karty do głosowania sporządzonych w alfabecie Braille\'a.</li>
</ol>
<p><strong>Osoby niepełnosprawne chcące głosować mają do dyspozycji dwie dodatkowe formy głosowania: głosowanie korespondencyjne oraz głosowanie przez pełnomocnika</strong>.</p>
<p><strong>Głosowanie korespondencyjne:</strong> Głosowanie korespondencyjne jest dostępne wyłącznie dla wyborców z orzeczonym znacznym lub umiarkowanym stopniem niepełnosprawności głosujących w stałych obwodowych komisjach wyborczych w Polsce. Aby zagłosować korespondencyjnie, wyborca musi powiadomić o tym komisarza wyborczego nie później niż 15. dnia przed dniem wyborów, ustnie, pisemnie, faksem lub elektronicznie. Zgłoszenie powinno zawierać dane osobowe, informacje o wpisaniu do rejestru wyborców, oznaczenie wyborów oraz adres, na który ma być wysłany pakiet wyborczy. Do wniosku należy dołączyć kopię aktualnego orzeczenia o niepełnosprawności. Wyborca może zażądać nakładki na kartę do głosowania w alfabecie Braille\'a. Pakiet wyborczy jest wysyłany nie później niż 7 dni przed wyborami. Po wypełnieniu karty do głosowania wyborca zakleja ją w kopercie na kartę do głosowania, umieszcza w kopercie zwrotnej wraz z podpisanym oświadczeniem i przesyła do okręgowej komisji wyborczej.</p>
<p><strong>Głosowanie przez pełnomocnika:</strong> Głosowanie przez pełnomocnika jest dostępne dla wyborców z potwierdzoną znaczną lub umiarkowaną niepełnosprawnością lub wyborców w wieku 60 lat lub starszych w dniu wyborów. Pełnomocnik musi być zarejestrowanym wyborcą w tej samej gminie lub posiadać zaświadczenie o prawie do głosowania. Pełnomocnika wyznacza burmistrz lub upoważniony pracownik gminy na wniosek wyborcy złożony co najmniej dziewięć dni przed wyborami. Wniosek powinien zawierać dane osobowe zarówno wyborcy, jak i pełnomocnika, a także wyraźny dokument tożsamości.</p>',
    's10' => '<p><em>Dla obywateli Polski i innych państw UE:</em></p>
<p><strong>Gdzie mogę głosować?</strong> Jeśli chcesz zostać dopisany do spisu wyborców w danej gminie, musisz zgłosić się do urzędu gminy, w której chcesz głosować, możesz też pobrać zaświadczenie o prawie do głosowania i zanieść je do wybranej przez siebie komisji wyborczej. W urzędzie gminy można <strong>sprawdzić</strong>, czy zostało się dopisanym do spisu wyborców, a jeśli nie, to najpóźniej w 5. dniu przed dniem wyborów można złożyć wniosek o dopisanie.</p>
<p><em>Dodatkowe informacje</em> <strong><em>dla obywateli UE</em></strong> <em>głosowanie w polskich wyborach do UE:</em>
Każdy obywatel UE, który spełnia określone warunki, ma prawo głosować w wyborach do Parlamentu Europejskiego we wszystkich krajach Unii Europejskiej. W Polsce obywatele UE niebędący obywatelami polskimi stale zamieszkujący na obszarze gminy są wpisywani do rejestru wyborców, część B. Obywatele UE niebędący obywatelami polskimi muszą być wpisani do rejestru wyborców w gminie, w której mieszkają. Przepisy nie wskazują terminu, do którego należy złożyć wniosek o wpisanie do rejestru wyborców. Trzeba jednak wziąć pod uwagę, że wójt ma trzy dni na rozpatrzenie wniosku. Na podstawie rejestru wyborców tworzony jest spis wyborców. Obywatele UE niebędący obywatelami polskimi (tak samo jak obywatele polscy) mogą głosować w wybranym lokalu wyborczym pod warunkiem złożenia pisemnego wniosku o dopisanie do spisu wyborców. Pisemny wniosek należy złożyć w gminie nie później niż pięć dni przed wyborami</p>
<p><strong>Jakie dokumenty należy zabrać ze sobą?</strong> Dowód osobisty lub paszport.</p>',
    's11' => '<p>Czy jesteś osobą niepełnosprawną lub doświadczasz ograniczeń uniemożliwiających Ci dotarcie do lokalu wyborczego?</p>',
    's11.1' => '<p>Tak</p>',
    's11.2' => '<p>Nie</p>',
    's12' => '<p><em>Dla obywateli Polski i innych państw UE:</em>.</p>
<p><strong>Gdzie mogę głosować?</strong> Jeśli chcesz głosować poza miejscem zamieszkania, masz dwie możliwości: możesz pobrać zaświadczenie o prawie do głosowania - wniosek składa się w urzędzie gminy, w której jesteś ujęty w spisie wyborców, najpóźniej w 3. dniu przed dniem wyborów. Wniosek można złożyć pisemnie, faksem lub elektronicznie. Z takim zaświadczeniem można głosować w <strong>każdym obwodzie głosowania na obszarze kraju</strong>. Możesz również złożyć pisemny wniosek o dopisanie do spisu wyborców w gminie, w której będziesz przebywać w dniu wyborów. Wniosek należy złożyć w urzędzie gminy najpóźniej w 3. dniu przed dniem wyborów.</p>
<p><em>Dodatkowe informacje</em> <strong><em>dla obywateli UE</em></strong> <em>głosowanie w polskich wyborach do UE:</em> Każdy obywatel UE, który spełnia określone warunki, ma prawo głosować w wyborach do Parlamentu Europejskiego we wszystkich krajach Unii Europejskiej. W Polsce obywatele UE niebędący obywatelami polskimi stale zamieszkujący na obszarze gminy są wpisywani do rejestru wyborców, część B. Obywatele UE niebędący obywatelami polskimi muszą być wpisani do rejestru wyborców w gminie, w której mieszkają. Przepisy nie wskazują terminu, do którego należy złożyć wniosek o wpisanie do rejestru wyborców. Trzeba jednak wziąć pod uwagę, że wójt ma trzy dni na rozpatrzenie wniosku. Na podstawie rejestru wyborców tworzony jest spis wyborców. Obywatele UE niebędący obywatelami polskimi (tak samo jak obywatele polscy) mogą głosować w wybranym lokalu wyborczym pod warunkiem złożenia pisemnego wniosku o dopisanie do spisu wyborców. Pisemny wniosek należy złożyć w gminie nie później niż pięć dni przed wyborami.</p>
<p>**Jakie dokumenty należy zabrać ze sobą? **Dowód osobisty lub paszport.</p>
<p><strong>Informacje dotyczące dostępności:</strong> Jeśli osoba niepełnosprawna zdecyduje się głosować osobiście:</p>
<ol>
<li>Ma prawo dostępu do pełnej informacji o lokalizacji najbliższych lokali wyborczych dostosowanych do jej potrzeb na terenie swojej gminy.</li>
<li>Lokale wyborcze powinny być specjalnie przygotowane do potrzeb osób z niepełnosprawnościami.</li>
<li>Obwieszczenia wyborcze i wyniki wyborów muszą być umieszczone w miejscach łatwo dostępnych dla osób o ograniczonej sprawności ruchowej.</li>
<li>Na prośbę wyborcy z niepełnosprawnością pracownik lokalu wyborczego jest zobowiązany do ustnego przekazania treści poszczególnych obwieszczeń wyborczych.</li>
<li>Wyborca niepełnosprawny może również skorzystać z nakładek na karty do głosowania sporządzonych w alfabecie Braille\'a.<br />
**Osoby niepełnosprawne chcące głosować mają do dyspozycji dwie dodatkowe formy głosowania: <strong>głosowanie korespondencyjne oraz głosowanie przez pełnomocnika</strong>.</li>
</ol>
<p><strong>Głosowanie korespondencyjne:</strong> Głosowanie korespondencyjne jest dostępne wyłącznie dla wyborców z orzeczonym znacznym lub umiarkowanym stopniem niepełnosprawności głosujących w stałych obwodowych komisjach wyborczych w Polsce. Aby zagłosować korespondencyjnie, wyborca musi powiadomić o tym komisarza wyborczego nie później niż 15. dnia przed dniem wyborów, ustnie, pisemnie, faksem lub elektronicznie. Zgłoszenie powinno zawierać dane osobowe, informacje o wpisaniu do rejestru wyborców, oznaczenie wyborów oraz adres, na który ma być wysłany pakiet wyborczy. Do wniosku należy dołączyć kopię aktualnego orzeczenia o niepełnosprawności. Wyborca może zażądać nakładki na kartę do głosowania w alfabecie Braille\'a. Pakiet wyborczy jest wysyłany nie później niż 7 dni przed wyborami. Po wypełnieniu karty do głosowania wyborca zakleja ją w kopercie na kartę do głosowania, umieszcza w kopercie zwrotnej wraz z podpisanym oświadczeniem i przesyła do okręgowej komisji wyborczej.</p>
<p><strong>Głosowanie przez pełnomocnika:</strong> Głosowanie przez pełnomocnika jest dostępne dla wyborców z potwierdzoną znaczną lub umiarkowaną niepełnosprawnością lub wyborców w wieku 60 lat lub starszych w dniu wyborów. Pełnomocnik musi być zarejestrowanym wyborcą w tej samej gminie lub posiadać zaświadczenie o prawie do głosowania. Pełnomocnika wyznacza burmistrz lub upoważniony pracownik gminy na wniosek wyborcy złożony co najmniej dziewięć dni przed wyborami. Wniosek powinien zawierać dane osobowe zarówno wyborcy, jak i pełnomocnika, a także wyraźny dokument tożsamości.</p>',
    's13' => '<p><em>Dla obywateli Polski i innych państw UE:</em></p>
<p><strong>Gdzie mogę głosować?</strong> Jeśli chcesz głosować poza miejscem zamieszkania, masz dwie możliwości: możesz pobrać zaświadczenie o prawie do głosowania - wniosek składa się w urzędzie gminy, w której jesteś ujęty w spisie wyborców, najpóźniej w 3. dniu przed dniem wyborów. Wniosek można złożyć pisemnie, faksem lub elektronicznie. Z takim zaświadczeniem można głosować w <strong>każdym obwodzie głosowania w kraju</strong>. <strong>Możesz też złożyć pisemny wniosek o dopisanie do spisu wyborców w gminie, w której będziesz przebywać w dniu wyborów</strong>. Wniosek należy złożyć w urzędzie gminy najpóźniej w 3. dniu przed dniem wyborów.</p>
<p><em>Dodatkowe informacje</em> <strong><em>dla obywateli UE</em></strong> <em>głosowanie w polskich wyborach do UE:</em>
Każdy obywatel UE, który spełnia określone warunki, ma prawo głosować w wyborach do Parlamentu Europejskiego we wszystkich krajach Unii Europejskiej. W Polsce obywatele UE niebędący obywatelami polskimi stale zamieszkujący na obszarze gminy są wpisywani do rejestru wyborców, część B. Obywatele UE niebędący obywatelami polskimi muszą być wpisani do rejestru wyborców w gminie, w której mieszkają. Przepisy nie wskazują terminu, do którego należy złożyć wniosek o wpisanie do rejestru wyborców. Trzeba jednak wziąć pod uwagę, że wójt ma trzy dni na rozpatrzenie wniosku. Na podstawie rejestru wyborców tworzony jest spis wyborców. Obywatele UE niebędący obywatelami polskimi (tak samo jak obywatele polscy) mogą głosować w wybranym lokalu wyborczym pod warunkiem złożenia pisemnego wniosku o dopisanie do spisu wyborców. Pisemny wniosek należy złożyć w gminie nie później niż pięć dni przed wyborami</p>
<p><strong>Jakie dokumenty należy zabrać ze sobą?</strong> Dowód osobisty lub paszport</p>',
    's14' => '<p>Inny kraj UE</p>',
    's14.1' => '<p>Jestem uprawniony i chcę głosować w <strong>polskich</strong> wyborach do UE <strong>z innego kraju UE</strong>.</p>',
    's14.2' => '<p>Jestem uprawniony i chcę głosować w wyborach do UE <strong>na inne państwo członkowskie UE.</strong></p>',
    's15' => '<p><strong>Gdzie mogę głosować?</strong> Wyborca przebywający w innym państwie UE, posiadający ważny polski paszport lub dowód osobisty może głosować na kandydatów startujących w wyborach w Polsce, jeżeli został wpisany do spisu wyborców sporządzanego przez właściwego terytorialnie konsula. Wpisu dokonuje się na podstawie osobistego wniosku złożonego ustnie, pisemnie, telefonicznie, telegraficznie, telefaksem lub w formie <a rel="noopener noreferrer" target="_blank" href="https://www.gov.pl/web/gov/uslugi-dla-obywatela/#meldunek-i-wybory/">elektronicznej</a> (w języku polskim). Zgłoszenia można dokonać najpóźniej w trzecim dniu przed dniem wyborów.</p>
<p>Lista polskich placówek za granicą znajduje się na <a rel="noopener noreferrer" target="_blank" href="https://www.gov.pl/web/dyplomacja/polskie-przedstawicielstwa-na-swiecie">stronie internetowej Ministerstwa Spraw Zagranicznych</a> (w języku polskim).</p>
<p><strong>Jakie dokumenty należy zabrać?</strong> Dowód osobisty lub paszport</p>',
    's16' => '<p>W wyborach w którym kraju UE weźmiesz udział jako wyborca?</p>',
    's17' => '<p>Poza UE</p>',
    's17.1' => '<p>Jestem uprawniony i chcę głosować w <strong>polskich</strong> wyborach do UE <strong>spoza UE</strong>.</p>',
    's17.2' => '<p>Jestem uprawniony i chcę głosować w wyborach do UE <strong>na inne państwo członkowskie UE.</strong></p>',
    's18' => '<p><strong>Gdzie mogę głosować?</strong> Jeśli jesteś obywatelem polskim mieszkającym poza Polską, możesz głosować w wyborach, jeśli istnieje wyznaczony okręg wyborczy dla Twojego obszaru. Obwód musi liczyć co najmniej 15 wyborców i być w stanie przesłać wyniki głosowania do komisji wyborczej zaraz po głosowaniu. Konsulowie <strong>informują o tych obwodach co najmniej 21 dni przed wyborami</strong>. Głosowanie za granicą jest możliwe osobiście w ambasadach i konsulatach, ale także w innych miejscach (np. kościołach i budynkach parafialnych, polskich ośrodkach kultury itp.) Polscy wyborcy przebywający za granicą</p>
<p>za granicą muszą złożyć wniosek o dopisanie do spisu wyborców sporządzanego przez właściwego konsula najpóźniej w 5. dniu przed dniem wyborów. Wpisu dokonuje się na podstawie osobistego wniosku złożonego ustnie, pisemnie, telefonicznie, telegraficznie, telefaksem lub <a rel="noopener noreferrer" target="_blank" href="https://www.gov.pl/web/gov/uslugi-dla-obywatela/#meldunek-i-wybory/">elektronicznie</a> (w języku polskim).Ponadto wyborcy zmieniający miejsce pobytu w okresie zbliżonym do wyborów mogą wystąpić z wnioskiem o wydanie zaświadczenia o prawie do głosowania w okresie od 44 do 3 dni przed wyborami. Jeżeli wyborca jest wpisany do spisu wyborców za granicą, zaświadczenie wydaje</p>
<p>zaświadczenie jest wydawane przez właściwego konsula i uprawnia do głosowania w dowolnym lokalu wyborczym za granicą lub w Polsce.</p>
<p><strong>Jakie dokumenty należy zabrać?</strong> Dowód osobisty lub paszport</p>',
    's19' => '<p>W wyborach w którym kraju UE weźmiesz udział jako wyborca?</p>',
];
