<?php
return [
    'intro_1' => 'Szanujemy Twoją prywatność i zdajemy sobie sprawę, że musimy przechowywać i wykorzystywać Twoje dane w sposób odpowiedzialny.',
    'title' => 'Polityka prywatności',
    'intro_2' => 'wevote4.eu to strona internetowa stworzona przez Commit Global („Commit Global”, „my”, „nas”, „nasz”) w celu informowania opinii publicznej o wyborach europejskich.',
    'line_6_1' => 'Dezaktywacja plików cookie nie pozwoli użytkownikom na dostęp do niektórych najważniejszych stron internetowych, takich jak Youtube, Gmail, Yahoo i inne. Oto kilka porad, które pomogą Ci bezpiecznie przeglądać przy zachowaniu plików cookie:',
    'line_3_4' => 'Istnieją pliki cookie, które są używane wyłącznie na jedną sesję - nie są one już przechowywane po opuszczeniu strony przez użytkownika. Stałe pliki cookie są przechowywane i ponownie wykorzystywane za każdym razem, gdy użytkownik wraca na tę stronę, ale mogą zostać usunięte w dowolnym momencie przez użytkownika.',
    'subtitle_4' => 'Jak zablokować/zrezygnować z używania plików cookie',
    'subtitle_2' => 'Integracje stron trzecich',
    'line_4_3' => 'Możesz skonfigurować przeglądarkę tak, aby automatycznie odrzucała pliki cookie lub wybrać tylko niektóre strony internetowe, w których włączone są pliki cookie. Ale, na przykład, jeśli wyłączysz pliki cookie na tej stronie, nie możesz wykonać kolejnych kroków wypełniania formularza.',
    'subtitle_6' => 'Porady dotyczące bezpiecznego i odpowiedzialnego przeglądania plików cookie',
    'line_3_3' => '- Cookies sesyjne - to pliki cookie tymczasowo przechowywane w historii przeglądarki, gdzie są przechowywane do momentu opuszczenia przez użytkownika tej strony internetowej lub zamknięcia okna przeglądarki.
- Trwałe pliki cookie - są one przechowywane przez określony czas na dysku twardym komputera lub podobnym sprzęcie. Trwałe pliki cookie obejmują pliki umieszczane przez inną stronę internetową niż ta, którą użytkownik odwiedza w danym momencie, tzw. „pliki cookie stron trzecich” - które mogą być anonimowo wykorzystywane do śledzenia zainteresowań użytkownika - umożliwiając mu otrzymywanie reklam bardziej odpowiadających jego zainteresowaniom.',
    'line_3_1' => 'Plik cookie („cookie przeglądarki” lub „plik cookie HTTP”) to mały plik, ciąg liter i cyfr, który jest przechowywany na dowolnym terminalu z dostępem do Internetu (komputery, telefony komórkowe, tablety itp.) i instalowany na żądanie serwera do przeglądarki (np. Internet Explorer, Chrome). „Pliki cookie” nie zawierają żadnych programów, wirusów ani programów szpiegujących i nie mogą uzyskać dostępu do informacji na dysku twardym użytkownika. Plik cookie składa się z nazwy i treści, długość jego istnienia jest ograniczona i może być ponownie dostępny przez serwer WWW, gdy użytkownik powróci do strony internetowej powiązanej z tym serwerem.',
    'line_7_5' => 'Niniejsza wersja Regulaminu wevotefor.eu wchodzi w życie z dniem 23 maja 2024 r. ',
    'line_2_1' => 'Commit Global korzysta z Google Analytics, aby lepiej zrozumieć, w jaki sposób odwiedzający poruszają się po naszej witrynie, aby poprawić ich ogólne wrażenia. Google Analytics nie zbiera żadnych możliwych do zidentyfikowania informacji o swoich odwiedzających i nie przetwarzamy danych zebranych za pośrednictwem naszych formularzy wraz z danymi dostarczonymi przez Google Analytics.',
    'line_5_1' => 'Mogą wystąpić sytuacje, w których, zgodnie z wymaganiami prawa, możemy zostać poproszeni o ujawnienie danych osobowych zebranych za pośrednictwem tej strony internetowej. Możemy uzyskać dostęp, przechowywać i ujawniać Twoje dane, jeśli zostaną one wymagane w celu spełnienia wymogów egzekwowania prawa i procesów prawnych, takich jak nakazy sądowe lub jeśli zostaną wezwane, lub jeśli może to chronić prawa użytkownika, własność lub ogólne bezpieczeństwo innych osób.',
    'line_1_2' => 'Po odwiedzeniu strony wevote4.eu będziemy automatycznie zbierać i przechowywać dane o Twojej bieżącej wizycie. Informacje te nie są identyfikowalne. Informacje, które możemy gromadzić, to: system operacyjny na urządzeniu użytkownika, przeglądarka, z której korzystasz, strony w witrynie wevote4.eu, które odwiedzasz, źródło Twojej wizyty (np. Google, Facebook), data i godzina wizyty oraz domena, z której uzyskujesz dostęp do Internetu. Wszystkie te informacje są wykorzystywane do dalszej poprawy nawigacji na naszej stronie internetowej i zrozumienia preferencji naszych odwiedzających. Nie będziemy zbierać żadnych danych osobowych za pośrednictwem tej strony internetowej bez Twojej wyraźnej zgody.',
    'line_1_1' => '- Zbieramy informacje od Ciebie, jeśli uzyskujesz dostęp do tej witryny za pośrednictwem zwykłej przeglądarki.
- Ta strona korzysta z plików cookie (np. Google Analytics) w celu pomiaru i optymalizacji doświadczenia dla wszystkich użytkowników.
- Commit Global nie ujawnia ani nie sprzedaje Twoich danych osobowych osobom trzecim, z wyjątkiem sytuacji prawnie wiążących opisanych w niniejszej Polityce prywatności.
- Commit Global podejmie wszelkie uzasadnione środki w celu ochrony Twoich danych osobowych, ponieważ jest to dla nas poważny problem.',
    'line_6_3' => 'Pliki cookie są wszędzie i nie można ich uniknąć, jeśli chcesz uzyskać dostęp do niektórych z największych i najlepszych stron internetowych w Internecie, zarówno lokalnych, jak i międzynarodowych. Jasne zrozumienie sposobu działania plików cookie i korzyści, jakie przynoszą, może podjąć niezbędne środki bezpieczeństwa, aby zawsze mieć bezpieczne i satysfakcjonujące wrażenia z przeglądania.',
    'line_4_1' => 'Pliki cookie są jednym z najważniejszych narzędzi zapewniających płynne i wydajne korzystanie z Internetu, pomagając generować przyjazne przeglądanie, dostosowane do potrzeb każdego użytkownika. Odmowa akceptacji plików cookie lub ich dezaktywacja może uniemożliwić korzystanie z niektórych stron internetowych. Odmowa akceptacji plików cookie lub ich dezaktywacja nie oznacza, że nie będziesz już otrzymywać reklam online, tylko że reklamy te nie będą już uwzględniać Twoich zainteresowań lub preferencji określonych przez Twoje zachowanie podczas przeglądania.',
    'line_4_5' => 'Więcej ogólnych informacji na temat plików cookie i sposobu ich dezaktywacji można znaleźć na stronie www.aboutcookies.org.',
    'line_2_2' => 'Google Analytics umieści plik cookie w Twojej przeglądarce, aby zidentyfikować użytkownika jako unikalnego użytkownika i odpowiednio zebrać informacje o Twojej nawigacji. Ten plik cookie jest używany wyłącznie przez Google, który z kolei jest ograniczony do udostępniania i wykorzystywania tych danych przez własne Warunki użytkowania Google Analytics i Politykę prywatności Google.',
    'intro_3' => 'Niniejsza Polityka Prywatności opisuje, w jaki sposób zbieramy, wykorzystujemy i chronimy Twoje dane osobowe na tej stronie internetowej. Przesyłając swoje dane osobowe na tej stronie, zgadzasz się na warunki niniejszej Polityki prywatności. Jeśli nie zgadzasz się z niniejszymi warunkami, nie korzystaj z naszej strony internetowej.',
    'line_7_4' => 'Commit Global zastrzega sobie prawo do zmiany i aktualizacji niniejszej polityki w dowolnym momencie, bez powiadomienia lub uprzedniej akceptacji użytkowników. Jeśli masz jakiekolwiek pytania dotyczące informacji zawartych na tej stronie, napisz do nas na adres ',
    'subtitle_5' => 'Udostępnianie danych',
    'subtitle_3' => 'Czym są pliki cookie',
    'line_7_3' => 'Niniejsza polityka stanowi w całości umowę zawartą między Tobą a Commit Global dotyczącą korzystania z tej witryny.',
    'line_6_2' => '- Dostosuj ustawienia plików cookie przeglądarki, aby zapewnić wygodny poziom bezpieczeństwa. Jeśli pliki cookie nie stanowią dla Ciebie problemu i jesteś jedyną osobą korzystającą z tego urządzenia, możesz ustawić długie okresy przechowywania plików cookie w celu przechowywania historii przeglądania i danych osobowych dostępu.
- Jeśli udostępniasz urządzenie lub komputer, możesz skonfigurować przeglądarkę tak, aby usuwała poszczególne dane przeglądania za każdym razem, gdy jest zamknięta. Jest to jeden ze sposobów uzyskania dostępu do stron internetowych, które umieszczają pliki cookie na udostępnionym komputerze, jednocześnie usuwając wszystkie dane przeglądania podczas zamykania sesji.
- zainstaluj aplikację antyspyware i aktualizuj ją. Wiele aplikacji anty-spyware obejmuje wykrywanie ataków na stronie internetowej. Te aplikacje uniemożliwiają przeglądarce dostęp do stron internetowych, które mogą wykorzystywać luki w zabezpieczeniach przeglądarki lub pobierać niebezpieczne oprogramowanie. Upewnij się, że Twoja przeglądarka jest aktualna. Wiele ataków opartych na plikach cookie wykorzystuje słabe strony starych wersji przeglądarki.',
    'subtitle_1' => 'Gromadzenie danych',
    'line_4_2' => 'Odmowa akceptacji plików cookie lub ich dezaktywacja może utrudnić lub uniemożliwić nawigację lub korzystanie z niektórych stron internetowych. Odmowa akceptacji plików cookie nie oznacza również, że nie będziesz już otrzymywać reklam online.',
    'line_3_2' => 'Pliki cookie zapisują informacje w małym pliku tekstowym umożliwiającym witrynie rozpoznanie przeglądarki. Serwer WWW rozpozna przeglądarkę do czasu wygaśnięcia lub usunięcia pliku cookie. Plik cookie przechowuje ważne informacje, które poprawiają jakość przeglądania (np. numer seryjny Twojej darowizny). Pliki cookie nie wymagają danych osobowych ani nie identyfikują użytkowników Internetu.',
    'line_4_4' => 'Nowoczesne przeglądarki oferują możliwość zmiany ustawień plików cookie. Zazwyczaj ustawienia plików cookie można znaleźć w zakładce „Opcje” lub w menu „preferencje” przeglądarki.',
    'subtitle_7' => 'Twoje prawa',
    'line_7_1' => 'Jako użytkownik strony internetowej wevote4.eu przysługują Ci następujące prawa:',
    'line_7_2' => '- Prawo do informacji dotyczących przetwarzania danych osobowych przez Commit Global;
- Prawo dostępu do danych osobowych, na żądanie i bezpłatnie na jedno żądanie rocznie;
- prawo do interwencji, sprostowania, usunięcia lub przenoszenia danych osobowych, na żądanie i bezpłatnie;
- Prawo do zwrócenia się do każdego właściwego organu w sprawie kwestii prywatności danych w związku z wykorzystaniem Twoich danych osobowych
- Prawo do sprzeciwu i zautomatyzowany indywidualny proces decyzyjny oraz prawo do ograniczenia przetwarzania.',
];
