<?php

return [
  's1' => '<p>Are you at least 18 on the day of voting?</p>',
  's1.1' => '<p>I am under 18</p>',
  's2' => '<p>You can\'t vote: Thank you for your interest in getting involved! We are looking forward to seeing you at the next elections. In the meantime, keep being an active citizen!</p>',
  's1.2' => '<p>I am 18 or over 18</p>',
  's3' => '<p>On the day of the election, which country do you want to vote from?</p>',
  's3.1' => '<p>Poland</p>',
  's3.2' => '<p>Another EU country</p>',
  's3.3' => '<p>Outside EU</p>',
  's4' => '<p>Do you 1. intend to vote at the district electoral commission of your permanent residence 2. have you changed your address and  you want to be added to the roll of voters in a given commune or 3.Do you want to vote outside your place of residence</p>',
  's4.1' => '<p>I intend to vote at the district of electoral commission of my permanent residence</p>',
  's4.2' => '<p>My address has changed and I want to be added to the roll of voters in a given commune</p>',
  's4.3' => '<p>I want to vote outside my place of residence</p>',
  's5' => '<p>Do you have a disability or experience any limitations preventing you from reaching a polling station?</p>',
  's5.1' => '<p>Yes</p>',
  's5.2' => '<p>No</p>',
  's6' => '<p><em>For Polish and other EU citizens:</em></p>
<p><strong>Where do I vote?</strong> You do not have to register your intention to vote in the elections. You are entered into the electoral register based on your place of permanent residence and vote in a <strong>district electoral commission at your place of permanent residence.</strong></p>
<p><em>Additional info</em> <strong><em>for EU citizen</em></strong> <em>voting in Polish EU elections:</em> Every EU citizen who fulfils certain conditions has the right to vote in European Parliament elections in all European Union countries. In Poland, non-Polish EU citizens permanently residing in the area of the commune are entered on the register of voters, part B. Non-Polish EU citizens must be registered in the register of voters at the municipality where they live. The regulations do not indicate the date by which the request for entry in the register of voters must be submitted. However, you have to take into account that the mayor has three days to process the application. Based on the register of voters, an electoral roll is created. EU citizens who are not Polish citizens (the same as Polish citizens) may vote at a chosen polling station provided that they submit a request in writing for entry on the electoral roll. The written request has to be made to the municipality no later than five days prior to the election.</p>
<p><strong>What documents should I bring?</strong> <em>ID card or passport</em></p>
<p><strong>Accessibility Information:</strong> If a person with disabilities chooses to vote in person:</p>
<ol>
<li>They have the right to access full information about the location of the nearest polling stations adapted to their needs within their commune.</li>
<li>Polling stations should be specially prepared to cater to the needs of individuals with disabilities.</li>
<li>Election announcements and results must be placed in locations easily accessible to individuals with reduced mobility.</li>
<li>At the request of a voter with disabilities, a member of the polling station is obliged to orally convey the content of specific electoral announcements.</li>
<li>A voter with disabilities may also use overlays for voting cards made in Braille.</li>
</ol>
<p>People with disabilities willing to vote have two additional forms of voting: <strong>Postal voting and proxy voting.</strong></p>
<p><strong>Postal Voting:</strong> Postal voting is available only to voters with confirmed significant or moderate disabilities voting in permanent district electoral commissions in Poland. To vote by correspondence, the voter must inform the electoral commissioner no later than the 15th day before the election, orally, in writing, by fax, or electronically. The application should include personal details, voter registration information, election designation, and the address for the electoral package. A copy of the current disability determination must accompany the application. The voter can request a Braille ballot overlay. The electoral package is sent no later than 7 days before the election. After completing the ballot, the voter seals it in the ballot envelope, places it in the return envelope with a signed declaration, and sends it to the district commission.</p>
<p><strong>Proxy Voting:</strong> Proxy voting is available for voters with confirmed severe or moderate disabilities or voters aged 60 or older on election day. The proxy must be a registered voter in the same municipality or have a voting entitlement certificate. The proxy is appointed before the mayor or an authorized municipal employee, requested by the voter at least nine days before the election. The application should include personal details of both the voter and the proxy, as well as clear election identification.</p>',
  's7' => '<p><em>For Polish and other EU citizens:</em></p>
<p><strong>Where do I vote?</strong> You do not have to register your intention to vote in the elections. You are entered into the electoral register based on your place of permanent residence and vote in a <strong>district electoral commission at your place of permanent residence.</strong></p>
<p><em>Additional info for EU citizen voting in Polish EU elections:</em> Every EU citizen who fulfils certain conditions has the right to vote in European Parliament elections in all European Union countries. In Poland, non-Polish EU citizens permanently residing in the area of the commune are entered on the register of voters, part B. Non-Polish EU citizens must be registered in the register of voters at the municipality where they live. The regulations do not indicate the date by which the request for entry in the register of voters must be submitted. However, you have to take into account that the mayor has three days to process the application. Based on the register of voters, an electoral roll is created. EU citizens who are not Polish citizens (the same as Polish citizens) may vote at a chosen polling station provided that they submit a request in writing for entry on the electoral roll. The written request has to be made to the municipality no later than five days prior to the election.</p>
<p><strong>What documents should I bring?</strong> ID card or passport</p>',
  's8' => '<p>Do you have a disability or experience any limitations preventing you from reaching a polling station?</p>',
  's8.1' => '<p>Yes</p>',
  's8.2' => '<p>No</p>',
  's9' => '<p>For Polish and other EU citizens:</p>
<p><strong>Where do I vote?</strong> If you want to be added to the roll of voters in a given commune, you must report to the office of the commune where you want to vote, you can also download a certificate of voting rights and take it to the electoral commission of your choice. You can <strong>check at the commune office</strong> whether you have been included in the voter roll, and if not, you can submit an application to be added no later than the 5th day before election day.</p>
<p><em>Additional info</em> <strong><em>for EU citizen</em></strong> <em>voting in Polish EU elections:</em> <em>Every EU citizen who fulfils certain conditions has the right to vote in European Parliament elections in all European Union countries. In Poland, non-Polish EU citizens permanently residing in the area of the commune are entered on the register of voters, part B. Non-Polish EU citizens must be registered in the register of voters at the municipality where they live. The regulations do not indicate the date by which the request for entry in the register of voters must be submitted. However, you have to take into account that the mayor has three days to process the application. Based on the register of voters, an electoral roll is created. EU citizens who are not Polish citizens (the same as Polish citizens) may vote at a chosen polling station provided that they submit a request in writing for entry on the electoral roll. The written request has to be made to the municipality no later than five days prior to the election.</em></p>
<p><strong><em>What documents should I bring?</em></strong> <em>ID card or passport</em></p>
<p><strong>Accessibility Information:</strong> If a person with disabilities chooses to vote in person:</p>
<ol>
<li>They have the right to access full information about the location of the nearest polling stations adapted to their needs within their commune.</li>
<li>Polling stations should be specially prepared to cater to the needs of individuals with disabilities.</li>
<li>Election announcements and results must be placed in locations easily accessible to individuals with reduced mobility.</li>
<li>At the request of a voter with disabilities, a member of the polling station is obliged to orally convey the content of specific electoral announcements.</li>
<li>A voter with disabilities may also use overlays for voting cards made in Braille.</li>
</ol>
<p><strong>People with disabilities willing to vote have two additional forms of voting: Postal voting and proxy voting.</strong></p>
<p><strong>Postal Voting:</strong> Postal voting is available only to voters with confirmed significant or moderate disabilities voting in permanent district electoral commissions in Poland. To vote by correspondence, the voter must inform the electoral commissioner no later than the 15th day before the election, orally, in writing, by fax, or electronically. The application should include personal details, voter registration information, election designation, and the address for the electoral package. A copy of the current disability determination must accompany the application. The voter can request a Braille ballot overlay. The electoral package is sent no later than 7 days before the election. After completing the ballot, the voter seals it in the ballot envelope, places it in the return envelope with a signed declaration, and sends it to the district commission.</p>
<p><strong>Proxy Voting:</strong> Proxy voting is available for voters with confirmed severe or moderate disabilities or voters aged 60 or older on election day. The proxy must be a registered voter in the same municipality or have a voting entitlement certificate. The proxy is appointed before the mayor or an authorized municipal employee, requested by the voter at least nine days before the election. The application should include personal details of both the voter and the proxy, as well as clear election identification.</p>',
  's10' => '<p><em>For Polish and other EU citizens:</em></p>
<p><strong>Where do I vote?</strong> If you want to be added to the roll of voters in a given commune, you must report to the office of the commune where you want to vote, you can also download a certificate of voting rights and take it to the electoral commission of your choice. You can <strong>check at the commune office</strong> whether you have been included in the voter roll, and if not, you can submit an application to be added no later than the 5th day before election day.</p>
<p><em>Additional info</em> <strong><em>for EU citizen</em></strong> <em>voting in Polish EU elections:</em> Every EU citizen who fulfils certain conditions has the right to vote in European Parliament elections in all European Union countries. In Poland, non-Polish EU citizens permanently residing in the area of the commune are entered on the register of voters, part B. Non-Polish EU citizens must be registered in the register of voters at the municipality where they live. The regulations do not indicate the date by which the request for entry in the register of voters must be submitted. However, you have to take into account that the mayor has three days to process the application. Based on the register of voters, an electoral roll is created. EU citizens who are not Polish citizens (the same as Polish citizens) may vote at a chosen polling station provided that they submit a request in writing for entry on the electoral roll. The written request has to be made to the municipality no later than five days prior to the election.</p>
<p><strong>What documents should I bring?</strong> ID card or passport</p>',
  's11' => '<p>Do you have a disability or experience any limitations preventing you from reaching a polling station?</p>',
  's11.1' => '<p>Yes</p>',
  's11.2' => '<p>No</p>',
  's12' => '<p><em>For Polish and other EU citizens:</em></p>
<p><strong>Where do I vote?</strong> If you want to vote outside your place of residence, you have two options: you can download a certificate of voting rights - the application is submitted to the office of the commune where you are included in the voter roll no later than the third day before election day. You can submit your application in writing, by fax or electronically. With such a certificate, you can vote in <strong>any voting district in the country</strong>. You can also submit a written request to be added to the voter roll in the commune where you will be staying on election day. The application must be submitted to the municipal office no later than the 3rd day before election day.</p>
<p><em>Additional info</em> <strong><em>for EU citizen</em></strong> <em>voting in Polish EU elections:</em> Every EU citizen who fulfils certain conditions has the right to vote in European Parliament elections in all European Union countries. In Poland, non-Polish EU citizens permanently residing in the area of the commune are entered on the register of voters, part B. Non-Polish EU citizens must be registered in the register of voters at the municipality where they live. The regulations do not indicate the date by which the request for entry in the register of voters must be submitted. However, you have to take into account that the mayor has three days to process the application. Based on the register of voters, an electoral roll is created. EU citizens who are not Polish citizens (the same as Polish citizens) may vote at a chosen polling station provided that they submit a request in writing for entry on the electoral roll. The written request has to be made to the municipality no later than five days prior to the election.</p>
<p><strong>What documents should I bring?</strong> ID card or passport</p>
<p><strong>Accessibility Information:</strong> If a person with disabilities chooses to vote in person:</p>
<ol>
<li>They have the right to access full information about the location of the nearest polling stations adapted to their needs within their commune.</li>
<li>Polling stations should be specially prepared to cater to the needs of individuals with disabilities.</li>
<li>Election announcements and results must be placed in locations easily accessible to individuals with reduced mobility.</li>
<li>At the request of a voter with disabilities, a member of the polling station is obliged to orally convey the content of specific electoral announcements.</li>
<li>A voter with disabilities may also use overlays for voting cards made in Braille.</li>
</ol>
<p><strong>People with disabilities willing to vote have two additional forms of voting: Postal voting and proxy voting.</strong></p>
<p><strong>Postal Voting:</strong> Postal voting is available only to voters with confirmed significant or moderate disabilities voting in permanent district electoral commissions in Poland. To vote by correspondence, the voter must inform the electoral commissioner no later than the 15th day before the election, orally, in writing, by fax, or electronically. The application should include personal details, voter registration information, election designation, and the address for the electoral package. A copy of the current disability determination must accompany the application. The voter can request a Braille ballot overlay. The electoral package is sent no later than 7 days before the election. After completing the ballot, the voter seals it in the ballot envelope, places it in the return envelope with a signed declaration, and sends it to the district commission.</p>
<p><strong>Proxy Voting:</strong> Proxy voting is available for voters with confirmed severe or moderate disabilities or voters aged 60 or older on election day. The proxy must be a registered voter in the same municipality or have a voting entitlement certificate. The proxy is appointed before the mayor or an authorized municipal employee, requested by the voter at least nine days before the election. The application should include personal details of both the voter and the proxy, as well as clear election identification.</p>',
  's13' => '<p><em>For Polish and other EU citizens:</em></p>
<p><strong>Where do I vote?</strong> If you want to vote outside your place of residence, you have two options: you can download a certificate of voting rights - the application is submitted to the office of the commune where you are included in the voter roll no later than the third day before election day. You can submit your application in writing, by fax or electronically. With such a certificate, you can vote in <strong>any voting district in the country</strong>. <strong>or</strong> you can also submit a written request to be added to the <strong>voter roll in the commune where you will be staying on election day.</strong> The application must be submitted to the municipal office no later than the 3rd day before election day.</p>
<p><em>Additional info</em> <strong><em>for EU citizen</em></strong> <em>voting in Polish EU elections:</em> Every EU citizen who fulfils certain conditions has the right to vote in European Parliament elections in all European Union countries. In Poland, non-Polish EU citizens permanently residing in the area of the commune are entered on the register of voters, part B. Non-Polish EU citizens must be registered in the register of voters at the municipality where they live. The regulations do not indicate the date by which the request for entry in the register of voters must be submitted. However, you have to take into account that the mayor has three days to process the application. Based on the register of voters, an electoral roll is created. EU citizens who are not Polish citizens (the same as Polish citizens) may vote at a chosen polling station provided that they submit a request in writing for entry on the electoral roll. The written request has to be made to the municipality no later than five days prior to the election.</p>
<p><strong>What documents should I bring?</strong> ID card or passport</p>',
  's14' => '<p>Another EU country</p>',
  's14.1' => '<p>I am eligible to and want to vote in <strong>Polish</strong> EU elections <strong>from another EU country.</strong></p>',
  's14.2' => '<p>I am eligible and want to vote in EU elections <strong>for another EU member state.</strong></p>',
  's15' => '<p><strong>Where do I vote?</strong> A voter staying in another EU country, holding a valid Polish passport or identity card may vote for candidates running in the elections in Poland if they entered in the register of electors drawn up by the territorially competent consul. The entry is made on the basis of a personal application submitted orally, in writing, by telephone, telegraph, telefax or in <a rel="noopener noreferrer" target="_blank" href="https://www.gov.pl/web/gov/uslugi-dla-obywatela/#meldunek-i-wybory/">electronic form</a> (in Polish). The application can be made no later than on the third day before election day.</p>
<p>List of Polish posts abroad can be found on <a rel="noopener noreferrer" target="_blank" href="https://www.gov.pl/web/dyplomacja/polskie-przedstawicielstwa-na-swiecie">the website of Ministry of Foreign Affairs</a> (in Polish).</p>
<p><strong>What documents should I bring?</strong> ID card or passport</p>',
  's16' => '<p>Which EU country\'s elections will you be participating in as a voter?</p>',
  's17' => '<p>Outside EU</p>',
  's17.1' => '<p>I am eligible to and want to vote in <strong>Polish</strong> EU elections <strong>from outside of the EU</strong>.</p>',
  's17.2' => '<p>I am eligible and want to vote in EU elections <strong>for another EU member state.</strong></p>',
  's18' => '<p><strong>Where do I vote?</strong> If you\'re a Polish citizen living outside Poland, you can vote in elections if there\'s a designated district for your area. The district needs to have at least 15 voters and be able to send the voting results to the election commission right after the vote. Consuls <strong>will let you know about these districts at least 21 days before the election.</strong> Voting abroad is possible in person in embassies and consulates, but also in other places (e.g. churches and parish buildings, Polish cultural centres, etc.). Polish voters who are staying</p>
<p>abroad must request to be registered on the electoral roll drawn up by the competent consul no later than the fifth day before elections. The entry is made on the basis of a personal application submitted orally, in writing, by telephone, telegraph, telefax or <a rel="noopener noreferrer" target="_blank" href="https://www.gov.pl/web/gov/uslugi-dla-obywatela/#meldunek-i-wybory/">electronically</a> (in Polish).Moreover, voters who change the place where they are staying close to the elections may request a certificate stating their right to vote between 44 and three days before the elections. If a voter is registered on an electoral roll</p>
<p>abroad, the certificate is issued by the competent consul, allowing the person to vote in any other polling station abroad or in Poland.</p>
<p><strong>What documents should I bring?</strong> ID card or passport</p>',
  's19' => '<p>Which EU country\'s elections will you be participating in as a voter?</p>',
];
