<?php

declare(strict_types=1);

return [
    'title' => 'À propos du projet',
    'line_1' => 'Imaginez un événement électoral unique et dynamique qui réunirait plus de 400 millions de citoyens à travers l\'Union européenne. Les élections européennes ne sont pas simplement une série de votes nationaux, mais une célébration collective de notre identité commune et de nos valeurs démocratiques. En tant que citoyens de l\'UE, nous nous unissons pour façonner notre avenir commun, en transcendant les frontières et en valorisant la force de notre diversité. Ce projet témoigne de notre unité, en permettant à chaque citoyen, où qu\'il se trouve dans l\'UE, de participer plus facilement à ce puissant processus démocratique.',
    'line_2' => 'Pour soutenir cette vision d\'un processus électoral unifié, Commit Global a créé une plateforme, **We Vote for EU**, qui incarne l\'idée d\'unité et de collaboration. Cette plateforme fournit à tous les citoyens de l\'UE des informations essentielles sur la manière de voter et de trouver rapidement des bureaux de vote, où qu\'ils se trouvent.',
    'subtitle' => 'Qu\'est-ce qui rend cette plateforme si spéciale ?',
    'line_3' => '**Format d\'arbre de décision :** La plateforme utilise un format d\'arbre de décision qui oriente directement les citoyens de l\'UE vers les informations spécifiques dont ils ont besoin.',
    'line_4' => '**Informations complètes :** Les informations finales fournies sont complètes et couvrent les exigences d\'inscription (le cas échéant), les différentes méthodes de vote (par procuration, en ligne, postal, bureau de vote), la documentation requise pour voter et l\'assistance aux électeurs handicapés ou ayant d\'autres limitations.',
    'line_5' => '**Informations vérifiées :** Les informations présentées sur le site Web proviennent de plusieurs sources différentes, notamment des ministères nationaux et des organisations responsables des règles et procédures de vote, ainsi que de la plateforme du Parlement européen.',
    'line_6' => '**Accessibilité multilingue :** Nous veillons à ce que chaque citoyen de l\'UE puisse accéder aux informations dont il a besoin dans sa propre langue. La plateforme est disponible en 26 langues, l\'arbre de décision de chaque pays étant fourni dans sa ou ses langues officielles et en anglais. Cela garantit que chacun, quelle que soit son origine linguistique, peut naviguer sans effort dans le processus de vote.',
    'line_7' => '**Conseils interconnectés :** Indépendamment de la nationalité européenne de l\'électeur, de son pays de résidence ou de sa situation géographique le jour des élections, la plateforme fournit des instructions et des informations précises et adaptées à sa situation unique. C\'est comme avoir un assistant de vote personnalisé qui rend le processus fluide et inspirant.',
    'line_8' => 'We Vote for EU est une plateforme créée et gérée par **Commit Global**, la première ONG mondiale de technologie civique au monde. Avec son siège social à La Haye (Pays-Bas), Commit Global consolide, maintient et fournit un accès gratuit au numérique critique, l\' **Infrastructure for Good**, aux organisations de la société civile et aux populations touchées du monde entier. Pour plus d\'informations sur notre travail, veuillez consulter [notre site Web](https://www.commitglobal.org).',
];
