<?php
return [
    'subtitle_2' => 'Intégrations tierces',
    'subtitle_5' => 'Partage de données',
    'line_7_5' => 'Cette version des conditions générales de wevotefor.eu entre en vigueur le 23 mai 2024. ',
    'line_6_1' => 'La désactivation des cookies ne permettra plus aux utilisateurs d\'accéder à certains des sites Web les plus importants tels que Youtube, Gmail, Yahoo et autres. Voici quelques conseils qui peuvent vous aider à naviguer en toute sécurité tout en conservant les cookies :',
    'line_3_4' => 'Certains cookies ne sont utilisés que pour une seule session ; ils ne sont plus stockés une fois que l\'utilisateur a quitté le site Web. Les cookies permanents sont stockés et réutilisés chaque fois que l\'utilisateur revient sur ce site Web, mais ils peuvent être supprimés à tout moment par l\'utilisateur.',
    'subtitle_4' => 'Comment bloquer/désactiver l\'utilisation de cookies',
    'line_7_1' => 'En tant qu\'utilisateur du site web wevote4.eu, vous disposez des droits suivants :',
    'line_4_3' => 'Vous pouvez configurer votre navigateur pour qu\'il rejette automatiquement les cookies ou sélectionner uniquement certains sites Web sur lesquels les cookies sont activés. Mais, par exemple, si vous désactivez les cookies sur ce site Web, vous ne pourrez pas suivre les étapes suivantes pour remplir le formulaire.',
    'subtitle_6' => 'Conseils pour une navigation sûre et responsable basée sur les cookies',
    'line_3_3' => '- Cookies de session - sont des cookies temporairement stockés dans l\'historique du navigateur, où ils sont stockés jusqu\'à ce que l\'utilisateur quitte ce site Web ou ferme la fenêtre du navigateur.
- Cookies persistants - Ils sont stockés, pendant une durée prédéterminée, sur le disque dur d\'un ordinateur ou un équipement similaire. Les cookies persistants incluent ceux placés par un site Web différent de celui que l\'utilisateur est en train de visiter, appelés « cookies tiers », qui peuvent être utilisés de manière anonyme pour suivre les intérêts d\'un utilisateur, lui permettant de recevoir des publicités correspondant davantage à ses intérêts.',
    'intro_1' => 'Nous respectons votre vie privée et reconnaissons que nous devons conserver et utiliser vos informations de manière responsable.',
    'line_3_2' => 'Les cookies enregistrent des informations dans un petit fichier texte permettant à un site Web de reconnaître un navigateur. Le serveur Web reconnaîtra le navigateur jusqu\'à ce que le cookie expire ou soit supprimé. Le cookie stocke des informations importantes qui améliorent l\'expérience de navigation (par exemple, un numéro de série pour votre don). Les cookies ne demandent pas d\'informations personnelles et n\'identifient pas personnellement les internautes.',
    'line_4_4' => 'Les navigateurs modernes offrent la possibilité de modifier les paramètres des cookies. Vous pouvez généralement trouver les paramètres des cookies dans l\'onglet « options » ou dans le menu « préférences » de votre navigateur.',
    'line_4_1' => 'Les cookies sont l\'un des outils les plus importants pour une expérience Internet fluide et efficace, en aidant à générer des expériences de navigation conviviales adaptées aux besoins de chaque utilisateur. Le fait de refuser d\'accepter les cookies ou de les désactiver peut rendre l\'utilisation de certains sites Web impossible. Refuser d\'accepter les cookies ou les désactiver ne signifie pas que vous ne recevrez plus de publicités en ligne, mais uniquement que ces publicités ne tiendront plus compte de vos intérêts ou préférences tels que déterminés par votre comportement de navigation.',
    'line_3_1' => 'Un cookie (« cookie de navigateur » ou « cookie HTTP ») est un petit fichier, une succession de lettres et de chiffres, qui est stocké sur tout terminal ayant accès à Internet (ordinateurs, téléphones portables, tablettes, etc.) et qui est installé à la demande d\'un serveur à un navigateur (ex : Internet Explorer, Chrome). Les « cookies » ne contiennent aucun logiciel, virus ou logiciel espion et ne peuvent pas accéder aux informations du disque dur de l\'utilisateur. Un cookie se compose d\'un nom et d\'un contenu, sa durée d\'existence est limitée et le serveur Web peut y accéder à nouveau lorsqu\'un utilisateur revient sur le site Web associé à ce serveur.',
    'line_2_1' => 'Commit Global utilise Google Analytics pour mieux comprendre comment les visiteurs naviguent sur notre site Web afin d\'améliorer leur expérience globale. Google Analytics ne collecte aucune information identifiable sur ses visiteurs et nous ne traitons pas les données collectées via nos formulaires avec les données fournies par Google Analytics.',
    'line_5_1' => 'Dans certaines situations, comme l\'exige la loi, il peut nous être demandé de divulguer des informations personnelles collectées via ce site Web. Nous pouvons accéder à vos informations, les conserver et les divulguer sur demande afin de nous conformer aux exigences des forces de l\'ordre et aux procédures légales, telles que des ordonnances judiciaires ou une citation à comparaître, ou si cela peut protéger vos droits ou ceux d\'autrui, vos biens ou votre sécurité générale.',
    'line_1_2' => 'Lorsque vous visitez wevote4.eu, nous collectons et stockons automatiquement des données concernant votre visite en cours. Ces informations ne permettent pas de vous identifier personnellement. Les informations que nous pouvons collecter sont les suivantes : le système d\'exploitation de votre appareil, le navigateur que vous utilisez, les pages que vous avez visitées sur wevote4.eu, la source de votre visite (ex : Google, Facebook), la date et l\'heure de votre visite et le domaine depuis lequel vous accédez à Internet. Toutes ces informations sont utilisées pour améliorer encore l\'expérience de navigation sur notre site Web et pour comprendre les préférences de nos visiteurs. Nous ne collecterons aucune information personnelle via ce site Web sans votre consentement exprès.',
    'title' => 'Politique de confidentialité',
    'line_1_1' => '- Nous collectons des informations vous concernant si vous accédez à ce site Web via un navigateur classique.
- Ce site Web utilise des cookies (par exemple : Google Analytics) pour mesurer et optimiser l\'expérience de tous les utilisateurs.
- Commit Global ne divulguera ni ne vendra vos données personnelles à aucun tiers, à l\'exception des situations juridiquement contraignantes décrites dans la présente Politique de confidentialité.
- Commit Global prendra toutes les mesures raisonnables pour protéger vos informations personnelles, car il s\'agit d\'une préoccupation majeure pour nous.',
    'line_6_3' => 'Les cookies sont omniprésents et ne peuvent être évités si vous souhaitez accéder à certains des sites Web les plus importants et les meilleurs sur Internet, qu\'ils soient locaux ou internationaux. Une bonne compréhension du fonctionnement des cookies et des avantages qu\'ils apportent vous permet de prendre les mesures de sécurité nécessaires afin de toujours bénéficier d\'une expérience de navigation sûre et satisfaisante.',
    'intro_2' => 'wevote4.eu est un site web créé par Commit Global (« Commit Global », « nous », « notre ») dans le but d\'informer le public sur les élections européennes.',
    'subtitle_7' => 'Vos droits',
    'line_7_2' => '- Le droit à l\'information concernant le traitement des données personnelles par Commit Global ;
- Le droit d\'accéder aux données personnelles, sur demande et gratuitement pour une demande par an ;
- Le droit d\'intervention, de rectification, de suppression ou de portabilité des données personnelles, sur demande et gratuitement ;
- Le droit de s\'adresser à toute autorité compétente concernant les questions de confidentialité des données liées à l\'utilisation de vos données personnelles
- Le droit d\'opposition et le processus décisionnel individuel automatisé ainsi que le droit de restreindre le traitement.',
    'line_4_5' => 'Pour plus d\'informations générales sur les cookies et sur la manière de les désactiver, vous pouvez consulter le site www.aboutcookies.org.',
    'line_2_2' => 'Google Analytics placera un cookie sur votre navigateur afin de vous identifier en tant que visiteur unique et de collecter des informations sur votre navigation en conséquence. Ce cookie est utilisé exclusivement par Google, qui est à son tour empêché de partager et d\'utiliser ces données en vertu de ses propres conditions d\'utilisation de Google Analytics et de sa politique de confidentialité.',
    'intro_3' => 'Cette politique de confidentialité décrit la manière dont nous collectons, utilisons et protégeons vos informations personnelles sur ce site Web. En soumettant vos informations personnelles sur ce site Web, vous acceptez les termes de cette Politique de confidentialité. Si vous n\'êtes pas d\'accord avec ces conditions, veuillez ne pas utiliser notre site Web.',
    'line_7_4' => 'Commit Global se réserve le droit de réviser et de mettre à jour cette politique à tout moment, sans préavis ni acceptation préalable des utilisateurs. Si vous avez des questions concernant les informations contenues dans cette page, veuillez nous écrire à ',
    'subtitle_3' => 'Que sont les cookies',
    'line_7_3' => 'Cette politique constitue, dans son intégralité, un accord conclu entre vous et Commit Global concernant l\'utilisation de ce site.',
    'line_6_2' => '- Personnalisez les paramètres des cookies de votre navigateur pour garantir un niveau de sécurité confortable. Si les cookies ne vous posent aucun problème et que vous êtes la seule personne à utiliser cet appareil, vous pouvez définir de longs intervalles de conservation des cookies afin de stocker votre historique de navigation et vos données d\'accès personnelles.
- Si vous partagez l\'appareil ou l\'ordinateur, vous souhaiterez peut-être configurer le navigateur pour qu\'il supprime vos données de navigation individuelles chaque fois qu\'il est fermé. Il s\'agit d\'un moyen d\'accéder aux sites Web qui placent des cookies sur votre ordinateur partagé tout en supprimant toutes vos données de navigation à la fermeture de la session.
- installez une application anti-spyware et maintenez-la à jour. De nombreuses applications anti-spyware incluent la détection des attaques de sites Web. Ces applications empêchent le navigateur d\'accéder à des sites Web susceptibles d\'exploiter les vulnérabilités du navigateur ou de télécharger des logiciels dangereux. Assurez-vous que votre navigateur est à jour. De nombreuses attaques basées sur les cookies exploitent les points faibles des anciennes versions des navigateurs.',
    'subtitle_1' => 'Collecte de données',
    'line_4_2' => 'Le fait de refuser d\'accepter les cookies ou de les désactiver peut rendre la navigation ou l\'utilisation de certains sites Web difficiles, voire impossibles. Refuser d\'accepter les cookies ne signifie pas non plus que vous ne recevrez plus de publicités en ligne.',
];
