<?php
return [
    'line_3_1' => 'Cookie („browser cookie“ nebo „HTTP cookie“) je malý soubor, posloupnost písmen a číslic, který je uložen na jakémkoli terminálu s přístupem k internetu (počítače, mobilní telefony, tablety atd.) a je instalován na vyžádání serveru do prohlížeče (např. Internet Explorer, Chrome). „Cookies“ neobsahují žádné softwarové programy, viry ani spyware a nemohou přistupovat k informacím na pevném disku uživatele. Soubor cookie se skládá z názvu a obsahu, délka jeho existence je omezená a webový server k němu může znovu přistupovat, když se uživatel vrátí na webovou stránku spojenou s tímto serverem.',
    'line_2_1' => 'Společnost Commit Global používá Google Analytics k lepšímu pochopení toho, jak návštěvníci procházejí naše webové stránky, aby zlepšili jejich celkový zážitek. Google Analytics neshromažďuje žádné identifikovatelné informace o svých návštěvnících a nezpracováváme údaje shromážděné prostřednictvím našich formulářů spolu s údaji poskytovanými službou Google Analytics.',
    'line_5_1' => 'Mohou nastat situace, kdy, jak to vyžaduje zákon, můžeme být požádáni o zveřejnění osobních údajů shromážděných prostřednictvím těchto webových stránek. Můžeme přistupovat k vašim údajům, uchovávat a zveřejňovat je, pokud o to požádáme, abychom vyhověli požadavkům donucovacím orgánům a právním procesům, jako jsou soudní příkazy nebo pokud jsou předvolány, nebo pokud to může chránit vaše nebo jiná práva, majetek nebo obecnou bezpečnost.',
    'line_2_2' => 'Google Analytics umístí do vašeho prohlížeče soubor cookie, aby vás identifikoval jako jedinečného návštěvníka a podle toho shromažďoval informace o vaší navigaci. Tento soubor cookie používá výhradně společnost Google, která je zase omezena sdílením a používáním těchto údajů vlastními podmínkami použití Google Analytics a zásadami ochrany osobních údajů společnosti Google.',
    'intro_3' => 'Tyto zásady ochrany osobních údajů popisují, jak shromažďujeme, používáme a chráníme vaše osobní údaje na tomto webu. Odesláním vašich osobních údajů na tomto webu, souhlasíte s podmínkami v těchto zásadách ochrany osobních údajů. Pokud s těmito podmínkami nesouhlasíte, nepoužívejte prosím naše webové stránky.',
    'line_7_4' => 'Společnost Commit Global si vyhrazuje právo tyto zásady kdykoli revidovat a aktualizovat, bez předchozího upozornění nebo předchozího souhlasu uživatelů. Máte-li jakékoli dotazy týkající se informací obsažených na této stránce, napište nám na ',
    'subtitle_5' => 'Sdílení dat',
    'subtitle_3' => 'Co jsou soubory cookie',
    'line_7_3' => 'Tyto zásady představují, v plném rozsahu, dohodu uzavřenou mezi vámi a Commit Global ohledně používání tohoto webu.',
    'line_6_2' => '- Přizpůsobte si nastavení souborů cookie prohlížeče tak, aby byla zajištěna pohodlná úroveň zabezpečení. Pokud pro vás soubory cookie nejsou problémem a jste jedinou osobou, která toto zařízení používá, můžete nastavit dlouhé intervaly uchovávání souborů cookie, abyste mohli ukládat historii prohlížení a vaše osobní přístupové údaje.
- Pokud sdílíte zařízení nebo počítač, možná budete chtít nastavit prohlížeč tak, aby odstranil vaše individuální údaje o prohlížení při každém jeho zavření. Jedná se o jeden ze způsobů, jak přistupovat k webovým stránkám, které ukládají soubory cookie do vašeho sdíleného počítače a zároveň mažou všechna data procházení při ukončení relace.
- nainstalujte antispywarovou aplikaci a udržujte ji aktuální. Mnoho antispywarových aplikací zahrnuje detekci útoků na webové stránky. Tyto aplikace zabraňují prohlížeči v přístupu k webům, které by mohly zneužít zranitelnosti prohlížeče nebo stahovat nebezpečný software. Ujistěte se, že je váš prohlížeč aktuální. Mnoho útoků založených na souborech cookie využívá slabá místa starých verzí prohlížeče.',
    'subtitle_1' => 'Sběr dat',
    'line_4_2' => 'Odmítnutí přijímání souborů cookie nebo jejich deaktivace může ztěžovat nebo znemožnit navigaci nebo používání některých webových stránek. Odmítnutí přijímat soubory cookie také neznamená, že již nebudete dostávat online reklamy.',
    'line_3_2' => 'Cookies ukládají informace do malého textového souboru, který umožňuje webové stránce rozpoznat prohlížeč. Webový server rozpozná prohlížeč až do vypršení platnosti nebo smazání souboru cookie. Soubor cookie ukládá důležité informace, které zlepšují zážitek z prohlížení (např. sériové číslo vašeho daru). Soubory cookie nepožadují osobní údaje ani osobně identifikují uživatele internetu.',
    'line_4_4' => 'Moderní prohlížeče nabízejí možnost změnit nastavení souborů cookie. Nastavení souborů cookie obvykle najdete na kartě „Možnosti“ nebo v nabídce „preference“ vašeho prohlížeče.',
    'subtitle_7' => 'Vaše práva',
    'subtitle_4' => 'Jak zablokovat/odhlásit používání souborů cookie',
    'line_6_1' => 'Deaktivace souborů cookie již neumožní uživateli přístup k některým z nejdůležitějších webových stránek, jako jsou Youtube, Gmail, Yahoo a další. Zde je několik rad, které vám mohou pomoci bezpečně procházet při zachování souborů cookie:',
    'line_3_4' => 'Existují soubory cookie, které se používají výhradně pro jednu relaci - ty se již neukládají poté, co uživatel opustil webovou stránku. Trvalé soubory cookie se ukládají a znovu používají pokaždé, když se uživatel vrátí na tuto webovou stránku, ale uživatel je může kdykoli odstranit.',
    'line_7_5' => 'Tato verze smluvních podmínek wevotefor.eu je účinná od 23. května 2024. ',
    'subtitle_2' => 'Integrace třetích stran',
    'line_7_1' => 'Jako uživatel webové stránky wevote4.eu máte následující práva:',
    'line_4_3' => 'Můžete nastavit prohlížeč tak, aby automaticky odmítal soubory cookie, nebo můžete vybrat pouze některé webové stránky, kde jsou cookies povoleny. Pokud však například vypnete soubory cookie na této webové stránce, nemůžete pokračovat v dalších krocích při vyplňování formuláře.',
    'subtitle_6' => 'Rady pro bezpečné a odpovědné prohlížení souborů cookie',
    'line_3_3' => '- Session cookies - jsou soubory cookie dočasně uložené v historii prohlížeče, kde jsou uloženy, dokud uživatel neopustí webovou stránku nebo nezavře okno prohlížeče.
- Trvalé soubory cookie - ukládají se po předem stanovenou dobu na pevném disku počítače nebo podobném zařízení. Trvalé soubory cookie zahrnují soubory cookie umístěné jinou webovou stránkou, než kterou uživatel v daném okamžiku navštěvuje, tzv. „cookies třetích stran“ - které lze anonymně použít ke sledování zájmů uživatele - což mu umožňuje přijímat reklamy relevantnější pro jeho zájmy.',
    'intro_1' => 'Respektujeme vaše soukromí a uznáváme, že musíme uchovávat a používat vaše informace zodpovědně.',
    'line_1_2' => 'Při návštěvě wevote4.eu automaticky shromažďujeme a ukládáme údaje o vaší aktuální návštěvě. Tyto informace nejsou osobně identifikovatelné. Informace, které můžeme shromažďovat, jsou: operační systém ve vašem zařízení, prohlížeč, který používáte, stránky wevote4.eu, které jste navštívili, zdroj vaší návštěvy (např. Google, Facebook), datum a čas vaší návštěvy a doména, ze které přistupujete k internetu. Všechny tyto informace slouží k dalšímu zlepšení navigačního zážitku na našich webových stránkách a k pochopení preferencí našich návštěvníků. Nebudeme shromažďovat žádné osobní údaje prostřednictvím těchto webových stránek bez vašeho výslovného souhlasu.',
    'title' => 'Zásady ochrany osobních údajů',
    'line_1_1' => '- Shromažďujeme od vás informace, pokud přistupujete na tuto webovou stránku prostřednictvím běžného prohlížeče.
- Tato webová stránka využívá cookies (např. Google Analytics) k měření a optimalizaci zážitku pro všechny uživatele.
- Společnost Commit Global nebude zveřejňovat ani prodávat vaše osobní údaje žádné třetí straně, s výjimkou právně závazných situací popsaných v těchto zásadách ochrany osobních údajů.
- Společnost Commit Global přijme veškerá přiměřená opatření k ochraně vašich osobních údajů, protože to je pro nás hlavní problém.',
    'line_6_3' => 'Soubory cookie jsou všude a nelze se jim vyhnout, pokud chcete přistupovat k některým z největších a nejlepších webových stránek na internetu, ať už místní nebo mezinárodní. Jasné pochopení způsobu fungování souborů cookie a výhod, které vám přinášejí, může přijmout nezbytná bezpečnostní opatření, abyste měli vždy bezpečný a uspokojivý zážitek z prohlížení.',
    'line_4_1' => 'Soubory cookie jsou jedním z nejdůležitějších nástrojů pro bezproblémový a efektivní zážitek z internetu a pomáhají vytvářet přátelské zážitky z prohlížení přizpůsobené potřebám každého uživatele. Odmítnutí přijímání souborů cookie nebo jejich deaktivace může znemožnit používání některých webových stránek. Odmítnutí přijímání souborů cookie nebo jejich deaktivace neznamená, že již nebudete dostávat online reklamy, pouze to, že tyto reklamy již nebudou brát v úvahu vaše zájmy nebo preference, jak je určeno vaším chováním při prohlížení.',
    'intro_2' => 'wevote4.eu je webová stránka vytvořená společností Commit Global („Commit Global“, „my“, „nás“, „naše“) s cílem informovat veřejnost o volbách do Evropského parlamentu.',
    'line_7_2' => '- Právo na informace týkající se zpracování osobních údajů společností Commit Global;
- Právo na přístup k osobním údajům na vyžádání a bezplatně na jednu žádost ročně;
- právo na zásah, opravu, výmaz nebo přenositelnost osobních údajů na vyžádání a zdarma;
- Právo obrátit se na jakýkoli příslušný orgán ohledně otázek ochrany osobních údajů v souvislosti s používáním vašich osobních údajů
- Právo na námitku a automatizovaný individuální rozhodovací proces, jakož i právo na omezení zpracování.',
    'line_4_5' => 'Obecnější informace o souborech cookie a o tom, jak je deaktivovat, naleznete na adrese www.aboutcookies.org.',
];
