<?php

declare(strict_types=1);

return [
    'title' => 'Über das Projekt',
    'line_1' => 'Stellen Sie sich eine einzige, lebendige Wahlveranstaltung vor, die über 400 Millionen Bürger in der gesamten Europäischen Union vereint. Die EU-Wahlen sind nicht nur eine Reihe nationaler Abstimmungen, sondern eine kollektive Feier unserer gemeinsamen Identität und unserer demokratischen Werte. Als EU-Bürger kommen wir zusammen, um unsere gemeinsame Zukunft zu gestalten, indem wir Grenzen überschreiten und die Stärke unserer Vielfalt nutzen. Dieses Projekt ist ein Beweis für unsere Einheit und erleichtert es allen Bürgern, unabhängig davon, wo sie sich in der EU befinden, an diesem starken demokratischen Prozess teilzunehmen.',
    'line_2' => 'Um diese Vision eines einheitlichen Wahlprozesses zu unterstützen, hat Commit Global eine Plattform namens **We Vote for EU** geschaffen, die die Idee von Einheit und Zusammenarbeit verkörpert. Diese Plattform bietet allen EU-Bürgern wichtige Informationen darüber, wie sie ihre Stimme abgeben und Wahllokale schnell finden können, unabhängig von ihrem Standort.',
    'subtitle' => 'Was macht diese Plattform so besonders?',
    'line_3' => '**Entscheidungsbaum-Format:** Die Plattform verwendet ein Entscheidungsbaumformat, das EU-Bürger direkt zu den spezifischen Informationen führt, die sie benötigen.',
    'line_4' => '**Umfassende Informationen:** Die letzten bereitgestellten Informationen sind umfassend und umfassen die Registrierungsanforderungen (falls vorhanden), die verschiedenen Wahlmethoden (Vollmacht, online, per Post, Wahllokal), die für die Stimmabgabe erforderlichen Unterlagen und die Unterstützung von Wählern mit Behinderungen oder anderen Einschränkungen.',
    'line_5' => '**Geprüfte Informationen:** Die auf der Website präsentierten Informationen wurden aus verschiedenen Quellen abgeglichen, einschließlich der nationalen Ministerien und Organisationen, die für die Wahlregeln und -verfahren zuständig sind, sowie der Plattform des Europäischen Parlaments.',
    'line_6' => '**Mehrsprachige Barrierefreiheit:** Wir stellen sicher, dass jeder EU-Bürger in seiner eigenen Sprache auf die Informationen zugreifen kann, die er benötigt. Die Plattform ist in 26 Sprachen verfügbar, wobei der Entscheidungsbaum jedes Landes in seiner Amtssprache (n) und in Englisch bereitgestellt wird. Dies stellt sicher, dass jeder, unabhängig von seinem sprachlichen Hintergrund, mühelos durch den Wahlprozess navigieren kann.',
    'line_7' => '**Vernetzte Beratung:** Unabhängig von der EU-Staatsangehörigkeit des Wählers, seinem Wohnsitzland oder seinem Aufenthaltsort am Tag der Wahlen bietet die Plattform präzise, maßgeschneiderte Anweisungen und Informationen, die für seine besondere Situation relevant sind. Es ist, als hätte man einen personalisierten Wahlassistenten, der den Prozess reibungslos und inspirierend gestaltet.',
    'line_8' => 'We Vote for EU ist eine Plattform, die von **Commit Global**, der weltweit ersten globalen Civic-Tech-NGO, geschaffen und verwaltet wird. Commit Global hat seinen Hauptsitz in Den Haag (Niederlande) und konsolidiert, unterhält und bietet zivilgesellschaftlichen Organisationen und betroffenen Bevölkerungsgruppen auf der ganzen Welt kostenlosen Zugang zu wichtigen digitalen Geräten, der **Infrastructure for Good**. Weitere Informationen zu unserer Arbeit finden Sie auf [unserer Website](https://www.commitglobal.org).',
];
