<?php
return [
    'line_6_1' => 'Durch das Deaktivieren von Cookies kann der Benutzer nicht mehr auf einige der wichtigsten Websites wie Youtube, Gmail, Yahoo und andere zugreifen. Hier sind einige Ratschläge, die Ihnen helfen können, sicher zu surfen und gleichzeitig Cookies beizubehalten:',
    'line_3_4' => 'Es gibt Cookies, die ausschließlich für eine einzelne Sitzung verwendet werden — diese werden nicht mehr gespeichert, nachdem der Nutzer die Website verlassen hat. Permanente Cookies werden gespeichert und jedes Mal wiederverwendet, wenn der Benutzer zu dieser Website zurückkehrt, können jedoch jederzeit vom Benutzer gelöscht werden.',
    'subtitle_4' => 'So blockieren/deaktivieren Sie die Verwendung von Cookies',
    'line_7_5' => 'Diese Version der Allgemeinen Geschäftsbedingungen von wevotefor.eu tritt am 23. Mai 2024 in Kraft. ',
    'line_7_1' => 'Als Nutzer der Website wevote4.eu haben Sie folgende Rechte:',
    'line_4_3' => 'Sie können Ihren Browser so einrichten, dass Cookies automatisch abgelehnt werden, oder Sie können nur einige Websites auswählen, auf denen Cookies aktiviert sind. Wenn Sie jedoch beispielsweise Cookies auf dieser Website deaktivieren, können Sie die nächsten Schritte zum Ausfüllen des Formulars nicht ausführen.',
    'subtitle_6' => 'Tipps für sicheres und verantwortungsbewusstes Surfen auf Cookie-Basis',
    'intro_2' => 'wevote4.eu ist eine Website, die von Commit Global („Commit Global“, „wir“, „uns“, „unser“) erstellt wurde, um die Öffentlichkeit über die Europawahlen zu informieren.',
    'subtitle_2' => 'Integrationen von Drittanbietern',
    'intro_1' => 'Wir respektieren Ihre Privatsphäre und sind uns bewusst, dass wir Ihre Daten verantwortungsbewusst verwalten und verwenden müssen.',
    'line_3_1' => 'Ein Cookie („Browser-Cookie“ oder „HTTP-Cookie“) ist eine kleine Datei, eine Abfolge von Buchstaben und Zahlen, die auf jedem Endgerät mit Internetzugang (Computer, Mobiltelefone, Tablets usw.) gespeichert und auf Anfrage von einem Server an einen Browser (z. B. Internet Explorer, Chrome) installiert wird. „Cookies“ enthalten keine Softwareprogramme, Viren oder Spyware und können nicht auf Informationen auf der Festplatte des Benutzers zugreifen. Ein Cookie besteht aus einem Namen und einem Inhalt, die Dauer seiner Existenz ist begrenzt und der Webserver kann erneut darauf zugreifen, wenn ein Benutzer zu der mit diesem Server verknüpften Website zurückkehrt.',
    'title' => 'Datenschutzrichtlinie',
    'subtitle_3' => 'Was sind Cookies',
    'line_3_2' => 'Cookies speichern Informationen in einer kleinen Textdatei, die es einer Website ermöglicht, einen Browser zu erkennen. Der Webserver erkennt den Browser, bis das Cookie abläuft oder gelöscht wird. Das Cookie speichert wichtige Informationen, die das Surferlebnis verbessern (z. B. eine Seriennummer für Ihre Spende). Cookies fordern keine persönlichen Daten an und identifizieren Internetnutzer auch nicht persönlich.',
    'line_3_3' => '- Sitzungscookies — sind Cookies, die vorübergehend im Verlauf des Browsers gespeichert werden, wo sie gespeichert werden, bis der Benutzer diese Website verlässt oder das Browserfenster schließt.
- Dauerhafte Cookies — Diese werden für einen bestimmten Zeitraum auf einer Computerfestplatte oder einem ähnlichen Gerät gespeichert. Zu den dauerhaften Cookies gehören solche, die von einer anderen Website als der, die der Nutzer gerade besucht, platziert werden, sogenannte „Drittanbieter-Cookies“ — die anonym verwendet werden können, um die Interessen eines Nutzers zu verfolgen — und es ihm ermöglichen, Werbung zu erhalten, die seinen Interessen besser entspricht.',
    'line_2_1' => 'Commit Global verwendet Google Analytics, um besser zu verstehen, wie Besucher auf unserer Website navigieren, um ihr Gesamterlebnis zu verbessern. Google Analytics sammelt keine identifizierbaren Informationen über seine Besucher und wir verarbeiten die über unsere Formulare gesammelten Daten nicht zusammen mit den von Google Analytics bereitgestellten Daten.',
    'line_5_1' => 'Es kann Situationen geben, in denen wir, wie gesetzlich vorgeschrieben, aufgefordert werden, die über diese Website gesammelten personenbezogenen Daten offenzulegen. Wir können auf Ihre Daten zugreifen, sie speichern und weitergeben, wenn dies erforderlich ist, um den Anforderungen der Strafverfolgungsbehörden und rechtlichen Verfahren nachzukommen, wie z. B. Gerichtsbeschlüsse oder wenn dies die Rechte, das Eigentum oder die allgemeine Sicherheit von Ihnen oder anderen schützen könnte.',
    'line_1_2' => 'Wenn Sie wevote4.eu besuchen, erheben und speichern wir automatisch Daten über Ihren aktuellen Besuch. Diese Informationen sind nicht persönlich identifizierbar. Die Informationen, die wir sammeln können, sind: Betriebssystem auf Ihrem Gerät, der von Ihnen verwendete Browser, die von Ihnen besuchten Seiten auf wevote4.eu, die Quelle Ihres Besuchs (z. B. Google, Facebook), Datum und Uhrzeit Ihres Besuchs und die Domain, von der aus Sie auf das Internet zugreifen. All diese Informationen werden verwendet, um das Navigationserlebnis auf unserer Website weiter zu verbessern und die Präferenzen unserer Besucher zu verstehen. Ohne Ihre ausdrückliche Zustimmung werden wir über diese Website keine personenbezogenen Daten sammeln.',
    'line_1_1' => '- Wir sammeln Informationen von Ihnen, wenn Sie über einen normalen Browser auf diese Website zugreifen.
- Diese Website verwendet Cookies (z. B. Google Analytics), um das Erlebnis für alle Nutzer zu messen und zu optimieren.
- Commit Global wird Ihre personenbezogenen Daten nicht an Dritte weitergeben oder verkaufen, mit Ausnahme der in dieser Datenschutzrichtlinie beschriebenen rechtsverbindlichen Situationen.
- Commit Global wird alle angemessenen Maßnahmen ergreifen, um Ihre personenbezogenen Daten zu schützen, da dies für uns ein wichtiges Anliegen ist.',
    'line_6_3' => 'Cookies sind überall und können nicht vermieden werden, wenn Sie auf einige der größten und besten lokalen oder internationalen Websites im Internet zugreifen möchten. Wenn Sie genau wissen, wie Cookies funktionieren und welche Vorteile sie bieten, können Sie die erforderlichen Sicherheitsmaßnahmen ergreifen, damit Sie immer ein sicheres und zufriedenstellendes Surferlebnis haben.',
    'line_4_1' => 'Cookies sind eines der wichtigsten Tools für ein reibungsloses, effizientes Interneterlebnis und tragen dazu bei, ein benutzerfreundliches Surferlebnis zu bieten, das auf die Bedürfnisse jedes Benutzers zugeschnitten ist. Die Weigerung, Cookies zu akzeptieren oder sie zu deaktivieren, kann dazu führen, dass einige Websites nicht genutzt werden können. Die Ablehnung oder Deaktivierung von Cookies bedeutet nicht, dass Sie keine Online-Werbung mehr erhalten, sondern nur, dass diese Anzeigen Ihre Interessen oder Präferenzen, die durch Ihr Surfverhalten bestimmt werden, nicht mehr berücksichtigen.',
    'line_7_2' => '- Das Recht auf Information über die Verarbeitung personenbezogener Daten durch Commit Global;
- Das Recht, auf Anfrage und kostenlos für eine Anfrage pro Jahr auf personenbezogene Daten zuzugreifen;
- Das Recht auf unentgeltliche Intervention, Berichtigung, Löschung oder Übertragbarkeit personenbezogener Daten;
- Das Recht, sich in Datenschutzfragen im Zusammenhang mit der Verwendung Ihrer personenbezogenen Daten an jede zuständige Behörde zu wenden
- Das Widerspruchsrecht und die automatisierte individuelle Entscheidungsfindung sowie das Recht, die Verarbeitung einzuschränken.',
    'line_4_5' => 'Weitere allgemeine Informationen zu Cookies und deren Deaktivierung finden Sie auf www.aboutcookies.org.',
    'line_2_2' => 'Google Analytics platziert ein Cookie in Ihrem Browser, um Sie als eindeutigen Besucher zu identifizieren und Informationen über Ihre Navigation entsprechend zu sammeln. Dieses Cookie wird ausschließlich von Google verwendet, das wiederum durch seine eigenen Nutzungsbedingungen von Google Analytics und die Google-Datenschutzrichtlinie daran gehindert ist, diese Daten weiterzugeben und zu verwenden.',
    'intro_3' => 'Diese Datenschutzrichtlinie beschreibt, wie wir Ihre personenbezogenen Daten auf dieser Website sammeln, verwenden und schützen. Durch die Übermittlung Ihrer persönlichen Daten auf dieser Website stimmen Sie den Bedingungen dieser Datenschutzrichtlinie zu. Wenn Sie mit diesen Bedingungen nicht einverstanden sind, nutzen Sie unsere Website bitte nicht.',
    'line_7_4' => 'Commit Global behält sich das Recht vor, diese Richtlinie jederzeit ohne vorherige Ankündigung oder vorherige Zustimmung der Nutzer zu überarbeiten und zu aktualisieren. Wenn Sie Fragen zu den auf dieser Seite enthaltenen Informationen haben, schreiben Sie uns bitte an ',
    'subtitle_5' => 'Teilen von Daten',
    'line_7_3' => 'Diese Richtlinie stellt in ihrer Gesamtheit eine zwischen Ihnen und Commit Global geschlossene Vereinbarung über die Nutzung dieser Website dar.',
    'line_6_2' => '- Passen Sie die Cookie-Einstellungen Ihres Browsers an, um ein komfortables Sicherheitsniveau zu gewährleisten. Wenn Cookies für Sie kein Problem darstellen und Sie die einzige Person sind, die dieses Gerät verwendet, können Sie lange Aufbewahrungsintervalle für Cookies festlegen, um Ihren Browserverlauf und Ihre persönlichen Zugangsdaten zu speichern.
- Wenn Sie das Gerät oder den Computer gemeinsam nutzen, möchten Sie den Browser möglicherweise so einrichten, dass Ihre individuellen Browserdaten bei jedem Schließen gelöscht werden. Dies ist eine Möglichkeit, auf Websites zuzugreifen, die Cookies auf Ihrem gemeinsam genutzten Computer platzieren, und gleichzeitig alle Ihre Browserdaten zu löschen, wenn Sie die Sitzung schließen.
- Installieren Sie eine Anti-Spyware-App und halten Sie sie auf dem neuesten Stand. Viele Anti-Spyware-Apps beinhalten die Erkennung von Website-Angriffen. Diese Apps verhindern, dass der Browser auf Websites zugreift, die die Sicherheitslücken des Browsers ausnutzen oder gefährliche Software herunterladen könnten. Stellen Sie sicher, dass Ihr Browser auf dem neuesten Stand ist. Viele auf Cookies basierende Angriffe nutzen die Schwachstellen alter Browserversionen aus.',
    'subtitle_1' => 'Erfassung von Daten',
    'line_4_2' => 'Die Ablehnung oder Deaktivierung von Cookies kann die Navigation oder Nutzung einiger Websites erschweren oder unmöglich machen. Die Ablehnung von Cookies bedeutet auch nicht, dass Sie keine Online-Werbung mehr erhalten.',
    'line_4_4' => 'Moderne Browser bieten die Möglichkeit, die Cookie-Einstellungen zu ändern. In der Regel finden Sie die Cookie-Einstellungen auf der Registerkarte „Optionen“ oder im Menü „Einstellungen“ Ihres Browsers.',
    'subtitle_7' => 'Deine Rechte',
];
