<?php
return [
    'title' => 'Om projektet',
    'line_1' => 'Forestil dig en enkelt, levende valgbegivenhed, der forener over 400 millioner borgere i hele EU. EU-valg er ikke blot en række nationale afstemninger, men en kollektiv fejring af vores fælles identitet og demokratiske værdier. Som EU-borgere mødes vi for at forme vores fælles fremtid, overskride grænser og omfavne styrken i vores mangfoldighed. Dette projekt er et vidnesbyrd om vores enhed og gør det lettere for enhver borger, uanset hvor i EU de befinder sig, at deltage i denne magtfulde demokratiske proces.',
    'line_2' => 'For at understøtte denne vision om en samlet valgproces har Commit Global skabt en platform, **We Vote for EU**, som legemliggør ideen om enhed og samarbejde. Denne platform giver alle EU-borgere vigtige oplysninger om, hvordan de hurtigt kan afgive deres stemme og finde valgsteder, uanset hvor de befinder sig.',
    'subtitle' => 'Hvad gør denne platform speciel?',
    'line_3' => '**Beslutningstræformat: ** Platformen bruger et beslutningstræformat, der guider EU-borgere direkte til de specifikke oplysninger, de har brug for.',
    'line_4' => '**Omfattende information: ** De endelige oplysninger, der leveres, er omfattende og dækker registreringskrav (hvis nogen), forskellige afstemningsmetoder (fuldmagt, online, post, valgsted), påkrævet dokumentation til afstemning og hjælp til vælgere med handicap eller andre begrænsninger.',
    'line_5' => '**Bekræftede oplysninger: ** Oplysningerne på webstedet krydstjekkes fra flere forskellige kilder, herunder nationale ministerier og organisationer, der er ansvarlige for afstemningsregler og -procedurer, samt Europa-Parlamentets platform.',
    'line_6' => '**Flersproget tilgængelighed: ** Vi sørger for, at alle EU-borgere kan få adgang til de oplysninger, de har brug for, på deres eget sprog. Platformen er tilgængelig på 26 sprog, hvor hvert lands beslutningstræ leveres på dets officielle sprog og på engelsk. Dette sikrer, at alle, uanset deres sproglige baggrund, kan navigere i afstemningsprocessen ubesværet.',
    'line_7' => '**Sammenkoblet vejledning: ** Uanset vælgerens EU-nationalitet, bopælsland eller placering på valgdagen giver platformen præcise, skræddersyede instruktioner og oplysninger, der er relevante for vedkommendes unikke situation. Det er som at have en personlig stemmeassistent, der gør processen glat og inspirerende.',
    'line_8' => 'We Vote for EU er en platform oprettet og administreret af**Commit Global**, verdens første globale civilteknologiske NGO. Med hovedsæde i Haag (Holland) konsoliderer, vedligeholder og giver Commit Global fri adgang til kritisk digital, **Infrastructure for Good**, til civilsamfundsorganisationer og berørte befolkninger rundt om i verden. For yderligere information om vores arbejde, besøg venligst [vores hjemmeside] (https://www.commitglobal.org).',
];
