<?php
return [
    'line_3_2' => 'Cookies gemmer oplysninger i en lille tekstfil, så et websted kan genkende en browser. Webserveren genkender browseren indtil cookien udløber eller slettes. Cookien gemmer vigtige oplysninger, der forbedrer browseroplevelsen (f.eks. et serienummer til din donation). Cookies anmoder ikke om personlige oplysninger, og de identificerer heller ikke internetbrugere personligt.',
    'line_4_4' => 'Moderne browsere giver mulighed for at ændre cookieindstillinger. Du kan normalt finde cookieindstillinger under fanen „indstillinger“ eller menuen „præferencer“ i din browser.',
    'line_6_1' => 'Deaktivering af cookies vil ikke længere give brugeren adgang til nogle af de vigtigste websteder som Youtube, Gmail, Yahoo og andre. Her er nogle råd, der kan hjælpe dig med at surfe sikkert, mens du gemmer cookies:',
    'line_3_4' => 'Der er cookies, der udelukkende bruges til en enkelt session - disse gemmes ikke længere, efter at brugeren har forladt hjemmesiden. Permanente cookies gemmes og genbruges hver gang brugeren vender tilbage til det pågældende websted, men kan til enhver tid slettes af brugeren.',
    'line_7_1' => 'Som bruger af websitet wevote4.eu har du følgende rettigheder:',
    'line_4_3' => 'Du kan indstille din browser til automatisk at afvise cookies, eller du kan kun vælge nogle websteder, hvor cookies er aktiveret. Men for eksempel, hvis du slår cookies fra på dette websted, kan du ikke følge op med de næste trin i udfyldelsen af formularen.',
    'subtitle_6' => 'Råd til sikker og ansvarlig cookie-baseret browsing',
    'line_3_3' => '- Session cookies - er cookies, der midlertidigt gemmes i browserens historik, hvor de gemmes, indtil brugeren forlader hjemmesiden eller lukker browservinduet.
- Vedvarende cookies - Disse gemmes i et forudbestemt tidsrum på en computerharddisk eller lignende udstyr. Vedvarende cookies omfatter dem, der placeres af et andet websted end det, som brugeren besøger på det tidspunkt, såkaldte „tredjepartscookies“ - som anonymt kan bruges til at spore en brugers interesser - så de kan modtage annoncer, der er mere relevante for deres interesser.',
    'line_3_1' => 'En cookie („browsercookie“ eller „HTTP-cookie“) er en lille fil, en række bogstaver og tal, der gemmes på enhver terminal med internetadgang (computere, mobiltelefoner, tablets osv.) og installeres efter anmodning fra en server til en browser (f.eks. Internet Explorer, Chrome). „Cookies“ indeholder ingen softwareprogrammer, vira eller spyware og kan ikke få adgang til oplysninger på brugerens harddisk. En cookie består af et navn og indhold, varigheden af dens eksistens er begrænset, og den kan tilgås igen af webserveren, når en bruger vender tilbage til det websted, der er tilknyttet den pågældende server.',
    'line_2_1' => 'Commit Global bruger Google Analytics til bedre at forstå, hvordan besøgende navigerer på vores websted for at forbedre deres samlede oplevelse. Google Analytics indsamler ingen identificerbare oplysninger om sine besøgende, og vi behandler ikke de data, der indsamles via vores formularer sammen med de data, der leveres af Google Analytics.',
    'line_5_1' => 'Der kan være situationer, hvor vi, som krævet ved lov, kan blive bedt om at videregive personlige oplysninger indsamlet via dette websted. Vi kan få adgang til, bevare og videregive dine oplysninger, hvis det anmodes om det for at overholde retshåndhævelseskrav og juridiske processer, såsom retskendelser eller hvis de stævnes, eller hvis dette kan beskytte dig eller andres rettigheder, ejendom eller generelle sikkerhed.',
    'subtitle_2' => 'Tredjepartsintegrationer',
    'intro_1' => 'Vi respekterer dit privatliv og anerkender, at vi skal vedligeholde og bruge dine oplysninger ansvarligt.',
    'line_1_2' => 'Når du besøger wevote4.eu, indsamler og gemmer vi automatisk data om dit aktuelle besøg. Disse oplysninger er ikke personligt identificerbare. De oplysninger, vi kan indsamle, er: operativsystem på din enhed, den browser, du bruger, sider i wevote4.eu, du har besøgt, kilden til dit besøg (f.eks. Google, Facebook), dato og klokkeslæt for dit besøg og det domæne, hvorfra du får adgang til internettet. Alle disse oplysninger bruges til yderligere at forbedre navigationsoplevelsen på vores hjemmeside og til at forstå vores besøgendes præferencer. Vi indsamler ikke personlige oplysninger via dette websted uden dit udtrykkelige samtykke.',
    'title' => 'Privatlivspolitik',
    'line_1_1' => '- Vi indsamler oplysninger fra dig, hvis du får adgang til dette websted via en almindelig browser.
- Denne hjemmeside gør brug af cookies (f.eks. Google Analytics) til at måle og optimere oplevelsen for alle brugere.
- Commit Global vil ikke videregive eller sælge dine personlige data til nogen tredjepart, undtagen de juridisk bindende situationer, der er beskrevet i denne fortrolighedspolitik.
- Commit Global vil træffe alle rimelige foranstaltninger for at beskytte dine personlige oplysninger, da dette er en stor bekymring for os.',
    'intro_2' => 'wevote4.eu er et websted oprettet af Commit Global („Commit Global“, „vi“, „os“, „vores“) med det formål at informere offentligheden om valget til Europa-Parlamentet.',
    'intro_3' => 'Denne fortrolighedspolitik beskriver, hvordan vi indsamler, bruger og beskytter dine personlige oplysninger på dette websted. Ved at indsende dine personlige oplysninger på dette websted accepterer du betingelserne i denne fortrolighedspolitik. Hvis du ikke er enig i disse vilkår, skal du ikke bruge vores hjemmeside.',
    'subtitle_1' => 'Dataindsamling',
    'subtitle_4' => 'Sådan blokerer/fravælger du brugen af cookies',
    'line_7_5' => 'Denne version af wevotefor.eu vilkår og betingelser træder i kraft den 23. maj 2024. ',
    'subtitle_7' => 'Dine rettigheder',
    'line_6_3' => 'Cookies er overalt og kan ikke undgås, hvis du ønsker at få adgang til nogle af de største og bedste websteder på internettet, enten lokale eller internationale. Den klare forståelse af, hvordan cookies fungerer, og de fordele, de giver dig, kan tage de nødvendige sikkerhedsforanstaltninger, så du altid har en sikker og tilfredsstillende browseroplevelse.',
    'line_4_1' => 'Cookies er et af de vigtigste værktøjer til en problemfri, effektiv internetoplevelse, der hjælper med at generere venlige browseroplevelser, der er skræddersyet til hver brugers behov. At nægte at acceptere cookies eller deaktivere dem kan gøre nogle websteder umulige at bruge. At nægte at acceptere cookies eller deaktivere dem betyder ikke, at du ikke længere vil modtage onlineannoncer, kun at disse annoncer ikke længere tager hensyn til dine interesser eller præferencer som bestemt af din browseradfærd.',
    'line_7_2' => '- Retten til information om Commit Globals behandling af personoplysninger;
- Retten til at få adgang til personoplysninger efter anmodning og gratis for en anmodning om året;
- Retten til indgriben, berigtigelse, sletning eller overførsel af personoplysninger, efter anmodning og gratis;
- Retten til at henvende sig til enhver kompetent myndighed vedrørende databeskyttelsesspørgsmål i forbindelse med brugen af dine personoplysninger
- Retten til indsigelse og den automatiserede individuelle beslutningsproces samt retten til at begrænse behandlingen.',
    'line_4_5' => 'For mere generel information om cookies og hvordan du deaktiverer dem, kan du besøge www.aboutcookies.org.',
    'line_2_2' => 'Google Analytics placerer en cookie i din browser, så den kan identificere dig som en unik besøgende og indsamle oplysninger om din navigation i overensstemmelse hermed. Denne cookie bruges udelukkende af Google, som igen er begrænset til at dele og bruge disse data i henhold til sine egne Google Analytics-brugsbetingelser og Googles privatlivspolitik.',
    'line_7_4' => 'Commit Global forbeholder sig retten til at revidere og opdatere denne politik til enhver tid, uden varsel eller forudgående accept fra brugerne. Hvis du har spørgsmål vedrørende oplysningerne på denne side, bedes du skrive til os på ',
    'subtitle_5' => 'Datadeling',
    'subtitle_3' => 'Hvad er cookies',
    'line_7_3' => 'Denne politik udgør i sin helhed en aftale indgået mellem dig og Commit Global vedrørende brugen af dette websted.',
    'line_6_2' => '- Tilpas dine browser-cookieindstillinger for at give mulighed for et behageligt sikkerhedsniveau. Hvis cookies ikke er et problem for dig, og du er den eneste person, der bruger denne enhed, kan du indstille lange cookie-opbevaringsintervaller for at gemme din browserhistorik og dine personlige adgangsdata.
- Hvis du deler enheden eller computeren, kan det være en god idé at indstille browseren til at slette dine individuelle browserdata, hver gang den lukkes. Dette er en måde at få adgang til websteder, der placerer cookies på din delte computer, mens du sletter alle dine browserdata, når du lukker sessionen.
- Installer en anti-spyware app og hold den opdateret. Mange anti-spyware-apps inkluderer detektion af webstedsangreb. Disse apps forhindrer browseren i at få adgang til websteder, der kan udnytte browserens sårbarheder eller downloade farlig software. Sørg for, at din browser er opdateret. Mange cookie-baserede angreb udnytter de svage punkter i gamle browserversioner.',
    'line_4_2' => 'At nægte at acceptere cookies eller deaktivere dem kan gøre nogle websteder vanskelige eller umulige at navigere eller bruge. At nægte at acceptere cookies betyder heller ikke, at du ikke længere vil modtage onlineannoncer.',
];
