<?php
return [
    'subtitle_2' => 'Integrácie tretích strán',
    'intro_1' => 'Rešpektujeme vaše súkromie a uznávame, že vaše informácie musíme udržiavať a používať zodpovedne.',
    'line_3_1' => 'Súbor cookie („cookie prehliadača“ alebo „súbor cookie HTTP“) je malý súbor, séria písmen a číslic, ktorý sa ukladá na akomkoľvek termináli s prístupom na internet (počítače, mobilné telefóny, tablety atď.) a je nainštalovaný na požiadanie servera do prehliadača (napr. Internet Explorer, Chrome). „Cookies“ neobsahujú žiadne softvérové programy, vírusy ani spyware a nemajú prístup k informáciám na pevnom disku používateľa. Súbor cookie pozostáva z názvu a obsahu, dĺžka jeho existencie je obmedzená a webový server k nemu môže znova pristupovať, keď sa používateľ vráti na webovú stránku spojenú s týmto serverom.',
    'title' => 'Zásady ochrany osobných údajov',
    'subtitle_3' => 'Čo sú súbory cookie',
    'subtitle_4' => 'Ako zablokovať/odhlásiť používanie súborov cookie',
    'subtitle_5' => 'Zdieľanie údajov',
    'line_7_5' => 'Táto verzia obchodných podmienok wevotefor.eu nadobúda účinnosť 23. mája 2024. ',
    'line_6_3' => 'Súbory cookie sú všade a nemožno sa im vyhnúť, ak chcete získať prístup k niektorým z najväčších a najlepších webových stránok na internete, či už miestnych alebo medzinárodných. Jasné pochopenie spôsobu fungovania súborov cookie a výhod, ktoré vám prinášajú, môžete prijať potrebné bezpečnostné opatrenia, aby ste mali vždy bezpečný a uspokojivý zážitok z prehliadania.',
    'line_7_4' => 'Commit Global si vyhradzuje právo kedykoľvek revidovať a aktualizovať tieto zásady bez predchádzajúceho upozornenia alebo predchádzajúceho súhlasu používateľov. Ak máte akékoľvek otázky týkajúce sa informácií obsiahnutých na tejto stránke, napíšte nám na ',
    'line_7_3' => 'Tieto zásady predstavujú v celom rozsahu dohodu uzatvorenú medzi vami a Commit Global týkajúcou sa používania tejto stránky.',
    'subtitle_7' => 'Vaše práva',
    'line_6_1' => 'Deaktivácia súborov cookie už neumožňuje používateľom prístup k niektorým z najdôležitejších webových stránok, ako sú Youtube, Gmail, Yahoo a ďalšie. Tu je niekoľko rád, ktoré vám môžu pomôcť bezpečne prehliadať pri zachovaní súborov cookie:',
    'line_3_4' => 'Existujú súbory cookie, ktoré sa používajú výhradne na jednu reláciu - tieto sa už neukladajú po opustení webovej stránky. Trvalé súbory cookie sa ukladajú a opätovne používajú vždy, keď sa používateľ vráti na danú webovú stránku, ale používateľ ich môže kedykoľvek odstrániť.',
    'line_4_3' => 'Môžete nastaviť svoj prehliadač tak, aby automaticky odmietol súbory cookie alebo môžete vybrať len niektoré webové stránky, kde sú povolené súbory cookie. Ak však napríklad vypnete súbory cookie na tejto webovej stránke, nemôžete nasledovať ďalšie kroky pri vyplnení formulára.',
    'subtitle_6' => 'Poradenstvo pre bezpečné a zodpovedné prehliadanie súborov cookie',
    'line_3_3' => '- Session cookies - sú cookies dočasne uložené v histórii prehliadača, kde sú uložené, kým používateľ neopustí túto webovú stránku alebo nezatvorí okno prehliadača.
- Trvalé súbory cookie - ukladajú sa na vopred určenú dobu na pevnom disku počítača alebo podobnom zariadení. Trvalé súbory cookie zahŕňajú súbory cookie umiestnené inou webovou stránkou, ako je tá, ktorú používateľ v tom čase navštevuje, tzv. „súbory cookie tretích strán“ - ktoré možno anonymne použiť na sledovanie záujmov používateľa - umožňujú mu prijímať reklamy, ktoré sú relevantnejšie pre jeho záujmy.',
    'line_2_1' => 'Spoločnosť Commit Global využíva službu Google Analytics na lepšie pochopenie toho, ako návštevníci navigujú na našich webových stránkach, aby zlepšili svoj celkový zážitok. Google Analytics nezhromažďuje žiadne identifikovateľné informácie o svojich návštevníkoch a nespracúvame údaje zhromaždené prostredníctvom našich formulárov spolu s údajmi poskytnutými spoločnosťou Google Analytics.',
    'line_5_1' => 'Môžu sa vyskytnúť situácie, keď nás v súlade so zákonom vyžaduje, aby sme zverejnili osobné údaje zhromaždené prostredníctvom tejto webovej stránky. Môžeme pristupovať k vašim informáciám, uchovávať a zverejňovať, ak sú o to požiadané, aby sme splnili požiadavky presadzovania práva a právne postupy, ako sú súdne príkazy alebo ak sú predvolané, alebo ak to môže chrániť vaše práva, majetok alebo všeobecnú bezpečnosť iných osôb.',
    'line_1_2' => 'Po návšteve wevote4.eu budeme automaticky zhromažďovať a ukladať údaje o vašej aktuálnej návšteve. Tieto informácie nie sú osobne identifikovateľné. Informácie, ktoré môžeme zhromažďovať, sú: operačný systém vo vašom zariadení, prehliadač, ktorý používate, stránky na wevote4.eu, ktoré ste navštívili, zdroj vašej návštevy (napr. Google, Facebook), dátum a čas vašej návštevy a doména, z ktorej pristupujete na internet. Všetky tieto informácie sa používajú na ďalšie zlepšenie navigácie na našich webových stránkach a na pochopenie preferencií našich návštevníkov. Prostredníctvom tejto webovej stránky nebudeme zhromažďovať žiadne osobné údaje bez vášho výslovného súhlasu.',
    'line_1_1' => '- Zhromažďujeme informácie od vás, ak vstupujete na túto webovú stránku prostredníctvom bežného prehliadača.
- Táto webová stránka používa súbory cookie (napr. Google Analytics) na meranie a optimalizáciu zážitku pre všetkých používateľov.
- Commit Global nebude zverejňovať ani predávať vaše osobné údaje žiadnej tretej strane, s výnimkou právne záväzných situácií opísaných v týchto Zásadách ochrany osobných údajov.
- Commit Global prijme všetky primerané opatrenia na ochranu vašich osobných údajov, pretože je to pre nás veľký problém.',
    'line_4_1' => 'Súbory cookie sú jedným z najdôležitejších nástrojov pre bezproblémový a efektívny zážitok z internetu a pomáhajú vytvárať priateľské zážitky z prehliadania prispôsobené potrebám každého používateľa. Odmietnutie prijímania súborov cookie alebo ich deaktivácia môže spôsobiť znemožnenie používania niektorých webových stránok. Odmietnutie prijímania súborov cookie alebo ich deaktivácia neznamená, že už nebudete dostávať online reklamy, len že tieto reklamy už nebudú brať do úvahy vaše záujmy alebo preferencie podľa vášho správania pri prehliadaní.',
    'intro_2' => 'wevote4.eu je webová stránka vytvorená spoločnosťou Commit Global („Commit Global“, „my“, „nás“, „naše“) s cieľom informovať verejnosť o európskych voľbách.',
    'line_4_5' => 'Všeobecnejšie informácie o súboroch cookie a spôsobe ich deaktivácie nájdete na stránke www.aboutcookies.org.',
    'line_2_2' => 'Google Analytics umiestni súbor cookie do vášho prehliadača, aby vás identifikoval ako jedinečného návštevníka a podľa toho zhromažďoval informácie o vašej navigácii. Tento súbor cookie používa výhradne spoločnosť Google, ktorá je zase zakázaná zdieľanie a používanie týchto údajov vlastnými podmienkami používania služby Google Analytics a Zásadami ochrany osobných údajov spoločnosti Google.',
    'intro_3' => 'Tieto zásady ochrany osobných údajov popisujú, ako zhromažďujeme, používame a chránime vaše osobné údaje na tejto webovej stránke. Odoslaním vašich osobných údajov na tejto webovej stránke súhlasíte s podmienkami v týchto Zásadách ochrany osobných údajov. Ak nesúhlasíte s týmito podmienkami, nepoužívajte našu webovú stránku.',
    'line_6_2' => '- Prispôsobte nastavenia súborov cookie prehliadača tak, aby ste umožnili pohodlnú úroveň zabezpečenia. Ak pre vás súbory cookie nie sú problémom a ste jedinou osobou, ktorá používa toto zariadenie, môžete nastaviť dlhé intervaly uchovávania súborov cookie, aby ste uložili históriu prehliadania a vaše osobné prístupové údaje.
- Ak zdieľate zariadenie alebo počítač, možno budete chcieť nastaviť prehliadač tak, aby odstránil vaše jednotlivé údaje prehliadania pri každom zatvorení. Toto je jeden zo spôsobov prístupu k webovým stránkam, ktoré umiestňujú súbory cookie do vášho zdieľaného počítača a zároveň vymažú všetky údaje o prehliadaní pri zatváraní relácie.
- nainštalujte aplikáciu proti spywaru a udržiavajte ju aktuálnu. Mnoho antispywarových aplikácií zahŕňa detekciu útokov na webových stránkach. Tieto aplikácie bránia prehliadaču prístup k webovým stránkam, ktoré môžu využívať zraniteľné miesta prehliadača alebo sťahovať nebezpečný softvér. Uistite sa, že váš prehliadač je aktuálny. Mnoho útokov založených na súboroch cookie využíva slabé stránky starých verzií prehliadača.',
    'subtitle_1' => 'Zhromažďovanie údajov',
    'line_4_2' => 'Odmietnutie prijímania súborov cookie alebo ich deaktivácia môže sťažiť alebo znemožniť navigáciu alebo používanie niektorých webových stránok. Odmietnutie prijímania súborov cookie tiež neznamená, že už nebudete dostávať online reklamy.',
    'line_3_2' => 'Súbory cookie ukladajú informácie do malého textového súboru, ktorý umožňuje webovej stránke rozpoznať prehliadač. Webový server rozpozná prehliadač až do vypršania platnosti alebo odstránenia súboru cookie. Súbor cookie ukladá dôležité informácie, ktoré zlepšujú zážitok z prehliadania (napr. sériové číslo pre váš dar). Cookies nevyžadujú osobné informácie ani osobne neidentifikujú používateľov internetu.',
    'line_4_4' => 'Moderné prehliadače ponúkajú možnosť zmeniť nastavenia súborov cookie. Nastavenia súborov cookie môžete zvyčajne nájsť na karte „Možnosti“ alebo v ponuke „preferencie“ vášho prehliadača.',
    'line_7_1' => 'Ako používateľ webovej stránky wevote4.eu máte nasledujúce práva:',
    'line_7_2' => '- právo na informácie týkajúce sa spracovania osobných údajov spoločnosťou Commit Global;
- právo na prístup k osobným údajom na požiadanie a bezplatne na jednu žiadosť ročne;
- právo na zásah, opravu, vymazanie alebo prenosnosť osobných údajov na požiadanie a bezplatne;
- Právo obrátiť sa na akýkoľvek príslušný orgán v súvislosti s otázkami ochrany osobných údajov v súvislosti s používaním vašich osobných údajov
- právo na námietku a automatizovaný individuálny rozhodovací proces, ako aj právo obmedziť spracúvanie.',
];
