<?php
return [
    'title' => 'Politika zasebnosti',
    'intro_1' => 'Spoštujemo vašo zasebnost in priznavamo, da moramo vaše podatke vzdrževati in uporabljati odgovorno.',
    'intro_2' => 'wevote4.eu je spletna stran, ki jo je ustvaril Commit Global (»Commit Global«, »mi«, »nas«, »naš«) z namenom obveščanja javnosti o evropskih volitvah.',
    'intro_3' => 'Ta pravilnik o zasebnosti opisuje, kako zbiramo, uporabljamo in varujemo vaše osebne podatke na tem spletnem mestu. S pošiljanjem vaših osebnih podatkov na tej spletni strani se strinjate s pogoji v tej politiki zasebnosti. Če se s temi pogoji ne strinjate, prosimo, ne uporabljajte naše spletne strani.',
    'subtitle_1' => 'Zbiranje podatkov',
    'line_1_1' => '- Podatke zbiramo od vas, če dostopate do tega spletnega mesta prek običajnega brskalnika.
- Ta spletna stran uporablja piškotke (npr. Google Analytics) za merjenje in optimizacijo izkušnje za vse uporabnike.
- Commit Global ne bo razkril ali prodal vaših osebnih podatkov nobeni tretji osebi, razen pravno zavezujočih situacij, opisanih v tem pravilniku o zasebnosti.
- Commit Global bo sprejel vse razumne ukrepe za zaščito vaših osebnih podatkov, saj je to za nas velika skrb.',
    'line_1_2' => 'Ob obisku wevote4.eu bomo samodejno zbirali in shranili podatke o vašem trenutnem obisku. Te informacije niso osebno prepoznavne. Podatki, ki jih lahko zbiramo, so: operacijski sistem v vaši napravi, brskalnik, ki ga uporabljate, strani na wevote4.eu, ki ste jih obiskali, vir vašega obiska (npr. Google, Facebook), datum in čas vašega obiska ter domena, s katere dostopate do interneta. Vse te informacije uporabljamo za nadaljnje izboljšanje navigacijske izkušnje na naši spletni strani in za razumevanje želja naših obiskovalcev. Preko tega spletnega mesta ne bomo zbirali nobenih osebnih podatkov brez vašega izrecnega soglasja.',
    'subtitle_2' => 'Integracije tretjih oseb',
    'line_2_1' => 'Commit Global uporablja Google Analytics, da bolje razume, kako obiskovalci krmarajo po našem spletnem mestu, da bi izboljšali svojo splošno izkušnjo. Google Analytics ne zbira nobenih identifikacijskih podatkov o svojih obiskovalcih in podatkov, zbranih prek naših obrazcev, ne obdelujemo skupaj s podatki, ki jih posreduje Google Analytics.',
    'line_2_2' => 'Google Analytics bo v vaš brskalnik namestil piškotek, da vas lahko identificira kot edinstvenega obiskovalca in ustrezno zbira podatke o vaši navigaciji. Ta piškotek uporablja izključno Google, ki je s tem omejen deljenje in uporabo teh podatkov s svojimi pogoji uporabe storitve Google Analytics in Googlovim pravilnikom o zasebnosti.',
    'subtitle_3' => 'Kaj so piškotki',
    'line_3_1' => 'Piškotek (»piškotek brskalnika« ali »piškotek HTTP«) je majhna datoteka, zaporedje črk in številk, ki se shrani na katerem koli terminalu z dostopom do interneta (računalniki, mobilni telefoni, tablični računalniki itd.) in se namesti na zahtevo strežnika v brskalnik (npr. Internet Explorer, Chrome). »Piškotki« ne vsebujejo nobene programske opreme, virusov ali vohunske programske opreme in ne morejo dostopati do informacij na uporabnikovem trdem disku. Piškotek je sestavljen iz imena in vsebine, dolžina njegovega obstoja je omejena in do njega lahko spletni strežnik ponovno dostopa, ko se uporabnik vrne na spletno mesto, povezano s tem strežnikom.',
    'line_3_2' => 'Piškotki shranjujejo podatke v majhno besedilno datoteko, ki omogoča spletnemu mestu, da prepozna brskalnik. Spletni strežnik bo brskalnik prepoznal, dokler piškotek ne poteče ali se izbriše. Piškotek shranjuje pomembne informacije, ki izboljšujejo izkušnjo brskanja (npr. serijsko številko za vašo donacijo). Piškotki ne zahtevajo osebnih podatkov niti osebno ne identificirajo uporabnikov interneta.',
    'line_3_3' => '- Sejni piškotki - so piškotki, ki so začasno shranjeni v zgodovini brskalnika, kjer so shranjeni, dokler uporabnik ne zapusti te spletne strani ali ne zapre okna brskalnika.
- Trajni piškotki - Ti se za vnaprej določen čas shranjujejo na računalniškem trdem disku ali podobni opremi. Trajni piškotki vključujejo tiste, ki jih namesti druga spletna stran od tiste, ki jo uporabnik takrat obišče, tako imenovane« piškotke tretjih oseb », ki jih je mogoče anonimno uporabiti za sledenje uporabnikovim interesom - ki jim omogočajo prejemanje oglasov, ki ustrezajo njihovim interesom.',
    'line_3_4' => 'Obstajajo piškotki, ki se uporabljajo izključno za eno samo sejo - ti se ne shranjujejo več, ko uporabnik zapusti spletno stran. Trajni piškotki se shranijo in ponovno uporabijo vsakič, ko se uporabnik vrne na to spletno mesto, vendar jih lahko uporabnik kadar koli izbriše.',
    'subtitle_4' => 'Kako blokirati/onemogočiti uporabo piškotkov',
    'line_4_1' => 'Piškotki so eno najpomembnejših orodij za brezhibno in učinkovito internetno izkušnjo in pomagajo ustvariti prijazne izkušnje brskanja, prilagojene potrebam vsakega uporabnika. Zavrnitev sprejemanja piškotkov ali njihovo deaktiviranje lahko onemogoči uporabo nekaterih spletnih mest. Zavrnitev sprejemanja piškotkov ali njihovo deaktiviranje ne pomeni, da ne boste več prejemali spletnih oglasov, temveč da ti oglasi ne bodo več upoštevali vaših interesov ali nastavitev, ki jih določa vaše vedenje brskanja.',
    'line_4_2' => 'Zavrnitev sprejemanja piškotkov ali njihovo deaktiviranje lahko oteži ali onemogoči navigacijo ali uporabo nekaterih spletnih mest. Zavrnitev sprejemanja piškotkov tudi ne pomeni, da ne boste več prejemali spletnih oglasov.',
    'line_4_3' => 'Vaš brskalnik lahko nastavite tako, da samodejno zavrne piškotke ali pa izberete samo nekatere spletne strani, kjer so piškotki omogočeni. Če pa na primer izklopite piškotke na tej spletni strani, ne morete slediti naslednjim korakom pri izpolnjevanju obrazca.',
    'line_4_4' => 'Sodobni brskalniki ponujajo možnost spreminjanja nastavitev piškotkov. Nastavitve piškotkov lahko običajno najdete na zavihku« možnosti »ali v meniju« nastavitve »vašega brskalnika.',
    'line_4_5' => 'Za več splošnih informacij o piškotkih in o tem, kako jih deaktivirati, lahko obiščete www.aboutcookies.org.',
    'subtitle_5' => 'Skupna raba podatkov',
    'line_5_1' => 'Obstajajo primeri, ko se od nas lahko zahteva, da razkrijemo osebne podatke, zbrane prek tega spletnega mesta, kot to zahteva zakon. Do vaših podatkov lahko dostopamo, jih hranimo in razkrivamo, če to zahtevajo zaradi izpolnjevanja zahtev kazenskega pregona in pravnih postopkov, kot so sodne odredbe ali če so bili pozvani, ali če to lahko zaščiti vaše ali druge pravice, lastnino ali splošno varnost.',
    'subtitle_6' => 'Nasveti za varno in odgovorno brskanje na podlagi piškotkov',
    'line_6_1' => 'Deaktiviranje piškotkov uporabnikom ne bo več omogočilo dostopa do nekaterih najpomembnejših spletnih mest, kot so Youtube, Gmail, Yahoo in druge. Tukaj je nekaj nasvetov, ki vam lahko pomagajo varno brskati, medtem ko hranite piškotke:',
    'line_6_2' => '- Prilagodite nastavitve piškotkov brskalnika, da omogočite udobno raven varnosti. Če vam piškotki ne predstavljajo težav in ste edina oseba, ki uporablja to napravo, lahko nastavite dolge intervale hrambe piškotkov za shranjevanje zgodovine brskanja in osebnih podatkov o dostopu.
- Če napravo ali računalnik delite v skupno rabo, boste morda želeli nastaviti brskalnik tako, da izbriše vaše posamezne podatke brskanja vsakič, ko je zaprt. To je eden od načinov za dostop do spletnih mest, ki na vaš računalnik v skupni rabi namestijo piškotke, medtem ko zaprete sejo, izbrišete vse podatke brskanja.
- namestite aplikacijo proti vohunski programski opremi in jo posodabljajte. Številne aplikacije proti vohunski programski opremi vključujejo zaznavanje napadov na spletnem mestu. Te aplikacije brskalniku preprečujejo dostop do spletnih mest, ki bi lahko izkoristila ranljivosti brskalnika ali prenesla nevarno programsko opremo. Prepričajte se, da je vaš brskalnik posodobljen. Številni napadi na osnovi piškotkov izkoriščajo šibke točke starih različic brskalnika.',
    'line_6_3' => 'Piškotki so povsod in se jim ni mogoče izogniti, če želite dostopati do nekaterih največjih in najboljših spletnih mest na internetu, bodisi lokalnih ali mednarodnih. Jasno razumevanje načina delovanja piškotkov in koristi, ki jih prinašajo, vam lahko sprejmete potrebne varnostne ukrepe, tako da imate vedno varno in zadovoljivo izkušnjo brskanja.',
    'subtitle_7' => 'Vaše pravice',
    'line_7_1' => 'Kot uporabnik spletne strani wevote4.eu imate naslednje pravice:',
    'line_7_2' => '- pravico do informacij v zvezi z obdelavo osebnih podatkov s strani Commit Global;
- pravico do dostopa do osebnih podatkov, na zahtevo in brezplačno za eno zahtevo na leto;
- pravico do posredovanja, popravljanja, izbrisa ali prenosljivosti osebnih podatkov na zahtevo in brezplačno;
- Pravica, da se obrnete na kateri koli pristojni organ glede vprašanj zasebnosti podatkov v zvezi z uporabo vaših osebnih podatkov
- Pravica do ugovora in avtomatizirani individualni postopek odločanja ter pravico do omejitve obdelave.',
    'line_7_3' => 'Ta pravilnik v celoti predstavlja sporazum, sklenjen med vami in Commit Global glede uporabe tega spletnega mesta.',
    'line_7_4' => 'Commit Global si pridržuje pravico, da kadarkoli spremeni in posodobi to politiko brez predhodnega obvestila ali predhodnega sprejetja uporabnikov. Če imate kakršna koli vprašanja v zvezi z informacijami na tej strani, nam pišite na ',
    'line_7_5' => 'Ta različica splošnih pogojev wevotefor.eu velja 23. maja 2024. ',
];
