<?php
return [
    'title' => 'Over het project',
    'line_1' => 'Stel je een enkele, levendige verkiezingsevenement voor dat meer dan 400 miljoen burgers uit de hele Europese Unie verenigt. EU-verkiezingen zijn niet alleen een reeks nationale stemmen, maar een collectieve viering van onze gedeelde identiteit en democratische waarden. Als EU-burgers komen we samen om onze gemeenschappelijke toekomst vorm te geven, door grenzen te overschrijden en de kracht van onze diversiteit te omarmen. Dit project is een bewijs van onze eenheid, waardoor het voor elke burger, ongeacht waar ze zich in de EU bevinden, gemakkelijker wordt om deel te nemen aan dit krachtige democratische proces.',
    'line_2' => 'Om deze visie van een verenigd verkiezingsproces te ondersteunen, heeft Commit Global een platform gecreëerd, **We Vote for EU**, dat het idee van eenheid en samenwerking belichaamt. Dit platform biedt alle EU-burgers essentiële informatie over hoe ze snel hun stem kunnen uitbrengen en stembureaus kunnen vinden, ongeacht hun locatie.',
    'subtitle' => 'Wat maakt dit platform bijzonder?',
    'line_3' => '**Decision Tree Format: ** Het platform maakt gebruik van een beslissingsboomindeling die EU-burgers rechtstreeks naar de specifieke informatie leidt die ze nodig hebben.',
    'line_4' => '**Uitgebreide informatie: ** De uiteindelijke verstrekte informatie is volledig en omvat registratievereisten (indien van toepassing), verschillende stemmethoden (volmacht, online, per post, stembureau), vereiste documenten om te stemmen en hulp voor kiezers met een handicap of andere beperkingen.',
    'line_5' => '**Geverifieerde informatie: ** De informatie op de website is gecontroleerd uit verschillende bronnen, waaronder nationale ministeries en organisaties die verantwoordelijk zijn voor de stemregels en -procedures, evenals het platform van het Europees Parlement.',
    'line_6' => '**Meertalige toegankelijkheid: ** We zorgen ervoor dat elke EU-burger toegang heeft tot de informatie die hij nodig heeft in zijn eigen taal. Het platform is beschikbaar in 26 talen, waarbij de beslissingsboom van elk land in de officiële taal (talen) en in het Engels wordt gegeven. Dit zorgt ervoor dat iedereen, ongeacht zijn taalkundige achtergrond, moeiteloos door het stemproces kan navigeren.',
    'line_7' => '**Onderling verbonden begeleiding: ** Ongeacht de EU-nationaliteit van de kiezer, zijn land van verblijf of zijn locatie op de dag van de verkiezingen, biedt het platform nauwkeurige, op maat gemaakte instructies en informatie die relevant is voor zijn unieke situatie. Het is alsof je een gepersonaliseerde stemassistent hebt die het proces soepel en inspirerend maakt.',
    'line_8' => 'We Vote for EU is een platform dat is opgericht en beheerd door **Commit Global**,\'s werelds eerste wereldwijde NGO op het gebied van civiele technologie. Met het hoofdkantoor in Den Haag (Nederland) consolideert, onderhoudt en biedt Commit Global gratis toegang tot kritieke digitale informatie, de **Infrastructure for Good**, aan maatschappelijke organisaties en getroffen bevolkingsgroepen over de hele wereld. Ga voor meer informatie over ons werk naar [onze website] (https://www.commitglobal.org).',
];
