<?php
return [
    'title' => 'Privacybeleid',
    'intro_1' => 'We respecteren uw privacy en erkennen dat we uw informatie op verantwoorde wijze moeten onderhouden en gebruiken.',
    'intro_2' => 'wevote4.eu is een website gemaakt door Commit Global („Commit Global”, „wij”, „ons”, „onze”) met als doel het publiek te informeren over de Europese verkiezingen.',
    'intro_3' => 'Dit privacybeleid beschrijft hoe we uw persoonlijke informatie op deze website verzamelen, gebruiken en beschermen. Door uw persoonlijke gegevens op deze website in te dienen, gaat u akkoord met de voorwaarden in dit privacybeleid. Als u het niet eens bent met deze voorwaarden, gebruik dan alstublieft onze website niet.',
    'subtitle_1' => 'Verzameling van gegevens',
    'line_1_1' => '- We verzamelen informatie van u als u deze website bezoekt via een gewone browser.
- Deze website maakt gebruik van cookies (bijvoorbeeld: Google Analytics) om de ervaring voor alle gebruikers te meten en te optimaliseren.
- Commit Global zal uw persoonlijke gegevens niet aan derden bekendmaken of verkopen, met uitzondering van de wettelijk bindende situaties die worden beschreven in dit privacybeleid.
- Commit Global zal alle redelijke maatregelen nemen om uw persoonlijke informatie te beschermen, aangezien dit een grote zorg voor ons is.',
    'line_1_2' => 'Bij een bezoek aan wevote4.eu verzamelen en bewaren we automatisch gegevens over uw huidige bezoek. Deze informatie is niet persoonlijk identificeerbaar. De informatie die we kunnen verzamelen is: het besturingssysteem op uw apparaat, de browser die u gebruikt, de pagina\'s in wevote4.eu die u hebt bezocht, de bron van uw bezoek (bijvoorbeeld: Google, Facebook), datum en tijd van uw bezoek en het domein van waaruit u toegang hebt tot het internet. Al deze informatie wordt gebruikt om de navigatie-ervaring op onze website verder te verbeteren en om de voorkeuren van onze bezoekers te begrijpen. We verzamelen via deze website geen persoonlijke informatie zonder uw uitdrukkelijke toestemming.',
    'subtitle_2' => 'Integraties van derden',
    'line_2_1' => 'Commit Global maakt gebruik van Google Analytics om beter te begrijpen hoe bezoekers op onze website navigeren en zo hun algehele ervaring te verbeteren. Google Analytics verzamelt geen identificeerbare informatie over zijn bezoekers en we verwerken de gegevens die via onze formulieren worden verzameld niet samen met de gegevens die door Google Analytics worden verstrekt.',
    'line_2_2' => 'Google Analytics plaatst een cookie in uw browser om u als unieke bezoeker te identificeren en dienovereenkomstig informatie over uw navigatie te verzamelen. Deze cookie wordt uitsluitend gebruikt door Google, die op zijn beurt deze gegevens niet mag delen en gebruiken op grond van de eigen gebruiksvoorwaarden van Google Analytics en het privacybeleid van Google.',
    'subtitle_3' => 'Wat zijn cookies',
    'line_3_1' => 'Een cookie („browsercookie” of „HTTP-cookie”) is een klein bestand, een opeenvolging van letters en cijfers, dat wordt opgeslagen op elk apparaat met internettoegang (computers, mobiele telefoons, tablets enz.) en wordt geïnstalleerd op verzoek van een server naar een browser (bijvoorbeeld: Internet Explorer, Chrome). „Cookies” bevatten geen softwareprogramma\'s, virussen of spyware en hebben geen toegang tot informatie op de harde schijf van de gebruiker. Een cookie bestaat uit een naam en inhoud, de duur van zijn bestaan is beperkt en de webserver kan deze opnieuw openen wanneer een gebruiker terugkeert naar de website die aan die server is gekoppeld.',
    'line_3_2' => 'Cookies slaan informatie op in een klein tekstbestand waardoor een website een browser kan herkennen. De webserver herkent de browser totdat de cookie verloopt of wordt verwijderd. De cookie slaat belangrijke informatie op die de surfervaring verbetert (bijvoorbeeld een serienummer voor uw donatie). Cookies vragen niet om persoonlijke informatie en identificeren ook geen internetgebruikers persoonlijk.',
    'line_3_3' => '- Sessiecookies - zijn cookies die tijdelijk worden opgeslagen in de geschiedenis van de browser, waar ze worden opgeslagen totdat de gebruiker die website verlaat of het browservenster sluit.
- Permanente cookies - Deze worden gedurende een vooraf bepaalde tijd opgeslagen op de harde schijf van een computer of soortgelijke apparatuur. Permanente cookies omvatten cookies die worden geplaatst door een andere website dan de website die de gebruiker op dat moment bezoekt, zogenaamde „cookies van derden” - die anoniem kunnen worden gebruikt om de interesses van een gebruiker te volgen - waardoor ze advertenties kunnen ontvangen die relevanter zijn voor hun interesses.',
    'line_3_4' => 'Er zijn cookies die uitsluitend voor een enkele sessie worden gebruikt - deze worden niet langer opgeslagen nadat de gebruiker de website heeft verlaten. Permanente cookies worden opgeslagen en hergebruikt telkens wanneer de gebruiker terugkeert naar die website, maar kunnen op elk moment door de gebruiker worden verwijderd.',
    'subtitle_4' => 'Hoe kunt u het gebruik van cookies blokkeren/afmelden',
    'line_4_1' => 'Cookies zijn een van de belangrijkste hulpmiddelen voor een naadloze, efficiënte internetervaring en helpen om gebruiksvriendelijke surfervaringen te creëren die zijn afgestemd op de behoeften van elke gebruiker. Als u cookies weigert of deactiveert, kan het gebruik van sommige websites onmogelijk worden. Het weigeren van cookies of het deactiveren ervan betekent niet dat u geen online advertenties meer zult ontvangen, alleen dat deze advertenties geen rekening meer houden met uw interesses of voorkeuren, zoals bepaald door uw surfgedrag.',
    'line_4_2' => 'Het weigeren of deactiveren van cookies kan ervoor zorgen dat sommige websites moeilijk of onmogelijk te navigeren of te gebruiken zijn. Het weigeren van cookies betekent ook niet dat u geen online advertenties meer zult ontvangen.',
    'line_4_3' => 'U kunt uw browser zo instellen dat cookies automatisch worden geweigerd of u kunt slechts enkele websites selecteren waar cookies zijn ingeschakeld. Maar als u bijvoorbeeld cookies uitschakelt op deze website, kunt u de volgende stappen bij het invullen van het formulier niet uitvoeren.',
    'line_4_4' => 'Moderne browsers bieden de mogelijkheid om cookie-instellingen te wijzigen. U kunt de cookie-instellingen meestal vinden onder het tabblad „opties” of in het menu „" voorkeuren "” van uw browser.”',
    'line_4_5' => 'Voor meer algemene informatie over cookies en hoe u ze kunt deactiveren, kunt u terecht op www.aboutcookies.org.',
    'subtitle_5' => 'Het delen van gegevens',
    'line_5_1' => 'Er kunnen zich situaties voordoen waarin, zoals wettelijk vereist, ons kan worden gevraagd om persoonlijke informatie die via deze website is verzameld, bekend te maken. We kunnen uw informatie inzien, bewaren en openbaar maken als daarom wordt gevraagd om te voldoen aan wetshandhavingsvereisten en juridische procedures, zoals gerechtelijke bevelen of als we worden gedagvaard, of als dit de rechten, eigendom of algemene veiligheid van u of anderen kan beschermen.',
    'subtitle_6' => 'Advies voor veilig en verantwoord browsen op basis van cookies',
    'line_6_1' => 'Door cookies te deactiveren, krijgt de gebruiker niet langer toegang tot enkele van de belangrijkste websites zoals YouTube, Gmail, Yahoo en andere. Hier zijn enkele tips die je kunnen helpen om veilig te surfen met behoud van cookies:',
    'line_6_2' => '- Pas de cookie-instellingen van uw browser aan om een comfortabel beveiligingsniveau mogelijk te maken. Als cookies geen probleem voor u zijn en u de enige persoon bent die dat apparaat gebruikt, kunt u lange bewaarintervallen voor cookies instellen om uw browsegeschiedenis en uw persoonlijke toegangsgegevens op te slaan.
- Als u het apparaat of de computer deelt, wilt u misschien de browser zo instellen dat uw individuele browsegegevens worden verwijderd telkens wanneer deze wordt gesloten. Dit is een manier om toegang te krijgen tot websites die cookies op uw gedeelde computer plaatsen en tegelijkertijd al uw browsegegevens verwijderen wanneer u de sessie sluit.
- installeer een antispyware-app en houd deze up-to-date. Veel antispyware-apps bevatten detectie van aanvallen op websites. Deze apps voorkomen dat de browser toegang krijgt tot websites die misbruik kunnen maken van de kwetsbaarheden van de browser of gevaarlijke software kunnen downloaden. Zorg ervoor dat je browser up-to-date is. Veel aanvallen op basis van cookies maken gebruik van de zwakke punten van oude browserversies.',
    'line_6_3' => 'Cookies zijn overal en kunnen niet worden vermeden als u toegang wilt krijgen tot enkele van de grootste en beste websites op het internet, zowel lokaal als internationaal. Als u duidelijk begrijpt hoe cookies werken en welke voordelen ze bieden, kunt u de nodige veiligheidsmaatregelen nemen zodat u altijd een veilige en bevredigende surfervaring hebt.',
    'subtitle_7' => 'Jouw rechten',
    'line_7_1' => 'Als gebruiker van de website wevote4.eu hebt u de volgende rechten:',
    'line_7_2' => '- Het recht op informatie over de verwerking van persoonsgegevens door Commit Global;
- Het recht op toegang tot persoonsgegevens, op verzoek en gratis voor één verzoek per jaar;
- Het recht op interventie, rectificatie, verwijdering of overdraagbaarheid van persoonlijke gegevens, op verzoek en gratis;
- Het recht om elke bevoegde autoriteit aan te spreken met betrekking tot gegevensprivacykwesties in verband met het gebruik van uw persoonlijke gegevens
- Het recht op verzet en het geautomatiseerde individuele besluitvormingsproces, evenals het recht om de verwerking te beperken.',
    'line_7_3' => 'Dit beleid vormt in zijn geheel een overeenkomst tussen u en Commit Global met betrekking tot het gebruik van deze site.',
    'line_7_4' => 'Commit Global behoudt zich het recht voor om dit beleid op elk moment te herzien en bij te werken, zonder voorafgaande kennisgeving of voorafgaande acceptatie van de gebruikers. Als u vragen hebt over de informatie op deze pagina, neem dan contact met ons op via ',
    'line_7_5' => 'Deze versie van de algemene voorwaarden van wevotefor.eu is van kracht vanaf 23 mei 2024. ',
];
