<?php
return [
    'title' => 'Beartas Príobháideachais',
    'line_6_1' => 'Ní ligfidh fianáin a dhíghníomhachtú rochtain úsáideora ar chuid de na suíomhanna Gréasáin is tábhachtaí mar Youtube, Gmail, Yahoo agus eile a thuilleadh. Seo roinnt comhairle a chabhróidh leat brabhsáil go sábháilte agus fianáin á choinneáil',
    'line_3_4' => 'Tá fianáin ann a úsáidtear go heisiach le haghaidh seisiún amháin - ní stóráiltear iad seo a thuilleadh tar éis don úsáideoir an láithreán gréasáin a fhágáil. Déantar fianáin bhuana a stóráil agus a athúsáid gach uair a fhilleann an t-úsáideoir ar an láithreán gréasáin sin ach is féidir leis an úsáideoir iad a scriosadh ag am ar bith.',
    'subtitle_4' => 'Conas fianáin a bhac a bhaint as úsáid',
    'line_7_5' => 'Tá an leagan seo de Téarmaí agus Coinníollacha wevotefor.eu éifeachtach amhail an 23 Bealtaine 2024. ',
    'subtitle_2' => 'Comhtháthú tríú páirtí',
    'line_7_1' => 'Mar úsáideoir ar shuíomh gréasáin wevote4.eu tá na cearta seo a leanas agat:',
    'line_4_3' => 'Is féidir leat do bhrabhsálaí a chur ar bun chun fianáin a dhiúltú go huathoibríoch nó ní féidir leat ach roinnt láithreáin ghréasáin a roghnú Ach, mar shampla, má mhúchann tú fianáin ar an suíomh Gréasáin seo ní féidir leat leanúint tríd leis na chéad chéimeanna eile chun an fhoirm a líonadh.',
    'subtitle_6' => 'Comhairle maidir le brabhsáil sábháilte agus freagrach atá bunaithe',
    'line_3_3' => '- Fianáin seisiúin - is fianáin iad a stóráiltear go sealadach i stair an bhrabhsálaí áit a stóráiltear iad go dtí go bhfágann an t-úsáideoir an láithreán gréasáin sin nó
- Fianáin leanúnacha - Stóráiltear iad seo, ar feadh tréimhse réamhshocraithe, ar thiomáint crua ríomhaire nó ar threalamh den chineál céanna. Cuimsíonn fianáin leanúnacha iad siúd a chuireann suíomh Gréasáin difriúil ná an ceann a bhfuil an t-úsáideoir ag tabhairt cuairte air ag an am, “fianáin tríú páirtí” mar a thugtar orthu - ar féidir iad a úsáid gan ainm chun leasanna úsáideora a rianú - a ligeann dóibh fógraí a fháil níos ábhartha dá leasanna.',
    'intro_1' => 'Tugaimid meas ar do phríobháideacht agus aithnímid go gcaithfimid d\'fhaisnéis a chothabháil agus',
    'line_3_1' => 'Is comhad beag é Fianán (“fianán brabhsálaí” nó “fianán HTTP”), comhad litreacha agus uimhreacha, a stóráiltear ar aon chríochfort le rochtain ar an Idirlíon (ríomhairí, fóin phóca, táibléad srl.) agus atá suiteáilte ar iarratas ó fhreastalaí chuig brabhsálaí (m.sh.: Internet Explorer, Chrome). Níl aon chláir bogearraí, víris nó spiaireacht i “fianáin” agus ní féidir leo rochtain a fháil ar fhaisnéis ar thiomáint crua an úsáideora. Is éard atá i bhfianán ainm agus ábhar, tá fad a bheith teoranta, agus is féidir leis an bhfreastalaí gréasáin rochtain a fháil arís nuair a fhilleann úsáideoir ar an suíomh Gréasáin a bhaineann leis an bhfreastalaí sin.',
    'line_2_1' => 'Úsáideann Commit Global Google Analytics chun tuiscint níos fearr a fháil ar an gcaoi a nascleanúnaíonn cuairteoirí ár suíomh Gréasáin chun a dtaith Ní bhailíonn Google Analytics aon fhaisnéis inaitheanta faoina gcuairteoirí agus ní phróiseálann muid na sonraí a bhailítear trínár bhfoirmeacha mar aon leis na sonraí a sholáthraíonn Google Analytics.',
    'line_5_1' => 'D\'fhéadfadh go mbeadh cásanna ann inar féidir iarraidh orainn faisnéis phearsanta a bhailítear tríd an láithreán gréasáin seo a nochtadh, de réir mar a cheanglaítear leis Féadfaimid rochtain a fháil ar d\'fhaisnéis, a chaomhnú agus a nochtadh má iarrfaimid d\'fhonn riachtanais forfheidhmithe dlí agus próisis dhlíthiúla a chomhlíonadh, amhail orduithe cúirte nó má chuirtear é sin cearta, maoin nó sábháilteacht ghinearálta duine eile a chosaint.',
    'line_1_2' => 'Nuair a chuirfimid cuairt ar wevote4.eu bailímid agus stóráilimid sonraí faoi do chuairt reatha go huathoibríoch. Ní féidir an fhaisnéis seo a aithint go pearsanta. Is é an fhaisnéis a d\'fhéadfaimis a bhailiú ná: córas oibriúcháin ar do ghléas, an brabhsálaí atá á úsáid agat, leathanaigh i wevote4.eu ar thug tú cuairt orthu, foinse do chuairte (m.sh.: Google, Facebook), dáta agus am do chuairte agus an fearann óna bhfaigheann tú rochtain ar an idirlíon. Úsáidtear an fhaisnéis seo go léir chun an taithí nascleanúna ar ár suíomh Gréasáin a fheabhsú tuilleadh agus chun roghanna ár gcuairteoirí a thuiscint. Ní bhailifimid aon fhaisnéis phearsanta tríd an láithreán gréasáin seo gan do thoiliú sainráite.',
    'line_1_1' => '- Bailímid faisnéis uait má rochtain agat ar an suíomh gréasáin seo trí bhrabhsálaí rialta.
- Úsáideann an láithreán gréasáin seo fianáin (m.sh.: Google Analytics) chun an taithí do gach úsáideoir a thomhas agus a bharrfheabhsú.
- Ní nochtfaidh Commit Global do chuid sonraí pearsanta le haon tríú páirtí, ach amháin na cásanna ceangailteacha go dlíthiúil a thuairiscítear sa Bheartas Príobháideachta seo.
- Glacfaidh Commit Global gach beart réasúnta chun d\'fhaisnéis phearsanta a chosaint mar is cúis imní mór dúinn é seo.',
    'line_6_3' => 'Tá fianáin i ngach áit agus ní féidir iad a sheachaint más mian leat rochtain a fháil ar chuid de na suíomhanna gréasáin is mó agus is fearr ar an idirlíon, áitiúil nó idirnáisiúnta. Is féidir leis an tuiscint shoiléir ar an mbealach a oibríonn fianáin agus na buntáistí a thugann siad duit na bearta slándála riachtanacha a ghlacadh ionas go mbeidh eispéireas brabhsála sásúil',
    'line_4_1' => 'Tá fianáin ar cheann de na huirlisí is tábhachtaí le haghaidh eispéireas Idirlín gan uaim, éifeachtach, ag cabhrú le heispéiris bhrabhsála cairdiúla a ghiniúint atá oiriúnach Má dhiúltú glacadh le fianáin nó iad a dhíghníomhachtú, is féidir roinnt suíomhanna Gréasáin a dhéanamh dodh Ní chiallaíonn diúltú glacadh le fianáin nó iad a dhíghníomhachtú nach bhfaighidh tú fógraí ar líne a thuilleadh, ach nach gcuirfidh na fógraí seo do leasanna nó do roghanna san áireamh a thuilleadh mar a chinnfidh d\'iompar brabhsála.',
    'intro_2' => 'Is suíomh Gréasáin é wevote4.eu a chruthaigh Commit Global (“Commit Global”, “muid”, “muid”, “ár”) chun an pobal a chur ar an eolas faoi na toghcháin Eorpacha.',
    'line_7_2' => '- An ceart chun faisnéis a fháil maidir le próiseáil sonraí pearsanta ag Commit Global;
- An ceart chun rochtain a fháil ar shonraí pearsanta, arna iarraidh agus saor in aisce ar iarratas amháin in aghaidh na bliana;
- An ceart idirghabhála, ceartú, scriosadh nó iniompartha sonraí pearsanta, arna iarraidh agus saor in aisce;
- An ceart chun aghaidh a thabhairt ar aon údarás inniúil maidir le saincheisteanna príobháideachta sonraí maidir le húsáid do shonraí pearsanta
- An ceart chun freasúra agus an próiseas cinnteoireachta aonair uathoibrithe chomh maith leis an gceart chun próiseáil a shrianadh.',
    'line_4_5' => 'Le haghaidh faisnéise níos ginearálta maidir le fianáin agus conas iad a dhíghníomhachtú, féadfaidh tú cuairt a thabhairt ar www.aboutcookies.org.',
    'line_2_2' => 'Cuirfidh Google Analytics fianán ar do bhrabhsálaí d\'fhonn go n-aithneoidh sé tú mar chuairteoir uathúil agus faisnéis a bhailiú faoi do nascleanúint dá réir. Úsáideann Google an fianán seo go heisiach a bhfuil srianta ar na sonraí seo a roinnt agus a úsáid ag a Téarmaí Úsáide Google Analytics féin agus Polasaí Príobháideachta Google.',
    'intro_3' => 'Déanann an Polasaí Príobháideachta seo cur síos ar an gcaoi a mbailímid, a úsáidimid agus a chosaint d\'fhaisnéis Trí d\'fhaisnéis phearsanta a chur isteach ar an suíomh Gréasáin seo, aontaíonn tú leis na téarmaí sa Bheartas Príobháideachta seo. Mura n-aontaíonn tú leis na téarmaí seo, ná bain úsáid as ár suíomh Gréasáin le do thoil.',
    'line_7_4' => 'Forchoimeádann Commit Global an ceart an beartas seo a athbhreithniú agus a nuashonrú ag am ar bith, gan fógra nó glacadh leis na húsáideoirí roimh ré Má tá aon cheist agat maidir leis an bhfaisnéis atá ar an leathanach seo, scríobh chugainn ag ',
    'subtitle_5' => 'Comhroinnt sonraí',
    'subtitle_3' => 'Cad iad fianáin',
    'line_7_3' => 'Is é an polasaí seo, ina iomláine, comhaontú a chuirtear i gcrích idir tú féin agus Commit Global maidir le húsáid an láithreáin seo.',
    'line_6_2' => '- Saincheap socruithe fianán do bhrabhsálaí chun leibhéal slándála compordach a cheadú Mura bhfuil fianáin ina fhadhb duit agus is tusa an t-aon duine a úsáideann an gléas sin is féidir leat eatraimh fhada coinneála fianán a shocrú d\'fhonn do stair brabhsála agus do shonraí rochtana pearsanta a stóráil.
- Má roinneann tú an gléas nó an ríomhaire b\'fhéidir gur mhaith leat an brabhsálaí a chur ar bun chun do chuid sonraí brabhsála aonair a scriosadh gach uair a dhúntar é. Is bealach amháin é seo chun rochtain a fháil ar láithreáin ghréasáin a chuireann fianáin ar do ríomhaire roinnte agus do chuid sonraí brabhsála go léir á scriosadh agus an
- suiteáil aip frith-spiaireachta agus coinnigh cothrom le dáta é. Cuimsíonn go leor aipeanna frith-spiaireachta braite ionsaí láithreán gréasáin Cuireann na feidhmchláir seo cosc ar an mbrabhsálaí rochtain a fháil ar láithreáin ghréasáin a d\'fhéadfadh leas a bhaint as leochaileachtaí Déan cinntiú go bhfuil do bhrabhsálaí Baineann go leor ionsaithe bunaithe ar fianáin leas as pointí laga seanleaganacha brabhsálaí.',
    'subtitle_1' => 'Bailiú sonraí',
    'line_4_2' => 'Má dhiúltaíonn glacadh le fianáin nó iad a dhíghníomhachtú, is féidir go mbeidh sé deacair nó dodhéanta roinnt suíomhanna Gréasáin Ní chiallaíonn diúltú glacadh le fianáin freisin nach bhfaighidh tú fógraí ar líne a thuilleadh.',
    'line_3_2' => 'Sábhálann fianáin faisnéis i gcomhad téacs beag a ligeann do shuíomh Gréasáin brabhsálaí a aithint Aithneoidh an freastalaí gréasáin an bhrabhsálaí suas go dtí go rachaidh an fianán in éag nó Stórálann an fianán faisnéis thábhachtach a fheabhsaíonn an taithí brabhsála (m.sh. sraithuimhir do do shíntiús Ní iarrann fianáin faisnéis phearsanta ná ní aithníonn siad úsáideoirí idirlín go pearsanta.',
    'line_4_4' => 'Tugann brabhsálaithe nua-aimseartha an cumas socruithe fianán a athrú De ghnáth is féidir leat socruithe fianán a fháil faoin gcluaisín “roghanna” nó roghchlár “roghanna” do bhrabhsálaí.',
    'subtitle_7' => 'Do chearta',
];
