<?php
return [
    'title' => 'Informazioni sul progetto',
    'line_1' => 'Immagina un unico e vivace evento elettorale che unisca oltre 400 milioni di cittadini in tutta l\'Unione europea. Le elezioni dell\'UE non sono solo una serie di voti nazionali, ma una celebrazione collettiva della nostra identità condivisa e dei nostri valori democratici. Come cittadini dell\'UE, ci uniamo per dare forma al nostro futuro comune, superando i confini e abbracciando la forza della nostra diversità. Questo progetto è una testimonianza della nostra unità e rende più facile per ogni cittadino, indipendentemente da dove si trovi nell\'UE, partecipare a questo potente processo democratico.',
    'line_2' => 'Per sostenere questa visione di un processo elettorale unificato, Commit Global ha creato una piattaforma, **We Vote for EU**, che incarna l\'idea di unità e collaborazione. Questa piattaforma fornisce a tutti i cittadini dell\'UE informazioni essenziali su come esprimere il proprio voto e trovare rapidamente i seggi elettorali, indipendentemente dalla loro ubicazione.',
    'subtitle' => 'Cosa rende speciale questa piattaforma?',
    'line_3' => '**Formato dell\'albero decisionale: ** La piattaforma utilizza un formato ad albero decisionale che guida i cittadini dell\'UE direttamente alle informazioni specifiche di cui hanno bisogno.',
    'line_4' => '**Informazioni complete: ** Le informazioni finali fornite sono complete e coprono i requisiti di registrazione (se presenti), i diversi metodi di voto (delega, online, postale, seggio elettorale), la documentazione richiesta per il voto e l\'assistenza per gli elettori con disabilità o altre limitazioni.',
    'line_5' => '**Informazioni verificate: ** Le informazioni presentate sul sito Web sono verificate da diverse fonti, tra cui i ministeri e le organizzazioni nazionali responsabili delle regole e delle procedure di voto, nonché la piattaforma del Parlamento europeo.',
    'line_6' => '**Accessibilità multilingue: ** Ci assicuriamo che ogni cittadino dell\'UE possa accedere alle informazioni di cui ha bisogno nella propria lingua. La piattaforma è disponibile in 26 lingue, con l\'albero decisionale di ciascun paese fornito nella lingua o nelle lingue ufficiali e in inglese. Ciò garantisce che tutti, indipendentemente dal loro background linguistico, possano navigare senza problemi nel processo di voto.',
    'line_7' => '**Guida interconnessa: ** Indipendentemente dalla nazionalità UE dell\'elettore, dal suo paese di residenza o dalla sua ubicazione il giorno delle elezioni, la piattaforma fornisce istruzioni e informazioni precise e personalizzate pertinenti alla sua situazione specifica. È come avere un assistente di voto personalizzato che rende il processo fluido e stimolante.',
    'line_8' => 'We Vote for EU è una piattaforma creata e gestita da **Commit Global**, la prima ONG globale di tecnologia civica al mondo. Con sede a L\'Aia (Paesi Bassi), Commit Global consolida, mantiene e fornisce l\'accesso gratuito al digitale critico, l\' **Infrastructure for Good**, alle organizzazioni della società civile e alle popolazioni colpite in tutto il mondo. Per ulteriori informazioni sul nostro lavoro, visitate il [nostro sito Web] (https://www.commitglobal.org).',
];
