<?php
return [
    'line_6_1' => 'La disattivazione dei cookie non consentirà più all\'utente di accedere ad alcuni dei siti Web più importanti come Youtube, Gmail, Yahoo e altri. Ecco alcuni consigli che possono aiutarti a navigare in sicurezza conservando i cookie:',
    'line_3_4' => 'Esistono cookie utilizzati esclusivamente per una singola sessione: non vengono più memorizzati dopo che l\'utente ha lasciato il sito Web. I cookie permanenti vengono memorizzati e riutilizzati ogni volta che l\'utente torna su quel sito Web, ma possono essere eliminati in qualsiasi momento dall\'utente.',
    'subtitle_4' => 'Come bloccare/negare il consenso all\'uso dei cookie',
    'line_7_5' => 'Questa versione dei Termini e condizioni di wevotefor.eu è in vigore dal 23 maggio 2024. ',
    'line_7_1' => 'Come utente del sito web wevote4.eu hai i seguenti diritti:',
    'line_4_3' => 'Puoi configurare il tuo browser in modo da rifiutare automaticamente i cookie oppure puoi selezionare solo alcuni siti Web in cui i cookie sono abilitati. Tuttavia, ad esempio, se disattivi i cookie su questo sito Web, non puoi seguire i passaggi successivi della compilazione del modulo.',
    'subtitle_6' => 'Consigli per una navigazione sicura e responsabile basata sui cookie',
    'line_3_3' => '- Cookie di sessione: sono cookie memorizzati temporaneamente nella cronologia del browser dove vengono memorizzati fino a quando l\'utente non lascia quel sito Web o chiude la finestra del browser.
- Cookie persistenti: vengono memorizzati, per un periodo di tempo predeterminato, sul disco rigido di un computer o su un\'apparecchiatura simile. I cookie persistenti includono quelli inseriti da un sito Web diverso da quello che l\'utente sta visitando in quel momento, i cosiddetti «cookie di terze parti», che possono essere utilizzati in modo anonimo per tracciare gli interessi dell\'utente, consentendo a quest\'ultimo di ricevere annunci più pertinenti ai suoi interessi.',
    'subtitle_2' => 'Integrazioni di terze parti',
    'intro_1' => 'Rispettiamo la tua privacy e riconosciamo che dobbiamo conservare e utilizzare le tue informazioni in modo responsabile.',
    'line_2_1' => 'Commit Global utilizza Google Analytics per capire meglio come i visitatori navigano nel nostro sito Web e migliorare la loro esperienza complessiva. Google Analytics non raccoglie alcuna informazione identificabile sui suoi visitatori e non trattiamo i dati raccolti tramite i nostri moduli insieme ai dati forniti da Google Analytics.',
    'title' => 'Informativa sulla privacy',
    'intro_2' => 'wevote4.eu è un sito web creato da Commit Global («Commit Global», «noi», «ci», «nostro») con lo scopo di informare il pubblico sulle elezioni europee.',
    'subtitle_3' => 'Cosa sono i cookie',
    'subtitle_1' => 'Raccolta dati',
    'line_3_1' => 'Un cookie («cookie del browser» o «cookie HTTP») è un piccolo file, una successione di lettere e numeri, che viene memorizzato su qualsiasi terminale con accesso a Internet (computer, telefoni cellulari, tablet ecc.) e viene installato su richiesta da un server a un browser (es: Internet Explorer, Chrome). I «cookie» non contengono programmi software, virus o spyware e non possono accedere alle informazioni sul disco rigido dell\'utente. Un cookie è costituito da un nome e da un contenuto, la sua durata è limitata ed è nuovamente accessibile dal server web quando un utente ritorna sul sito Web associato a quel server.',
    'line_5_1' => 'Potrebbero esserci situazioni in cui, come richiesto dalla legge, ci potrebbe essere richiesto di divulgare le informazioni personali raccolte tramite questo sito Web. Possiamo accedere, conservare e divulgare le tue informazioni se richiesto al fine di rispettare i requisiti delle forze dell\'ordine e i procedimenti legali, ad esempio ordinanze del tribunale o in caso di citazione in giudizio, o se ciò può proteggere i diritti, la proprietà o la sicurezza generale dell\'utente o di altri.',
    'line_1_2' => 'Quando visiti wevote4.eu, raccoglieremo e memorizzeremo automaticamente i dati sulla tua visita attuale. Queste informazioni non sono personalmente identificabili. Le informazioni che possiamo raccogliere sono: il sistema operativo del tuo dispositivo, il browser che stai utilizzando, le pagine di wevote4.eu che hai visitato, la fonte della tua visita (es: Google, Facebook), la data e l\'ora della tua visita e il dominio da cui accedi a Internet. Tutte queste informazioni vengono utilizzate per migliorare ulteriormente l\'esperienza di navigazione sul nostro sito Web e per comprendere le preferenze dei nostri visitatori. Non raccoglieremo alcuna informazione personale tramite questo sito Web senza il tuo esplicito consenso.',
    'line_1_1' => '- Raccogliamo informazioni da te se accedi a questo sito Web tramite un normale browser.
- Questo sito Web utilizza i cookie (ad es. Google Analytics) per misurare e ottimizzare l\'esperienza di tutti gli utenti.
- Commit Global non divulgherà o venderà i tuoi dati personali a terzi, ad eccezione delle situazioni legalmente vincolanti descritte nella presente Informativa sulla privacy.
- Commit Global adotterà tutte le misure ragionevoli per proteggere le tue informazioni personali poiché questa è una delle nostre principali preoccupazioni.',
    'line_6_3' => 'I cookie sono ovunque e non possono essere evitati se si desidera accedere ad alcuni dei più grandi e migliori siti Web su Internet, locali o internazionali. Una chiara comprensione del funzionamento dei cookie e dei vantaggi che ne derivano consente di adottare le misure di sicurezza necessarie in modo da avere sempre un\'esperienza di navigazione sicura e soddisfacente.',
    'line_4_1' => 'I cookie sono uno degli strumenti più importanti per un\'esperienza Internet fluida ed efficiente, che aiutano a generare esperienze di navigazione amichevoli su misura per le esigenze di ogni utente. Il rifiuto di accettare i cookie o la loro disattivazione può rendere impossibile l\'utilizzo di alcuni siti Web. Il rifiuto di accettare i cookie o la loro disattivazione non significa che non riceverai più annunci online, ma solo che questi annunci non terranno più conto dei tuoi interessi o delle tue preferenze, determinati dal tuo comportamento di navigazione.',
    'line_7_2' => '- Il diritto all\'informazione sul trattamento dei dati personali da parte di Commit Global;
- Il diritto di accedere ai dati personali, su richiesta e gratuitamente per una richiesta all\'anno;
- Il diritto di intervento, rettifica, cancellazione o portabilità dei dati personali, su richiesta e gratuitamente;
- Il diritto di rivolgersi a qualsiasi autorità competente in merito a questioni relative alla riservatezza dei dati in relazione all\'uso dei dati personali
- Il diritto all\'opposizione e al processo decisionale individuale automatizzato, nonché il diritto di limitare il trattamento.',
    'line_4_5' => 'Per informazioni più generali sui cookie e su come disattivarli, puoi visitare www.aboutcookies.org.',
    'line_2_2' => 'Google Analytics inserirà un cookie nel tuo browser per identificarti come visitatore unico e raccogliere di conseguenza informazioni sulla tua navigazione. Questo cookie viene utilizzato esclusivamente da Google, che a sua volta è limitato dalla condivisione e dall\'utilizzo di questi dati dai propri Termini di utilizzo di Google Analytics e dalle Norme sulla privacy di Google.',
    'intro_3' => 'La presente Informativa sulla privacy descrive come raccogliamo, utilizziamo e proteggiamo le tue informazioni personali su questo sito web. Inviando le tue informazioni personali su questo sito Web, accetti i termini della presente Informativa sulla privacy. Se non siete d\'accordo con questi termini, vi preghiamo di non utilizzare il nostro sito Web.',
    'line_7_4' => 'Commit Global si riserva il diritto di rivedere e aggiornare questa politica in qualsiasi momento, senza preavviso o previa accettazione da parte degli utenti. Se avete domande sulle informazioni contenute in questa pagina, scriveteci all\'indirizzo ',
    'subtitle_5' => 'Condivisione dei dati',
    'line_7_3' => 'Questa politica costituisce, nella sua interezza, un accordo concluso tra te e Commit Global in merito all\'uso di questo sito.',
    'line_6_2' => '- Personalizza le impostazioni dei cookie del browser per consentire un livello di sicurezza confortevole. Se i cookie non sono un problema per te e sei l\'unica persona che utilizza quel dispositivo, puoi impostare lunghi intervalli di conservazione dei cookie per memorizzare la cronologia di navigazione e i tuoi dati di accesso personali.
- Se condividi il dispositivo o il computer, potresti voler configurare il browser in modo da eliminare i tuoi dati di navigazione individuali ogni volta che viene chiuso. Questo è un modo per accedere ai siti Web che inseriscono cookie sul computer condiviso e allo stesso tempo eliminare tutti i dati di navigazione alla chiusura della sessione.
- installa un\'app anti-spyware e mantienila aggiornata. Molte app anti-spyware includono il rilevamento degli attacchi ai siti Web. Queste app impediscono al browser di accedere a siti Web che potrebbero sfruttare le vulnerabilità del browser o scaricare software pericoloso. Assicurati che il tuo browser sia aggiornato. Molti attacchi basati sui cookie sfruttano i punti deboli delle vecchie versioni dei browser.',
    'line_4_2' => 'Il rifiuto di accettare i cookie o la loro disattivazione può rendere alcuni siti Web difficili o impossibili da navigare o utilizzare. Il rifiuto di accettare i cookie, inoltre, non significa che non riceverai più annunci online.',
    'line_3_2' => 'I cookie salvano le informazioni in un piccolo file di testo che consente a un sito Web di riconoscere un browser. Il server web riconoscerà il browser fino alla scadenza o all\'eliminazione del cookie. Il cookie memorizza informazioni importanti che migliorano l\'esperienza di navigazione (ad esempio un numero di serie per la donazione). I cookie non richiedono informazioni personali né identificano personalmente gli utenti di Internet.',
    'line_4_4' => 'I browser moderni offrono la possibilità di modificare le impostazioni dei cookie. Di solito puoi trovare le impostazioni dei cookie nella scheda «opzioni» o nel menu «preferenze» del tuo browser.',
    'subtitle_7' => 'I tuoi diritti',
];
