<?php
return [
    'title' => 'Acerca del proyecto',
    'line_1' => 'Imagine un evento electoral único y vibrante que reúna a más de 400 millones de ciudadanos de toda la Unión Europea. Las elecciones de la UE no son solo una serie de votaciones nacionales, sino una celebración colectiva de nuestra identidad compartida y nuestros valores democráticos. Como ciudadanos de la UE, nos unimos para dar forma a nuestro futuro común, trascendiendo las fronteras y abrazando la fuerza de nuestra diversidad. Este proyecto es un testimonio de nuestra unidad, ya que facilita que todos los ciudadanos, sin importar en qué parte de la UE se encuentren, participen en este poderoso proceso democrático.',
    'line_2' => 'Para apoyar esta visión de un proceso electoral unificado, Commit Global ha creado una plataforma, **Votamos por la UE**, que encarna la idea de unidad y colaboración. Esta plataforma proporciona a todos los ciudadanos de la UE información esencial sobre cómo emitir su voto y encontrar centros de votación rápidamente, independientemente de su ubicación.',
    'subtitle' => '¿Qué hace que esta plataforma sea especial?',
    'line_3' => '**Formato de árbol de decisiones: ** La plataforma utiliza un formato de árbol de decisiones que guía a los ciudadanos de la UE directamente a la información específica que necesitan.',
    'line_4' => '**Información completa: ** La información final proporcionada es exhaustiva y abarca los requisitos de registro (si los hubiera), los diferentes métodos de votación (por poder, en línea, postal, centro de votación), la documentación requerida para votar y la asistencia para los votantes con discapacidades u otras limitaciones.',
    'line_5' => '**Información verificada: ** La información presentada en el sitio web se cotejó a partir de múltiples fuentes diferentes, incluidos los ministerios y organizaciones nacionales responsables de las normas y procedimientos de votación, así como la plataforma del Parlamento Europeo.',
    'line_6' => '**Accesibilidad multilingüe: ** Nos aseguramos de que todos los ciudadanos de la UE puedan acceder a la información que necesitan en su propio idioma. La plataforma está disponible en 26 idiomas, y el árbol de decisiones de cada país está disponible en su (s) idioma (s) oficial (s) y en inglés. Esto garantiza que todos, sin importar su origen lingüístico, puedan navegar por el proceso de votación sin esfuerzo.',
    'line_7' => '**Orientación interconectada: ** Independientemente de la nacionalidad de la UE del votante, su país de residencia o su ubicación el día de las elecciones, la plataforma proporciona instrucciones e información precisas y personalizadas relevantes para su situación particular. Es como tener un asistente de votación personalizado que hace que el proceso sea fluido e inspirador.',
    'line_8' => 'We Vote for EU es una plataforma creada y gestionada por **Commit Global**, la primera ONG global de tecnología cívica del mundo. Con sede en La Haya (Países Bajos), Commit Global consolida, mantiene y proporciona acceso gratuito a la tecnología digital crítica, la **Infraestructura para el bien**, a las organizaciones de la sociedad civil y las poblaciones afectadas de todo el mundo. Para obtener más información sobre nuestro trabajo, visite [nuestro sitio web] (https://www.commitglobal.org).',
];
