<?php
return [
    'subtitle_2' => 'Integraciones de terceros',
    'intro_1' => 'Respetamos su privacidad y reconocemos que debemos mantener y usar su información de manera responsable.',
    'line_1_2' => 'Al visitar wevote4.eu, recopilaremos y almacenaremos automáticamente datos sobre su visita actual. Esta información no es identificable personalmente. La información que podemos recopilar es: el sistema operativo de su dispositivo, el navegador que está utilizando, las páginas de wevote4.eu que ha visitado, el origen de su visita (por ejemplo, Google o Facebook), la fecha y hora de la visita y el dominio desde el que accede a Internet. Toda esta información se utiliza para mejorar aún más la experiencia de navegación en nuestro sitio web y para comprender las preferencias de nuestros visitantes. No recopilaremos ninguna información personal a través de este sitio web sin su consentimiento expreso.',
    'title' => 'Política de privacidad',
    'line_1_1' => '- Recopilamos información sobre usted si accede a este sitio web a través de un navegador normal.
- Este sitio web utiliza cookies (por ejemplo, Google Analytics) para medir y optimizar la experiencia de todos los usuarios.
- Commit Global no divulgará ni venderá sus datos personales a ningún tercero, excepto en las situaciones legalmente vinculantes descritas en esta Política de privacidad.
- Commit Global tomará todas las medidas razonables para proteger su información personal, ya que esta es una de nuestras principales preocupaciones.',
    'intro_2' => 'wevote4.eu es un sitio web creado por Commit Global («Commit Global», «nosotros», «nos», «nuestro») con el propósito de informar al público sobre las elecciones europeas.',
    'intro_3' => 'Esta Política de privacidad describe cómo recopilamos, utilizamos y protegemos su información personal en este sitio web. Al enviar su información personal a este sitio web, usted acepta los términos de esta Política de privacidad. Si no está de acuerdo con estos términos, no utilice nuestro sitio web.',
    'subtitle_1' => 'Recopilación de datos',
    'subtitle_4' => 'Cómo bloquear/rechazar el uso de cookies',
    'line_7_5' => 'Esta versión de los términos y condiciones de wevotefor.eu entrará en vigor el 23 de mayo de 2024. ',
    'line_7_1' => 'Como usuario del sitio web wevote4.eu, tiene los siguientes derechos:',
    'line_6_3' => 'Las cookies están en todas partes y no se pueden evitar si desea acceder a algunos de los sitios web más grandes y mejores de Internet, ya sean locales o internacionales. Con una comprensión clara de la forma en que funcionan las cookies y los beneficios que aportan, puede tomar las medidas de seguridad necesarias para que siempre tenga una experiencia de navegación segura y satisfactoria.',
    'line_7_2' => '- El derecho a la información sobre el procesamiento de datos personales por parte de Commit Global;
- El derecho a acceder a los datos personales, previa solicitud y de forma gratuita durante una solicitud al año;
- El derecho de intervención, rectificación, eliminación o portabilidad de los datos personales, previa solicitud y de forma gratuita;
- El derecho a dirigirse a cualquier autoridad competente en relación con las cuestiones de privacidad de los datos en relación con el uso de sus datos personales
- El derecho a la oposición y al proceso automatizado de toma de decisiones individuales, así como el derecho a restringir el procesamiento.',
    'line_7_4' => 'Commit Global se reserva el derecho de revisar y actualizar esta política en cualquier momento, sin previo aviso ni aceptación de los usuarios. Si tiene alguna pregunta sobre la información contenida en esta página, escríbanos a ',
    'line_7_3' => 'Esta política constituye, en su totalidad, un acuerdo celebrado entre usted y Commit Global con respecto al uso de este sitio.',
    'subtitle_7' => 'Sus derechos',
    'line_4_5' => 'Para obtener más información general sobre las cookies y cómo desactivarlas, puede visitar www.aboutcookies.org.',
    'line_2_2' => 'Google Analytics colocará una cookie en su navegador para identificarlo como visitante único y recopilar información sobre su navegación en consecuencia. Esta cookie es utilizada exclusivamente por Google, quien, a su vez, no puede compartir ni utilizar estos datos según sus propias condiciones de uso de Google Analytics y su política de privacidad de Google.',
    'subtitle_5' => 'Intercambio de datos',
    'subtitle_3' => 'Qué son las cookies',
    'line_6_2' => '- Personalice la configuración de cookies de su navegador para permitir un nivel de seguridad cómodo. Si las cookies no suponen un problema para usted y es la única persona que utiliza ese dispositivo, puede establecer intervalos de retención de cookies prolongados para almacenar su historial de navegación y sus datos de acceso personales.
- Si compartes el dispositivo o el ordenador, es posible que desees configurar el navegador para que borre tus datos de navegación individuales cada vez que lo cierres. Esta es una forma de acceder a sitios web que colocan cookies en el ordenador compartido y, al mismo tiempo, borrar todos los datos de navegación al cerrar la sesión.
- instale una aplicación antispyware y manténgala actualizada. Muchas aplicaciones antispyware incluyen la detección de ataques a sitios web. Estas aplicaciones impiden que el navegador acceda a sitios web que podrían aprovechar las vulnerabilidades del navegador o descargar software peligroso. Asegúrese de que su navegador esté actualizado. Muchos ataques basados en cookies explotan los puntos débiles de las versiones antiguas de los navegadores.',
    'line_4_2' => 'Negarse a aceptar cookies o desactivarlas puede dificultar o imposibilitar la navegación o el uso de algunos sitios web. Negarse a aceptar las cookies tampoco significa que deje de recibir anuncios en línea.',
    'line_3_2' => 'Las cookies guardan la información en un pequeño archivo de texto que permite a un sitio web reconocer un navegador. El servidor web reconocerá el navegador hasta que la cookie caduque o se elimine. La cookie almacena información importante que mejora la experiencia de navegación (por ejemplo, un número de serie para su donación). Las cookies no solicitan información personal ni identifican personalmente a los usuarios de Internet.',
    'line_6_1' => 'La desactivación de las cookies ya no permitirá a los usuarios acceder a algunos de los sitios web más importantes, como Youtube, Gmail, Yahoo y otros. Estos son algunos consejos que pueden ayudarle a navegar de forma segura y conservar las cookies:',
    'line_3_4' => 'Hay cookies que se utilizan exclusivamente para una sola sesión; ya no se almacenan después de que el usuario haya abandonado el sitio web. Las cookies permanentes se almacenan y se reutilizan cada vez que el usuario regresa a ese sitio web, pero el usuario puede eliminarlas en cualquier momento.',
    'line_4_3' => 'Puede configurar su navegador para que rechace las cookies automáticamente o puede seleccionar solo algunos sitios web en los que estén habilitadas las cookies. Pero, por ejemplo, si desactiva las cookies en este sitio web, no podrá completar los pasos siguientes para completar el formulario.',
    'subtitle_6' => 'Consejos para una navegación segura y responsable basada en cookies',
    'line_3_3' => '- Cookies de sesión: son cookies que se almacenan temporalmente en el historial del navegador, donde se almacenan hasta que el usuario abandone ese sitio web o cierre la ventana del navegador.
- Cookies persistentes: se almacenan, durante un período de tiempo predeterminado, en el disco duro de una computadora o equipo similar. Las cookies persistentes incluyen las colocadas por un sitio web diferente al que el usuario está visitando en ese momento, las denominadas «cookies de terceros», que se pueden utilizar de forma anónima para rastrear los intereses de un usuario, lo que le permite recibir anuncios más relevantes para sus intereses.',
    'line_3_1' => 'Una cookie («cookie del navegador» o «cookie HTTP») es un archivo pequeño, una sucesión de letras y números, que se almacena en cualquier terminal con acceso a Internet (ordenadores, teléfonos móviles, tabletas, etc.) y se instala cuando un servidor lo solicita a un navegador (por ejemplo, Internet Explorer, Chrome). Las «cookies» no contienen ningún programa de software, virus o spyware y no pueden acceder a la información del disco duro del usuario. Una cookie se compone de un nombre y un contenido, su duración es limitada y el servidor web puede volver a acceder a ella cuando un usuario regresa al sitio web asociado a ese servidor.',
    'line_2_1' => 'Commit Global utiliza Google Analytics para comprender mejor cómo los visitantes navegan por nuestro sitio web y mejorar su experiencia general. Google Analytics no recopila ninguna información identificable sobre sus visitantes y no procesamos los datos recopilados a través de nuestros formularios junto con los datos proporcionados por Google Analytics.',
    'line_5_1' => 'Puede haber situaciones en las que, según lo exija la ley, se nos solicite que divulguemos la información personal recopilada a través de este sitio web. Podemos acceder a su información, conservarla y divulgarla si así lo solicita para cumplir con los requisitos de aplicación de la ley y los procesos legales, como las órdenes judiciales o en caso de citación judicial, o si esto puede proteger sus derechos, propiedades o seguridad general o los de otras personas.',
    'line_4_1' => 'Las cookies son una de las herramientas más importantes para una experiencia de Internet eficiente y sin interrupciones, ya que ayudan a generar experiencias de navegación amigables y adaptadas a las necesidades de cada usuario. Negarse a aceptar las cookies o desactivarlas puede hacer que algunos sitios web sean imposibles de usar. Negarse a aceptar las cookies o desactivarlas no significa que deje de recibir anuncios en línea, solo que estos anuncios dejarán de tener en cuenta sus intereses o preferencias según lo determine su comportamiento de navegación.',
    'line_4_4' => 'Los navegadores modernos ofrecen la posibilidad de cambiar la configuración de las cookies. Por lo general, puede encontrar la configuración de las cookies en la pestaña «opciones» o en el menú «preferencias» de su navegador.',
];
