<?php
return [
    'title' => 'Tietosuojakäytäntö',
    'line_6_1' => 'Evästeiden poistaminen käytöstä ei enää salli käyttäjän pääsyä tärkeimmille verkkosivustoille, kuten Youtube, Gmail, Yahoo ja muut. Seuraavassa on muutamia neuvoja, joiden avulla voit selata turvallisesti ja säilyttää evästeet:',
    'line_7_5' => 'Tämä wevotefor.eu käyttöehtojen versio on voimassa 23. toukokuuta 2024 alkaen. ',
    'subtitle_6' => 'Ohjeita turvalliseen ja vastuulliseen evästepohjaiseen selaamiseen',
    'line_5_1' => 'Saattaa olla tilanteita, joissa lain edellyttämällä tavalla meitä saatetaan pyytää luovuttamaan tämän verkkosivuston kautta kerättyjä henkilötietoja. Saatamme käyttää, säilyttää ja luovuttaa tietojasi, jos sitä pyydetään noudattaaksemme lainvalvontavaatimuksia ja oikeudellisia prosesseja, kuten tuomioistuimen määräyksiä tai jos ne haastetaan, tai jos tämä voi suojata sinua tai muiden oikeuksia, omaisuutta tai yleistä turvallisuutta.',
    'line_4_5' => 'Lisätietoja evästeistä ja niiden käytöstä poistamisesta on osoitteessa www.aboutcookies.org.',
    'subtitle_5' => 'Tietojen jakaminen',
    'line_3_4' => 'On olemassa evästeitä, joita käytetään yksinomaan yhteen istuntoon - niitä ei enää tallenneta käyttäjän poistuttua verkkosivustolta. Pysyvät evästeet tallennetaan ja niitä käytetään uudelleen aina, kun käyttäjä palaa kyseiselle verkkosivustolle, mutta käyttäjä voi poistaa ne milloin tahansa.',
    'subtitle_4' => 'Evästeiden käytön estäminen/kieltäminen',
    'subtitle_2' => 'Kolmannen osapuolen integraatiot',
    'line_4_3' => 'Voit asettaa selaimesi hylkäämään evästeet automaattisesti tai voit valita vain joitain verkkosivustoja, joissa evästeet ovat käytössä. Mutta jos esimerkiksi poistat evästeet käytöstä tällä verkkosivustolla, et voi seurata seuraavia vaiheita lomakkeen täyttämisessä.',
    'line_3_3' => '- Istuntoevästeet - ovat evästeitä, jotka tallennetaan väliaikaisesti selaimen historiaan, jonne ne tallennetaan, kunnes käyttäjä poistuu kyseisestä verkkosivustosta tai sulkee selainikkunan.
- Pysyvät evästeet - Ne tallennetaan ennalta määrätyn ajan tietokoneen kiintolevylle tai vastaavalle laitteelle. Pysyviä evästeitä ovat muun verkkosivuston asettamat evästeet kuin se, jolla käyttäjä vierailee, ns. ”Kolmannen osapuolen evästeet” - joita voidaan käyttää nimettömästi käyttäjän kiinnostuksen kohteiden seuraamiseen - jolloin he voivat vastaanottaa kiinnostuksen kohteidensa mukaisia mainoksia.',
    'intro_1' => 'Kunnioitamme yksityisyyttäsi ja tunnustamme, että meidän on säilytettävä ja käytettävä tietojasi vastuullisesti.',
    'line_3_1' => 'Eväste (”selaineväste” tai ”HTTP-eväste”) on pieni kirjainten ja numeroiden peräkkäinen tiedosto, joka tallennetaan mihin tahansa päätelaitteeseen, jolla on Internet-yhteys (tietokoneet, matkapuhelimet, tabletit jne.) ja joka asennetaan palvelimelta selaimelle (esim. Internet Explorer, Chrome) pyynnöstä. ”Evästeet” eivät sisällä ohjelmistoja, viruksia tai vakoiluohjelmia eivätkä pääse käsiksi käyttäjän kiintolevyllä oleviin tietoihin. Eväste koostuu nimestä ja sisällöstä, sen olemassaolon kesto on rajoitettu, ja verkkopalvelin voi käyttää sitä uudelleen, kun käyttäjä palaa kyseiseen palvelimeen liittyvälle verkkosivustolle.',
    'line_2_1' => 'Commit Global käyttää Google Analyticsia ymmärtääkseen paremmin, miten kävijät navigoivat verkkosivustollamme parantaakseen yleistä kokemustaan. Google Analytics ei kerää mitään tunnistettavia tietoja kävijöistään, emmekä käsittele lomakkeidemme kautta kerättyjä tietoja yhdessä Google Analyticsin toimittamien tietojen kanssa.',
    'line_1_2' => 'Vieraillessamme wevote4.eu keräämme ja tallennamme automaattisesti tietoja nykyisestä vierailustasi. Nämä tiedot eivät ole henkilökohtaisesti tunnistettavissa. Voimme kerätä tietoja: laitteesi käyttöjärjestelmä, käyttämäsi selain, wevote4.eu-sivuilla vieraillut sivut, vierailusi lähde (esim. Google, Facebook), vierailusi päivämäärä ja kellonaika sekä verkkotunnus, josta käytät Internetiä. Kaikkia näitä tietoja käytetään verkkosivustomme navigointikokemuksen parantamiseen ja kävijöiden mieltymysten ymmärtämiseen. Emme kerää mitään henkilökohtaisia tietoja tämän verkkosivuston kautta ilman nimenomaista suostumustasi.',
    'line_1_1' => '- Keräämme sinulta tietoja, jos käytät tätä verkkosivustoa tavallisen selaimen kautta.
- Tämä verkkosivusto käyttää evästeitä (esim. Google Analytics) kaikkien käyttäjien kokemuksen mittaamiseen ja optimointiin.
- Commit Global ei luovuta tai myy henkilötietojasi kolmannelle osapuolelle lukuun ottamatta tässä tietosuojakäytännössä kuvattuja oikeudellisesti sitovia tilanteita.
- Commit Global ryhtyy kaikkiin kohtuullisiin toimenpiteisiin henkilötietojesi suojaamiseksi, koska tämä on meille suuri huolenaihe.',
    'line_6_3' => 'Evästeitä on kaikkialla, eikä niitä voida välttää, jos haluat käyttää joitain Internetin suurimmista ja parhaista verkkosivustoista, joko paikallisia tai kansainvälisiä. Selkeä ymmärrys evästeiden toiminnasta ja niiden tuomista eduista voit ryhtyä tarvittaviin turvatoimiin, jotta sinulla on aina turvallinen ja tyydyttävä selauskokemus.',
    'line_4_1' => 'Evästeet ovat yksi tärkeimmistä työkaluista saumattomaan ja tehokkaaseen Internet-kokemukseen, mikä auttaa luomaan ystävällisiä selauskokemuksia, jotka on räätälöity jokaisen käyttäjän tarpeisiin. Kieltäytyminen evästeiden hyväksymisestä tai niiden poistaminen käytöstä voi tehdä joidenkin verkkosivustojen käytön mahdottomaksi. Evästeiden hyväksymisen kieltäminen tai niiden poistaminen käytöstä ei tarkoita, että et enää saa verkkomainoksia, vaan ainoastaan sitä, että näissä mainoksissa ei enää oteta huomioon kiinnostuksen kohteitasi tai mieltymyksiäsi selauskäyttäytymisesi perusteella.',
    'intro_2' => 'wevote4.eu on Commit Globalin (”Commit Global”, ”me”, ”me”, ”meidän”) luoma verkkosivusto, jonka tarkoituksena on tiedottaa yleisölle Euroopan parlamentin vaaleista.',
    'line_2_2' => 'Google Analytics asettaa selaimeesi evästeen, jotta se voi tunnistaa sinut ainutlaatuisena kävijänä ja kerätä tietoja navigoinnistasi vastaavasti. Tätä evästettä käyttää yksinomaan Google, jota puolestaan rajoitetaan jakamasta ja käyttämästä näitä tietoja omilla Google Analyticsin käyttöehdoilla ja Googlen tietosuojakäytännöllä.',
    'intro_3' => 'Tässä tietosuojakäytännössä kuvataan, kuinka keräämme, käytämme ja suojaamme henkilökohtaisia tietojasi tällä verkkosivustolla. Lähettämällä henkilökohtaisia tietojasi tällä verkkosivustolla, hyväksyt tämän tietosuojakäytännön ehdot. Jos et hyväksy näitä ehtoja, älä käytä verkkosivustoamme.',
    'line_7_4' => 'Commit Global pidättää oikeuden tarkistaa ja päivittää tätä käytäntöä milloin tahansa, ilman ennakkoilmoitusta tai käyttäjien hyväksyntää. Jos sinulla on kysyttävää tämän sivun tiedoista, kirjoita meille osoitteeseen ',
    'subtitle_3' => 'Mitä ovat evästeet',
    'line_7_3' => 'Tämä käytäntö muodostaa kokonaisuudessaan sopimuksen sinun ja Commit Globalin välillä tämän sivuston käytöstä.',
    'line_6_2' => '- Muokkaa selaimesi evästeasetuksia mukavan suojaustason mahdollistamiseksi. Jos evästeet eivät ole sinulle ongelma ja olet ainoa henkilö, joka käyttää kyseistä laitetta, voit asettaa pitkät evästeiden säilytysvälit selaushistoriasi ja henkilökohtaisten käyttötietojesi tallentamiseksi.
- Jos jaat laitteen tai tietokoneen, saatat haluta määrittää selaimen poistamaan yksittäiset selaustietosi aina, kun se suljetaan. Tämä on yksi tapa käyttää verkkosivustoja, jotka asettavat evästeitä jaetulle tietokoneellesi ja poistavat kaikki selaustietosi istunnon sulkemisen yhteydessä.
- asenna vakoiluohjelmien torjuntasovellus ja pidä se ajan tasalla. Monet vakoiluohjelmien torjuntasovellukset sisältävät verkkosivustojen hyökkäysten havaitsemisen. Nämä sovellukset estävät selainta pääsemästä verkkosivustoihin, jotka saattavat hyödyntää selaimen haavoittuvuuksia tai ladata vaarallisia ohjelmistoja. Varmista, että selaimesi on ajan tasalla. Monet evästepohjaiset hyökkäykset hyödyntävät vanhojen selainversioiden heikkoja kohtia.',
    'subtitle_1' => 'Tiedonkeruu',
    'line_4_2' => 'Kieltäytyminen evästeiden hyväksymisestä tai niiden poistaminen käytöstä voi vaikeuttaa tai vaikeuttaa joidenkin verkkosivustojen navigointia tai käyttöä. Evästeiden hyväksymisen kieltäminen ei myöskään tarkoita sitä, että et enää saa verkkomainoksia.',
    'line_3_2' => 'Evästeet tallentavat tiedot pieneen tekstitiedostoon, jonka avulla verkkosivusto tunnistaa selaimen. Verkkopalvelin tunnistaa selaimen, kunnes eväste vanhenee tai se poistetaan. Eväste tallentaa tärkeitä tietoja, jotka parantavat selauskokemusta (esim. lahjoituksesi sarjanumero). Evästeet eivät pyydä henkilökohtaisia tietoja eivätkä tunnista Internetin käyttäjiä henkilökohtaisesti.',
    'line_4_4' => 'Nykyaikaiset selaimet tarjoavat mahdollisuuden muuttaa evästeasetuksia. Löydät evästeasetukset yleensä selaimesi ”asetukset” -välilehdestä tai ”Asetukset” -valikosta.',
    'subtitle_7' => 'Sinun oikeutesi',
];
