<?php
return [
    'intro_1' => 'Respeitamos sua privacidade e reconhecemos que devemos manter e usar suas informações com responsabilidade.',
    'title' => 'Política de privacidade',
    'intro_2' => 'wevote4.eu é um site criado pela Commit Global (“Commit Global”, “nós”, “nós”, “nosso”) com o objetivo de informar o público sobre as eleições europeias.',
    'line_7_5' => 'Esta versão dos Termos e Condições do wevotefor.eu entra em vigor a partir de 23 de maio de 2024. ',
    'subtitle_7' => 'Seus direitos',
    'line_6_1' => 'A desativação dos cookies não permitirá mais o acesso do usuário a alguns dos sites mais importantes, como Youtube, Gmail, Yahoo e outros. Aqui estão alguns conselhos que podem ajudar você a navegar com segurança e, ao mesmo tempo, manter os cookies:',
    'line_3_4' => 'Existem cookies que são usados exclusivamente para uma única sessão - eles não são mais armazenados depois que o usuário sai do site. Os cookies permanentes são armazenados e reutilizados sempre que o usuário retorna ao site, mas podem ser excluídos a qualquer momento pelo usuário.',
    'subtitle_4' => 'Como bloquear/desativar o uso de cookies',
    'subtitle_2' => 'Integrações de terceiros',
    'line_4_3' => 'Você pode configurar seu navegador para rejeitar cookies automaticamente ou selecionar apenas alguns sites em que os cookies estão ativados. Mas, por exemplo, se você desativar os cookies neste site, não poderá seguir com as próximas etapas no preenchimento do formulário.',
    'subtitle_6' => 'Conselhos para uma navegação segura e responsável baseada em cookies',
    'line_3_3' => '- Cookies de sessão - são cookies armazenados temporariamente no histórico do navegador, onde são armazenados até que o usuário saia desse site ou feche a janela do navegador.
- Cookies persistentes - São armazenados, por um período de tempo predeterminado, no disco rígido de um computador ou equipamento similar. Os cookies persistentes incluem aqueles colocados por um site diferente daquele que o usuário está visitando no momento, os chamados “cookies de terceiros” — que podem ser usados anonimamente para rastrear os interesses de um usuário — permitindo que ele receba anúncios mais relevantes aos seus interesses.',
    'line_3_1' => 'Um cookie (“cookie do navegador” ou “cookie HTTP”) é um pequeno arquivo, uma sucessão de letras e números, que é armazenado em qualquer terminal com acesso à Internet (computadores, telefones celulares, tablets etc.) e é instalado mediante solicitação de um servidor para um navegador (ex: Internet Explorer, Chrome). Os “cookies” não contêm nenhum programa de software, vírus ou spyware e não podem acessar informações no disco rígido do usuário. Um cookie consiste em um nome e conteúdo, sua duração de existência é limitada e pode ser acessado novamente pelo servidor da web quando um usuário retorna ao site associado a esse servidor.',
    'line_2_1' => 'A Commit Global usa o Google Analytics para entender melhor como os visitantes navegam em nosso site para melhorar sua experiência geral. O Google Analytics não coleta nenhuma informação identificável sobre seus visitantes e não processamos os dados coletados por meio de nossos formulários junto com os dados fornecidos pelo Google Analytics.',
    'line_5_1' => 'Pode haver situações em que, conforme exigido por lei, possamos ser solicitados a divulgar informações pessoais coletadas por meio deste site. Podemos acessar, preservar e divulgar suas informações, se solicitado, a fim de cumprir os requisitos de aplicação da lei e processos legais, como ordens judiciais ou se intimados, ou se isso puder proteger você ou os direitos, a propriedade ou a segurança geral de outras pessoas.',
    'line_1_2' => 'Ao visitar wevote4.eu, coletaremos e armazenaremos automaticamente dados sobre sua visita atual. Essas informações não são pessoalmente identificáveis. As informações que podemos coletar são: sistema operacional em seu dispositivo, o navegador que você está usando, páginas em wevote4.eu que você visitou, a fonte da sua visita (ex: Google, Facebook), data e hora da sua visita e o domínio a partir do qual você acessa a Internet. Todas essas informações são usadas para melhorar ainda mais a experiência de navegação em nosso site e para entender as preferências de nossos visitantes. Não coletaremos nenhuma informação pessoal por meio deste site sem o seu consentimento expresso.',
    'line_1_1' => '- Coletamos informações de você se você acessar este site por meio de um navegador comum.
- Este site usa cookies (ex: Google Analytics) para medir e otimizar a experiência de todos os usuários.
- A Commit Global não divulgará nem venderá seus dados pessoais a terceiros, exceto nas situações legalmente vinculativas descritas nesta Política de Privacidade.
- A Commit Global tomará todas as medidas razoáveis para proteger suas informações pessoais, pois essa é uma grande preocupação para nós.',
    'line_6_3' => 'Os cookies estão em toda parte e não podem ser evitados se você quiser acessar alguns dos maiores e melhores sites da Internet, locais ou internacionais. A compreensão clara da forma como os cookies funcionam e dos benefícios que eles trazem pode tomar as medidas de segurança necessárias para que você sempre tenha uma experiência de navegação segura e satisfatória.',
    'line_4_1' => 'Os cookies são uma das ferramentas mais importantes para uma experiência de Internet perfeita e eficiente, ajudando a gerar experiências de navegação amigáveis, adaptadas às necessidades de cada usuário. Recusar-se a aceitar cookies ou desativá-los pode impossibilitar o uso de alguns sites. Recusar-se a aceitar cookies ou desativá-los não significa que você não receberá mais anúncios on-line, apenas que esses anúncios não levarão mais em consideração seus interesses ou preferências, conforme determinado pelo seu comportamento de navegação.',
    'line_4_5' => 'Para obter mais informações gerais sobre cookies e como desativá-los, visite www.aboutcookies.org.',
    'line_2_2' => 'O Google Analytics colocará um cookie em seu navegador para identificá-lo como um visitante único e coletar informações sobre sua navegação adequadamente. Este cookie é usado exclusivamente pelo Google, que, por sua vez, está impedido de compartilhar e usar esses dados de acordo com seus próprios Termos de Uso do Google Analytics e Política de Privacidade do Google.',
    'intro_3' => 'Esta Política de Privacidade descreve como coletamos, usamos e protegemos suas informações pessoais neste site. Ao enviar suas informações pessoais neste site, você concorda com os termos desta Política de Privacidade. Se você não concordar com esses termos, não use nosso site.',
    'line_7_4' => 'A Commit Global se reserva o direito de revisar e atualizar esta política a qualquer momento, sem aviso prévio ou aceitação prévia dos usuários. Se você tiver alguma dúvida sobre as informações contidas nesta página, escreva para nós em ',
    'subtitle_5' => 'Compartilhamento de dados',
    'subtitle_3' => 'O que são cookies',
    'line_7_3' => 'Esta política constitui, em sua totalidade, um acordo celebrado entre você e a Commit Global em relação ao uso deste site.',
    'line_6_2' => '- Personalize as configurações de cookies do seu navegador para permitir um nível de segurança confortável. Se os cookies não forem um problema para você e você for a única pessoa usando esse dispositivo, poderá definir longos intervalos de retenção de cookies para armazenar seu histórico de navegação e seus dados pessoais de acesso.
- Se você compartilha o dispositivo ou o computador, convém configurar o navegador para excluir seus dados de navegação individuais sempre que ele for fechado. Essa é uma maneira de acessar sites que colocam cookies no seu computador compartilhado e, ao mesmo tempo, excluir todos os seus dados de navegação ao fechar a sessão.
- instale um aplicativo anti-spyware e mantenha-o atualizado. Muitos aplicativos anti-spyware incluem a detecção de ataques a sites. Esses aplicativos impedem que o navegador acesse sites que possam explorar as vulnerabilidades do navegador ou baixar softwares perigosos. Certifique-se de que seu navegador esteja atualizado. Muitos ataques baseados em cookies exploram os pontos fracos das versões antigas do navegador.',
    'subtitle_1' => 'Coleta de dados',
    'line_4_2' => 'Recusar-se a aceitar cookies ou desativá-los pode tornar alguns sites difíceis ou impossíveis de navegar ou usar. Recusar-se a aceitar cookies também não significa que você não receberá mais anúncios on-line.',
    'line_3_2' => 'Os cookies salvam informações em um pequeno arquivo de texto, permitindo que um site reconheça um navegador. O servidor web reconhecerá o navegador até que o cookie expire ou seja excluído. O cookie armazena informações importantes que melhoram a experiência de navegação (por exemplo, um número de série para sua doação). Os cookies não solicitam informações pessoais nem identificam pessoalmente os usuários da Internet.',
    'line_4_4' => 'Os navegadores modernos oferecem a capacidade de alterar as configurações de cookies. Normalmente, você pode encontrar as configurações de cookies na guia “opções” ou no menu “preferências” do seu navegador.',
    'line_7_1' => 'Como usuário do site wevote4.eu, você tem os seguintes direitos:',
    'line_7_2' => '- O direito à informação sobre o processamento de dados pessoais pela Commit Global;
- O direito de acessar dados pessoais, mediante solicitação e gratuitamente, por uma solicitação por ano;
- O direito de intervenção, retificação, exclusão ou portabilidade de dados pessoais, mediante solicitação e gratuitamente;
- O direito de se dirigir a qualquer autoridade competente em relação a questões de privacidade de dados relacionadas ao uso de seus dados pessoais
- O direito à oposição e o processo automatizado de tomada de decisão individual, bem como o direito de restringir o processamento.',
];
