<?php
return [
    'line_6_1' => 'A cookie-k kikapcsolása már nem teszi lehetővé a felhasználók hozzáférését néhány legfontosabb weboldalhoz, például a Youtube, a Gmail, a Yahoo és másokhoz. Íme néhány tanács, amely segíthet a biztonságos böngészésben a cookie-k megőrzése mellett:',
    'line_3_4' => 'Vannak olyan cookie-k, amelyeket kizárólag egyetlen munkamenetre használnak - ezeket már nem tárolják, miután a felhasználó elhagyta a weboldalt. Az állandó cookie-kat minden alkalommal tárolják és újra használják, amikor a felhasználó visszatér az adott weboldalra, de a felhasználó bármikor törölheti őket.',
    'line_7_1' => 'A wevote4.eu weboldal felhasználójaként Ön a következő jogokkal rendelkezik:',
    'line_4_3' => 'Beállíthatja böngészőjét úgy, hogy automatikusan elutasítsa a cookie-kat, vagy csak néhány olyan webhelyet választhat ki, ahol a cookie-k engedélyezve vannak. De, például, ha kikapcsolja a cookie-kat ezen a weboldalon, akkor nem tudja követni az űrlap kitöltésének következő lépéseit.',
    'subtitle_6' => 'Tanácsok a biztonságos és felelősségteljes cookie-alapú böngészéshez',
    'line_3_3' => '- Munkamenet sütik - olyan sütik, amelyek ideiglenesen tárolódnak a böngésző előzményeiben, ahol addig tárolódnak, amíg a felhasználó el nem hagyja a weboldalt, vagy bezárja a böngésző ablakát.
- Állandó cookie-k - Ezeket előre meghatározott ideig tárolják számítógépes merevlemezen vagy hasonló eszközön. Az állandó cookie-k közé tartoznak azok, amelyeket egy másik webhely helyez el, mint amelyet a felhasználó akkoriban meglátogat, úgynevezett „harmadik féltől származó cookie-k” - amelyek névtelenül használhatók a felhasználó érdeklődésének nyomon követésére -, amelyek lehetővé teszik számukra az érdeklődési körének megfelelő hirdetéseket kaphatnak.',
    'intro_1' => 'Tiszteletben tartjuk magánéletét, és elismerik, hogy adatait felelősségteljesen kell fenntartanunk és használnunk kell.',
    'line_3_1' => 'A süti („böngészősüti” vagy „HTTP cookie”) egy kis fájl, betűk és számok sorozata, amelyet bármely internet-hozzáféréssel rendelkező terminálon (számítógépek, mobiltelefonok, táblagépek stb.) tárolnak, és egy szerver kérésére egy böngészőre (pl. Internet Explorer, Chrome) telepítik. A „sütik” nem tartalmaznak szoftvereket, vírusokat vagy kémprogramokat, és nem férhetnek hozzá a felhasználó merevlemezén található információkhoz. A cookie egy névből és tartalomból áll, létezésének hossza korlátozott, és a webszerver ismét hozzáférhet hozzá, amikor a felhasználó visszatér az adott szerverhez társított weboldalra.',
    'line_2_1' => 'A Commit Global a Google Analytics-t használja annak érdekében, hogy jobban megértse, hogyan navigálnak a látogatók weboldalunkon, hogy javítsák általános élményüket. A Google Analytics nem gyűjt semmilyen azonosítható információt a látogatóiról, és nem dolgozzuk fel az űrlapunkon gyűjtött adatokat a Google Analytics által biztosított adatokkal együtt.',
    'subtitle_2' => 'Harmadik fél integrációja',
    'subtitle_4' => 'A cookie-k használatának letiltása/letiltása',
    'line_7_5' => 'A wevotefor.eu Általános Szerződési Feltételek ezen változata 2024. május 23-tól lép hatályba. ',
    'subtitle_7' => 'Az Ön jogai',
    'line_5_1' => 'Előfordulhatnak olyan helyzetek, amikor a törvény előírja szerint a weboldalon gyűjtött személyes adatok közzétételére kérhetünk tőlünk. Hozzáférhetjük, megőrizzük és közölhetjük az Ön adatait, ha a bűnüldözési követelményeknek és jogi eljárásoknak való megfelelés érdekében kérjük, például bírósági végzéseknek vagy idézés esetén, vagy ha ez megvédi Önt vagy mások jogait, tulajdonát vagy általános biztonságát.',
    'line_1_2' => 'A wevote4.eu meglátogatásakor automatikusan adatokat gyűjtünk és tárolunk az aktuális látogatásáról. Ez az információ nem személyazonosítható. Az általunk gyűjtött információk a következők: az Ön eszközén található operációs rendszer, az Ön által használt böngésző, a wevote4.eu oldalai, amelyeket meglátogatott, látogatásának forrása (pl.: Google, Facebook), látogatásának dátuma és időpontja, valamint a domain, ahonnan Ön hozzáférhet az internethez. Mindezeket az információkat arra használjuk fel, hogy tovább javítsuk weboldalunkon a navigációs élményt, és megértsük látogatóink preferenciáit. Ezen a weboldalon keresztül az Ön kifejezett hozzájárulása nélkül nem gyűjtünk személyes adatokat.',
    'title' => 'Adatvédelmi szabályzat',
    'line_1_1' => '- Adatokat gyűjtünk Öntől, ha rendszeres böngészőn keresztül fér hozzá ehhez a weboldalhoz.
- Ez a weboldal sütiket (pl. Google Analytics) használ az élmény mérésére és optimalizálására minden felhasználó számára.
- A Commit Global nem adja át vagy adja el személyes adatait harmadik félnek, kivéve a jelen Adatvédelmi Szabályzatban leírt jogilag kötelező erejű helyzeteket.
- A Commit Global minden ésszerű intézkedést megtesz az Ön személyes adatainak védelme érdekében, mivel ez komoly aggodalomra ad okot számunkra.',
    'line_6_3' => 'A cookie-k mindenütt megtalálhatók, és nem kerülhetők el, ha az internet legnagyobb és legjobb webhelyeit szeretné elérni, akár helyi, akár nemzetközi. A sütik működésének és az általuk nyújtott előnyök egyértelmű megértése megteheti a szükséges biztonsági intézkedéseket annak érdekében, hogy Ön mindig biztonságos és kielégítő böngészési élményt nyújtson.',
    'line_4_1' => 'A cookie-k az egyik legfontosabb eszköz a zökkenőmentes, hatékony internetes élmény eléréséhez, amelyek segítenek minden felhasználó igényeihez igazított barátságos böngészési élmény létrehozásában. A cookie-k elfogadásának megtagadása vagy kikapcsolása egyes webhelyek használatát lehetetlenné teheti. A cookie-k elfogadásának megtagadása vagy azok kikapcsolása nem jelenti azt, hogy már nem fog online hirdetéseket kapni, csupán azt, hogy ezek a hirdetések már nem veszik figyelembe az Ön érdeklődési körét vagy preferenciáit, amelyeket böngészési magatartása határoz meg.',
    'intro_2' => 'A wevote4.eu egy weboldal, amelyet a Commit Global („Commit Global”, „mi”, „mi”, „miénk”) hozott létre azzal a céllal, hogy tájékoztassa a nyilvánosságot az európai választásokról.',
    'line_7_2' => '- A személyes adatok Commit Global általi feldolgozásával kapcsolatos tájékoztatáshoz való jog;
- a személyes adatokhoz való hozzáférés joga, kérésre és díjmentesen, évente egy kérelem esetén;
- a személyes adatok beavatkozásához, helyesbítéséhez, törléséhez vagy hordozhatósághoz való jog kérésre és ingyenesen;
- Az Ön személyes adatainak felhasználásával összefüggő adatvédelmi kérdésekkel kapcsolatban bármely illetékes hatósághoz fordulni
- A felszólaláshoz való jog és az automatizált egyéni döntéshozatali folyamat, valamint az adatkezelés korlátozásának joga.',
    'line_4_5' => 'A cookie-kkal kapcsolatos általános információkért és azok kikapcsolásának módjáról a www.aboutcookies.org webhelyen talál.',
    'line_2_2' => 'A Google Analytics sütit helyez el a böngészőjében annak érdekében, hogy egyedi látogatóként azonosítsa Önt, és ennek megfelelően gyűjtse az Ön navigációjáról szóló információkat. Ezt a sütit kizárólag a Google használja, aki viszont a Google Analytics felhasználási feltételei és a Google Adatvédelmi szabályzata korlátozza ezen adatok megosztását és felhasználását.',
    'intro_3' => 'Ez az Adatvédelmi Szabályzat leírja, hogyan gyűjtjük, használjuk és védjük személyes adatait ezen a weboldalon. Személyes adatainak ezen a weboldalon történő elküldésével elfogadja a jelen Adatvédelmi Szabályzat feltételeit. Ha nem ért egyet ezekkel a feltételekkel, kérjük, ne használja weboldalunkat.',
    'line_7_4' => 'A Commit Global fenntartja magának a jogot, hogy bármikor felülvizsgálja és frissítse ezt a szabályzatot, a felhasználók értesítése vagy előzetes elfogadása nélkül. Ha bármilyen kérdése van az ezen az oldalon található információkkal kapcsolatban, kérjük, írjon nekünk a következő címen ',
    'subtitle_5' => 'Adatmegosztás',
    'subtitle_3' => 'Mik azok a cookie-k',
    'line_7_3' => 'Ez a szabályzat teljes egészében az Ön és a Commit Global között létrejött megállapodást jelent a weboldal használatáról.',
    'line_6_2' => '- Testreszabhatja böngészője cookie-beállításait a kényelmes biztonsági szint érdekében. Ha a cookie-k nem jelentenek problémát az Ön számára, és Ön az egyetlen személy használja ezt az eszközt, akkor hosszú cookie-megőrzési intervallumokat állíthat be böngészési előzményeinek és személyes hozzáférési adatainak tárolása érdekében.
- Ha megosztja az eszközt vagy számítógépet, érdemes beállítani a böngészőt úgy, hogy minden egyes bezáráskor törölje az egyes böngészési adatokat. Ez az egyik módja annak, hogy elérje azokat a webhelyeket, amelyek cookie-kat helyeznek el a megosztott számítógépén, miközben törlik az összes böngészési adatot a munkamenet bezárásakor.
- telepítsen egy kémprogram-ellenes alkalmazást, és tartsa naprakészen. Számos kémprogram-ellenes alkalmazás tartalmazza a webhelytámadások észlelését. Ezek az alkalmazások megakadályozzák, hogy a böngésző hozzáférjen olyan webhelyekhez, amelyek kihasználhatják a böngésző biztonsági réseit, vagy veszélyes szoftvereket tölthetnek le Győződjön meg róla, hogy böngészője napra Számos cookie-alapú támadás kihasználja a régi böngészőverziók gyenge pontjait.',
    'subtitle_1' => 'Adatgyűjtés',
    'line_4_2' => 'A cookie-k elfogadásának megtagadása vagy azok kikapcsolása egyes weboldalak navigálását vagy használatát megnehezítheti vagy lehetetlenné teheti. A cookie-k elfogadásának megtagadása nem jelenti azt sem, hogy többé nem fog online hirdetéseket kapni.',
    'line_3_2' => 'A cookie-k egy kis szöveges fájlban tárolják az információkat, amelyek lehetővé teszik a webhely számára, hogy felismerje a böngészőt. A webszerver felismeri a böngészőt addig, amíg a süti lejár vagy törlődik. A cookie fontos információkat tárol, amelyek javítják a böngészési élményt (pl. az adomány sorozatszámát). A cookie-k nem kérnek személyes adatokat, és nem azonosítják személyesen az internetes felhasználókat.',
    'line_4_4' => 'A modern böngészők lehetőséget nyújtanak a cookie-beállítások megváltoztatására. A cookie-beállításokat általában a böngészője „Beállítások” lapján vagy a „Beállítások” menüjében találja meg.',
];
