<?php
return [
    'subtitle_2' => 'Integrationer från tredje part',
    'intro_1' => 'Vi respekterar din integritet och inser att vi måste behålla och använda din information på ett ansvarsfullt sätt.',
    'line_2_1' => 'Commit Global använder Google Analytics för att bättre förstå hur besökare navigerar på vår webbplats för att förbättra sin övergripande upplevelse. Google Analytics samlar inte in någon identifierbar information om sina besökare och vi behandlar inte de uppgifter som samlas in via våra formulär tillsammans med de uppgifter som tillhandahålls av Google Analytics.',
    'title' => 'Sekretesspolicy',
    'line_1_1' => '- Vi samlar in information från dig om du besöker denna webbplats via en vanlig webbläsare.
- Denna webbplats använder cookies (ex: Google Analytics) för att mäta och optimera upplevelsen för alla användare.
- Commit Global kommer inte att avslöja eller sälja dina personuppgifter till någon tredje part, förutom de juridiskt bindande situationer som beskrivs i denna sekretesspolicy.
- Commit Global kommer att vidta alla rimliga åtgärder för att skydda din personliga information eftersom detta är ett stort problem för oss.',
    'line_6_1' => 'Inaktivering av cookies tillåter inte längre användaren åtkomst till några av de viktigaste webbplatserna som Youtube, Gmail, Yahoo och andra. Här är några råd som kan hjälpa dig att surfa säkert samtidigt som du behåller cookies:',
    'line_3_4' => 'Det finns cookies som endast används för en enda session - dessa lagras inte längre efter att användaren har lämnat webbplatsen. Permanenta cookies lagras och återanvänds varje gång användaren återvänder till webbplatsen men kan raderas när som helst av användaren.',
    'subtitle_4' => 'Hur man blockerar/väljer bort användning av cookies',
    'line_4_3' => 'Du kan ställa in din webbläsare för att avvisa cookies automatiskt eller så kan du bara välja vissa webbplatser där cookies är aktiverade. Men, till exempel, om du stänger av cookies på den här webbplatsen kan du inte följa med nästa steg i att fylla i formuläret.',
    'subtitle_6' => 'Råd för säker och ansvarsfull cookie-baserad surfning',
    'line_3_3' => '- Session cookies - är cookies som tillfälligt lagras i webbläsarens historik där de lagras tills användaren lämnar webbplatsen eller stänger webbläsarfönstret.
- Beständiga cookies - Dessa lagras, under en förutbestämd tid, på en dators hårddisk eller liknande utrustning. Beständiga cookies inkluderar de som placeras av en annan webbplats än den som användaren besöker vid den tidpunkten, så kallade ”tredjepartscookies” - som kan användas anonymt för att spåra en användares intressen - så att de kan få annonser som är mer relevanta för deras intressen.',
    'line_7_5' => 'Denna version av wevotefor.eu regler och villkor gäller från och med den 23 maj 2024. ',
    'line_7_4' => 'Commit Global förbehåller sig rätten att revidera och uppdatera denna policy när som helst, utan föregående meddelande eller godkännande av användarna. Om du har några frågor angående informationen på denna sida, skriv till oss på ',
    'line_3_1' => 'En cookie (”webbläsarcookie” eller ”HTTP-cookie”) är en liten fil, en följd av bokstäver och siffror, som lagras på vilken terminal som helst med internetåtkomst (datorer, mobiltelefoner, surfplattor etc.) och installeras på begäran från en server till en webbläsare (t.ex. Internet Explorer, Chrome). ”Cookies” innehåller inga program, virus eller spionprogram och kan inte komma åt information på användarens hårddisk. En cookie består av ett namn och innehåll, längden på dess existens är begränsad och den kan nås igen av webbservern när en användare återvänder till webbplatsen som är associerad med den servern.',
    'line_5_1' => 'Det kan finnas situationer där vi, enligt vad som krävs enligt lag, kan bli ombedda att avslöja personlig information som samlats in via denna webbplats. Vi kan komma åt, bevara och avslöja din information om så begärs för att uppfylla brottsbekämpande krav och rättsliga processer, till exempel domstolsbeslut eller om det stämts, eller om detta kan skydda dig eller andras rättigheter, egendom eller allmänna säkerhet.',
    'line_1_2' => 'När du besöker wevote4.eu samlar vi automatiskt in och lagrar uppgifter om ditt aktuella besök. Denna information är inte personligt identifierbar. Den information vi kan samla in är: operativsystem på din enhet, webbläsaren du använder, sidor i wevote4.eu du har besökt, källan till ditt besök (t.ex. Google, Facebook), datum och tid för ditt besök och domänen från vilken du får tillgång till internet. All denna information används för att ytterligare förbättra navigeringsupplevelsen på vår webbplats och för att förstå våra besökares preferenser. Vi samlar inte in någon personlig information via denna webbplats utan ditt uttryckliga medgivande.',
    'line_6_3' => 'Cookies finns överallt och kan inte undvikas om du vill komma åt några av de största och bästa webbplatserna på internet, antingen lokala eller internationella. Den tydliga förståelsen av hur cookies fungerar och de fördelar de ger dig kan vidta nödvändiga säkerhetsåtgärder så att du alltid har en säker och tillfredsställande surfupplevelse.',
    'line_4_1' => 'Cookies är ett av de viktigaste verktygen för en sömlös, effektiv internetupplevelse och hjälper till att skapa vänliga surfupplevelser skräddarsydda för varje användares behov. Att vägra acceptera cookies eller inaktivera dem kan göra vissa webbplatser omöjliga att använda. Att vägra acceptera cookies eller inaktivera dem betyder inte att du inte längre kommer att få onlineannonser, bara att dessa annonser inte längre tar hänsyn till dina intressen eller preferenser som bestäms av ditt surfbeteende.',
    'intro_2' => 'wevote4.eu är en webbplats skapad av Commit Global (”Commit Global”, ”vi”, ”oss”, ”vår”) i syfte att informera allmänheten om valet till Europaparlamentet.',
    'line_4_5' => 'För mer allmän information om cookies och hur du inaktiverar dem kan du besöka www.aboutcookies.org.',
    'line_2_2' => 'Google Analytics placerar en cookie i din webbläsare för att den ska kunna identifiera dig som en unik besökare och för att samla in information om din navigering i enlighet med detta. Denna cookie används uteslutande av Google som i sin tur är begränsad från att dela och använda dessa data genom sina egna användarvillkor för Google Analytics och Googles sekretesspolicy.',
    'intro_3' => 'Denna sekretesspolicy beskriver hur vi samlar in, använder och skyddar din personliga information på denna webbplats. Genom att skicka in din personliga information på denna webbplats godkänner du villkoren i denna sekretesspolicy. Om du inte godkänner dessa villkor, använd inte vår webbplats.',
    'subtitle_5' => 'Datadelning',
    'subtitle_3' => 'Vad är cookies',
    'line_7_3' => 'Denna policy utgör, i sin helhet, ett avtal som ingåtts mellan dig och Commit Global angående användningen av denna webbplats.',
    'line_6_2' => '- Anpassa din webbläsares cookie-inställningar för att möjliggöra en bekväm säkerhetsnivå. Om cookies inte är ett problem för dig och du är den enda personen som använder den enheten kan du ställa in långa lagringsintervall för cookies för att lagra din webbhistorik och dina personliga åtkomstdata.
- Om du delar enheten eller datorn kanske du vill ställa in webbläsaren så att den raderar dina individuella webbläsardata varje gång den stängs. Detta är ett sätt att komma åt webbplatser som placerar cookies på din delade dator samtidigt som du raderar all din surfdata när du stänger sessionen.
- installera en anti-spyware app och hålla den uppdaterad. Många anti-spionprogram inkluderar upptäckt av webbplatsattacker. Dessa appar hindrar webbläsaren från att komma åt webbplatser som kan utnyttja webbläsarens sårbarheter eller ladda ner farlig programvara. Se till att din webbläsare är uppdaterad. Många cookie-baserade attacker utnyttjar svaga punkter i gamla webbläsarversioner.',
    'subtitle_1' => 'Datainsamling',
    'line_4_2' => 'Att vägra acceptera cookies eller inaktivera dem kan göra vissa webbplatser svåra eller omöjliga att navigera eller använda. Att vägra att acceptera cookies betyder inte heller att du inte längre kommer att få onlineannonser.',
    'line_3_2' => 'Cookies sparar information i en liten textfil så att en webbplats kan känna igen en webbläsare. Webbservern känner igen webbläsaren tills cookien löper ut eller raderas. Cookien lagrar viktig information som förbättrar surfupplevelsen (t.ex. ett serienummer för din donation). Cookies begär inte personlig information och identifierar inte heller internetanvändare personligen.',
    'line_4_4' => 'Moderna webbläsare erbjuder möjligheten att ändra cookieinställningar. Du kan vanligtvis hitta cookieinställningar under fliken ”alternativ” eller ”inställningar” -menyn i din webbläsare.',
    'subtitle_7' => 'Dina rättigheter',
    'line_7_1' => 'Som användare av webbplatsen wevote4.eu har du följande rättigheter:',
    'line_7_2' => '- Rätten till information om Commit Globals behandling av personuppgifter;
- Rätten att få tillgång till personuppgifter, på begäran och kostnadsfritt för en begäran per år;
- Rätten till ingripande, rättelse, radering eller överföring av personuppgifter, på begäran och kostnadsfritt;
- Rätten att vända sig till en behörig myndighet angående dataskyddsfrågor i samband med användningen av dina personuppgifter
- Rätten till invändning och den automatiska individuella beslutsprocessen samt rätten att begränsa behandlingen.',
];
