<?php
return [
    'line_4_4' => 'Šiuolaikinės naršyklės siūlo galimybę keisti slapukų nustatymus. Paprastai slapukų nustatymus galite rasti skirtuke “parinktys” arba naršyklės meniu “nuostatos”.',
    'subtitle_7' => 'Jūsų teisės',
    'title' => 'Privatumo politika',
    'line_6_1' => 'Slapukų išjungimas nebeleis naudotojui patekti į kai kurias svarbiausias svetaines, tokias kaip “Youtube”, “Gmail”, “Yahoo” ir kt. Štai keletas patarimų, kurie gali padėti saugiai naršyti išlaikant slapukus:',
    'line_7_5' => 'Ši wevotefor.eu sąlygų versija įsigalioja nuo 2024 m. gegužės 23 d. ',
    'subtitle_6' => 'Patarimai saugiam ir atsakingam naršymui slapukais',
    'line_5_1' => 'Gali būti situacijų, kai, kaip to reikalauja įstatymai, mūsų gali būti paprašyta atskleisti asmeninę informaciją, surinktą per šią svetainę. Mes galime pasiekti, išsaugoti ir atskleisti jūsų informaciją, jei to prašoma, kad būtų laikomasi teisėsaugos reikalavimų ir teisinių procesų, pvz., teismo nutarčių arba jei jie bus šaukti, arba jei tai gali apsaugoti jūsų ar kito asmens teises, nuosavybę ar bendrą saugumą.',
    'line_4_5' => 'Norėdami gauti daugiau bendros informacijos apie slapukus ir kaip juos išjungti, galite apsilankyti www.aboutcookies.org.',
    'subtitle_5' => 'Duomenų dalijimasis',
    'line_3_4' => 'Yra slapukų, kurie naudojami tik vienai sesijai - jie nebėra saugomi vartotojui išėjus iš svetainės. Nuolatiniai slapukai yra saugomi ir pakartotinai naudojami kiekvieną kartą, kai vartotojas grįžta į tą svetainę, tačiau vartotojas gali juos bet kada ištrinti.',
    'subtitle_4' => 'Kaip blokuoti/atsisakyti naudoti slapukus',
    'subtitle_2' => 'Trečiųjų šalių integracija',
    'line_4_3' => 'Galite nustatyti, kad naršyklė automatiškai atmestų slapukus arba galite pasirinkti tik kai kurias svetaines, kuriose įgalinti slapukai. Bet, pavyzdžiui, jei išjungiate slapukus šioje svetainėje, jūs negalite sekti per su kitais žingsniais pildant formą.',
    'line_3_3' => '- Sesijos slapukai - tai slapukai, laikinai saugomi naršyklės istorijoje, kur jie saugomi tol, kol vartotojas palieka tą svetainę arba uždaro naršyklės langą.
- Nuolatiniai slapukai - jie iš anksto nustatytą laiką saugomi kompiuterio kietajame diske ar panašioje įrangoje. Nuolatiniai slapukai apima slapukus, kuriuos patalpina kita svetainė nei ta, kurioje tuo metu lankosi vartotojas, vadinamieji “trečiųjų šalių slapukai”, kurie gali būti anonimiškai naudojami vartotojo pomėgiams sekti, leidžiančius gauti skelbimus, labiau atitinkančius jo interesus.',
    'intro_1' => 'Mes gerbiame jūsų privatumą ir pripažįstame, kad privalome saugoti ir naudoti jūsų informaciją atsakingai.',
    'line_3_1' => 'Slapukas (“naršyklės slapukas” arba “HTTP slapukas”) yra nedidelis failas, raidžių ir skaičių eilės, kuris yra saugomas bet kuriame terminale, turinčiame prieigą prie interneto (kompiuteriuose, mobiliuosiuose telefonuose, planšetiniuose kompiuteriuose ir kt.) ir įdiegiamas gavus serverio prašymą į naršyklę (pvz.: “Internet Explorer”, “Chrome”). “Slapukuose” nėra jokių programinės įrangos programų, virusų ar šnipinėjimo programų ir jie negali pasiekti informacijos vartotojo kietajame diske. Slapuką sudaro vardas ir turinys, jo egzistavimo trukmė yra ribota, o interneto serveris jį vėl gali pasiekti, kai vartotojas grįžta į su tuo serveriu susietą svetainę.',
    'line_2_1' => '“Commit Global” naudoja “Google Analytics”, kad geriau suprastų, kaip lankytojai naršo mūsų svetainėje, kad pagerintų bendrą savo patirtį. “Google Analytics” nerenka jokios identifikuojamos informacijos apie savo lankytojus ir mes netvarkome duomenų, surinktų naudojant mūsų formas, kartu su “Google Analytics” pateiktais duomenimis.',
    'line_1_2' => 'Apsilankę wevote4.eu mes automatiškai rinksime ir saugosime duomenis apie jūsų dabartinį apsilankymą. Ši informacija nėra asmens tapatybė. Informacija, kurią galime rinkti, yra: jūsų įrenginio operacinė sistema, jūsų naudojama naršyklė, svetainės wevote4.eu puslapiai, kuriuose lankėtės, jūsų apsilankymo šaltinis (pvz.: “Google”, “Facebook”), apsilankymo data ir laikas bei domenas, iš kurio naudojatės internetu. Visa ši informacija naudojama siekiant toliau pagerinti naršymo patirtį mūsų svetainėje ir suprasti mūsų lankytojų pageidavimus. Mes nerinksime jokios asmeninės informacijos per šią svetainę be aiškaus jūsų sutikimo.',
    'line_1_1' => '- Mes renkame informaciją iš jūsų, jei jūs pasiekiate šią svetainę per įprastą naršyklę.
- Ši svetainė naudoja slapukus (pvz.: “Google Analytics”), kad matuotų ir optimizuotų visų vartotojų patirtį.
- “Commit Global” neatskleis ir neparduos jūsų asmens duomenų jokiai trečiajai šaliai, išskyrus teisiškai privalomas situacijas, aprašytas šioje privatumo politikoje.
- “Commit Global” imsis visų pagrįstų priemonių, kad apsaugotų jūsų asmeninę informaciją, nes tai mums kelia didelį susirūpinimą.',
    'line_6_3' => 'Slapukų yra visur ir jų negalima išvengti, jei norite pasiekti kai kurias didžiausias ir geriausias interneto svetaines, tiek vietines, tiek tarptautines. Aiškiai suprantant slapukų veikimo būdą ir jų teikiamą naudą galite imtis būtinų saugumo priemonių, kad visada turėtumėte saugų ir patenkinamą naršymo patirtį.',
    'line_4_1' => 'Slapukai yra viena svarbiausių vientisos, efektyvios interneto patirties įrankių, padedančių generuoti draugišką naršymo patirtį, pritaikytą kiekvieno vartotojo poreikiams. Atsisakius priimti slapukus arba juos išjungus, kai kurių svetainių naudojimas gali tapti neįmanomas. Atsisakymas priimti slapukus arba jų išjungimas nereiškia, kad nebegausite internetinių skelbimų, tik kad šiuose skelbimuose nebebus atsižvelgiama į jūsų pomėgius ar nuostatas, kurias lemia jūsų naršymo elgesys.',
    'intro_2' => 'wevote4.eu yra Commit Global (“Commit Global”, “mes”, “mus”, “mūsų”) sukurta svetainė su tikslu informuoti visuomenę apie Europos Parlamento rinkimus.',
    'line_2_2' => '“Google Analytics” įdės slapuką jūsų naršyklėje tam, kad jis identifikuotų jus kaip unikalų lankytoją ir atitinkamai rinktų informaciją apie jūsų navigaciją. Šį slapuką naudoja tik “Google”, kuriai savo “Google Analytics” naudojimo sąlygos ir “Google” privatumo politika draudžiama dalytis ir naudoti šiuos duomenis.',
    'intro_3' => 'Šioje privatumo politikoje aprašoma, kaip renkame, naudojame ir saugome jūsų asmeninę informaciją šioje svetainėje. Pateikdami savo asmeninę informaciją šioje svetainėje, jūs sutinkate su šioje privatumo politikoje pateiktomis sąlygomis. Jei nesutinkate su šiomis sąlygomis, prašome nesinaudoti mūsų svetaine.',
    'line_7_4' => '“Commit Global” pasilieka teisę bet kuriuo metu peržiūrėti ir atnaujinti šią politiką be išankstinio vartotojų įspėjimo ar sutikimo. Jei turite klausimų dėl šiame puslapyje pateiktos informacijos, parašykite mums adresu ',
    'subtitle_3' => 'Kas yra slapukai',
    'line_7_3' => 'Visa ši politika yra jūsų ir “Commit Global” sudarytas susitarimas dėl šios svetainės naudojimo.',
    'line_6_2' => '- Tinkinkite savo naršyklės slapukų nustatymus, kad būtų užtikrintas patogus saugumo lygis. Jei slapukai jums nekelia problemų ir jūs esate vienintelis asmuo, naudojantis tuo įrenginiu, galite nustatyti ilgus slapukų saugojimo intervalus, kad būtų išsaugota jūsų naršymo istorija ir jūsų asmeninės prieigos duomenys.
- Jei bendrinate įrenginį ar kompiuterį galbūt norėsite nustatyti naršyklę ištrinti savo atskirus naršymo duomenis kiekvieną kartą, kai jis uždarytas. Tai yra vienas iš būdų pasiekti svetaines, kurios talpina slapukus į jūsų bendrinamą kompiuterį, tuo pačiu ištrinant visus jūsų naršymo duomenis uždarant sesiją.
- įdiekite antišnipinėjimo programą ir nuolat ją atnaujinkite. Daugelis kovos su šnipinėjimo programomis programų apima svetainės atakų aptikimą. Šios programos neleidžia naršyklei pasiekti svetainių, kurios gali išnaudoti naršyklės pažeidžiamumą, arba atsisiųsti pavojingą programinę įrangą. Įsitikinkite, kad jūsų naršyklė yra atnaujinta. Daugelis slapukais pagrįstų atakų išnaudoja senų naršyklių versijų silpnąsias vietas.',
    'subtitle_1' => 'Duomenų rinkimas',
    'line_4_2' => 'Atsisakius priimti slapukus arba juos išjungus, kai kuriose svetainėse naršymas ar naudojimas gali būti sudėtingas arba neįmanomas. Atsisakymas priimti slapukus taip pat nereiškia, kad nebegausite internetinių skelbimų.',
    'line_3_2' => 'Slapukai išsaugo informaciją mažame tekstiniame faile, leidžiančiame svetainei atpažinti naršyklę. Žiniatinklio serveris atpažins naršyklę tol, kol slapukas pasibaigs arba bus ištrintas. Slapukas saugo svarbią informaciją, kuri pagerina naršymo patirtį (pvz., jūsų aukos serijos numeris). Slapukai neprašo asmeninės informacijos ir asmeniškai neidentifikuoja interneto vartotojų.',
    'line_7_1' => 'Kaip wevote4.eu svetainės naudotojas turite šias teises:',
    'line_7_2' => '- Teisė į informaciją apie “Commit Global” vykdomą asmens duomenų tvarkymą;
- Teisė susipažinti su asmens duomenimis, paprašius ir nemokamai už vieną prašymą per metus;
- Asmens duomenų įsikišimo, ištaisymo, ištrynimo ar perkeliamumo teisė, gavus prašymą ir nemokamai;
- Teisė kreiptis į bet kurią kompetentingą instituciją dėl duomenų privatumo klausimų, susijusių su jūsų asmens duomenų naudojimu
- Teisė į protestą ir automatizuotas individualaus sprendimų priėmimo procesas, taip pat teisė apriboti duomenų tvarkymą.',
];
