<?php
return [
    'title' => 'Proje Hakkında',
    'line_1' => 'Avrupa Birliği\'nde 400 milyondan fazla vatandaşı birleştiren tek, canlı bir seçim etkinliği hayal edin. AB seçimleri sadece bir dizi ulusal oy değil, ortak kimliğimizin ve demokratik değerlerimizin toplu bir kutlamasıdır. AB vatandaşları olarak, ortak geleceğimizi şekillendirmek, sınırları aşmak ve çeşitliliğimizin gücünü kucaklamak için bir araya geliyoruz. Bu proje birliğimizin bir kanıtıdır ve AB\'nin neresinde olursa olsun her vatandaşın bu güçlü demokratik sürece katılmasını kolaylaştırıyor.',
    'line_2' => 'Bu birleşik seçim süreci vizyonunu desteklemek için Commit Global, birlik ve işbirliği fikrini somutlaştıran **AB için Oy verme** adlı bir platform oluşturdu. Bu platform, tüm AB vatandaşlarına, bulundukları yer ne olursa olsun, oylarını nasıl kullanacakları ve sandık merkezlerini hızlı bir şekilde bulabilecekleri konusunda temel bilgiler sağlar.',
    'subtitle' => 'Bu platformu özel kılan nedir?',
    'line_3' => '**Karar Ağacı Biçimi: ** Platform, AB vatandaşlarını doğrudan ihtiyaç duydukları belirli bilgilere yönlendiren bir karar ağacı biçimi kullanır.',
    'line_4' => '**Kapsamlı Bilgi: ** Sağlanan nihai bilgiler kapsamlıdır ve kayıt gerekliliklerini (varsa), farklı oylama yöntemlerini (vekalet, çevrimiçi, posta, sandık merkezi), oylama için gerekli belgeleri ve engelli veya diğer sınırlamaları olan seçmenler için yardımı kapsar.',
    'line_5' => '**Doğrulanmış Bilgiler: ** Web sitesinde sunulan bilgiler, oylama kuralları ve prosedürlerinden sorumlu ulusal bakanlıklar ve kuruluşların yanı sıra Avrupa Parlamentosu platformu da dahil olmak üzere birçok farklı kaynaktan çapraz kontrol edilir.',
    'line_6' => '**Çok Dilli Erişilebilirlik: ** Her AB vatandaşının ihtiyaç duydukları bilgilere kendi dillerinde erişebilmesini sağlıyoruz. Platform 26 dilde mevcuttur ve her ülkenin karar ağacı resmi dil (ler) inde ve İngilizce olarak sağlanır. Bu, dilsel geçmişi ne olursa olsun herkesin oylama sürecinde zahmetsizce gezinebilmesini sağlar.',
    'line_7' => '**Bağlantılı Rehberlik: ** Seçmenin AB uyruğu, ikamet ettiği ülke veya seçim gününde bulunduğu yer ne olursa olsun, platform, benzersiz durumlarıyla ilgili kesin, özel talimatlar ve bilgiler sağlar. Süreci sorunsuz ve ilham verici hale getiren kişiselleştirilmiş bir oylama asistanına sahip olmak gibi.',
    'line_8' => 'AB için Oy Veriyoruz, dünyanın ilk küresel sivil teknoloji STK\'sı olan **Commit Global** tarafından oluşturulan ve yönetilen bir platformdur. Genel merkezi Lahey\'de (Hollanda) bulunan Commit Global, kritik dijital, ** İyi için Altyapı**, sivil toplum kuruluşlarına ve etkilenen nüfuslara ücretsiz erişim sağlamaktadır, sürdürür ve sağlar. Çalışmalarımız hakkında daha fazla bilgi için lütfen [web sitemizi] ziyaret edin (https://www.commitglobal.org).',
];
