<?php
return [
    'title' => 'Gizlilik Politikası',
    'intro_1' => 'Gizliliğinize saygı duyuyoruz ve bilgilerinizi sorumlu bir şekilde korumamız ve kullanmamız gerektiğini kabul ediyoruz.',
    'intro_2' => 'wevote4.eu, Avrupa seçimleri hakkında halkı bilgilendirmek amacıyla Commit Global (“Commit Global”, “we”, “us”, “our”) tarafından oluşturulan bir web sitesidir.',
    'intro_3' => 'Bu Gizlilik Politikası, bu web sitesinde kişisel bilgilerinizi nasıl topladığımızı, kullandığımızı ve koruduğumuzu açıklar. Kişisel bilgilerinizi bu web sitesine göndererek, bu Gizlilik Politikasındaki şartları kabul ediyorsunuz. Bu şartları kabul etmiyorsanız, lütfen web sitemizi kullanmayın.',
    'subtitle_1' => 'Veri toplama',
    'line_1_1' => '- Bu web sitesine normal bir tarayıcı aracılığıyla erişmeniz durumunda sizden bilgi toplarız.
- Bu web sitesi, tüm kullanıcılar için deneyimi ölçmek ve optimize etmek için çerezleri (örn. Google Analytics) kullanır.
- Commit Global, bu Gizlilik Politikasında açıklanan yasal olarak bağlayıcı durumlar dışında kişisel verilerinizi herhangi bir üçüncü tarafa ifşa etmeyecek veya satmayacaktır.
- Commit Global, kişisel bilgilerinizi korumak için tüm makul önlemleri alacaktır çünkü bu bizim için büyük bir endişe kaynağıdır.',
    'line_1_2' => 'wevote4.eu\'yu ziyaret ettiğinizde, mevcut ziyaretinizle ilgili verileri otomatik olarak toplayacağız ve saklayacağız. Bu bilgiler kişisel olarak tanımlanamaz. Toplayabileceğimiz bilgiler şunlardır: cihazınızdaki işletim sistemi, kullandığınız tarayıcı, wevote4.eu\'da ziyaret ettiğiniz sayfalar, ziyaretinizin kaynağı (örn. Google, Facebook), ziyaretinizin tarihi ve saati ve internete eriştiğiniz alan adıdır. Tüm bu bilgiler web sitemizdeki gezinme deneyimini daha da geliştirmek ve ziyaretçilerimizin tercihlerini anlamak için kullanılır. Açık izniniz olmadan bu web sitesi aracılığıyla herhangi bir kişisel bilgi toplamayacağız.',
    'subtitle_2' => 'Üçüncü taraf entegrasyonları',
    'line_2_1' => 'Commit Global, ziyaretçilerin genel deneyimlerini iyileştirmek için web sitemizde nasıl gezindiğini daha iyi anlamak için Google Analytics\'i kullanır. Google Analytics, ziyaretçileri hakkında tanımlanabilir herhangi bir bilgi toplamaz ve formlarımız aracılığıyla toplanan verileri Google Analytics tarafından sağlanan verilerle birlikte işlemeyiz.',
    'line_2_2' => 'Google Analytics, sizi benzersiz bir ziyaretçi olarak tanımlaması ve buna göre navigasyonunuz hakkında bilgi toplaması için tarayıcınıza bir çerez yerleştirir. Bu çerez, yalnızca kendi Google Analytics Kullanım Koşulları ve Google Gizlilik Politikası tarafından bu verileri paylaşması ve kullanması kısıtlanan Google tarafından kullanılır..',
    'subtitle_3' => 'Çerezler nedir',
    'line_3_1' => 'Çerez (“tarayıcı çerezi” veya “HTTP çerezi”), İnternet erişimi olan herhangi bir terminalde (bilgisayarlar, cep telefonları, tabletler vb.) depolanan ve bir sunucudan bir tarayıcıya (örn. Internet Explorer, Chrome) talep üzerine yüklenen küçük bir dosyadır. “Çerezler” herhangi bir yazılım programı, virüs veya casus yazılım içermez ve kullanıcının sabit diskindeki bilgilere erişemez. Bir çerez bir ad ve içerikten oluşur, varlığının süresi sınırlıdır ve bir kullanıcı o sunucuyla ilişkili web sitesine döndüğünde web sunucusu tarafından tekrar erişilebilir.',
    'line_3_2' => 'Çerezler, bilgileri küçük bir metin dosyasına kaydeder ve bir web sitesinin bir tarayıcıyı tanımasını sağlar. Web sunucusu, çerez süresi dolana veya silinene kadar tarayıcıyı tanıyacaktır. Çerez, gezinme deneyimini iyileştiren önemli bilgileri saklar (örn. bağışınız için seri numarası). Çerezler kişisel bilgi talep etmez veya internet kullanıcılarını kişisel olarak tanımlamaz.',
    'line_3_3' => '- Oturum çerezleri - kullanıcı o web sitesinden çıkana veya tarayıcı penceresini kapatana kadar saklandıkları tarayıcının geçmişinde geçici olarak saklanan çerezlerdir.
- Kalıcı Çerezler - Bunlar önceden belirlenmiş bir süre boyunca bir bilgisayarın sabit diskinde veya benzeri bir ekipmanda saklanır. Kalıcı çerezler, kullanıcının o sırada ziyaret ettiği web sitesinden farklı bir web sitesi tarafından yerleştirilen çerezleri içerir. Bu çerezler, kullanıcının ilgi alanlarını izlemek için anonim olarak kullanılabilen ve ilgi alanlarıyla daha alakalı reklamlar almalarını sağlayan “üçüncü taraf çerezleri” olarak adlandırılanları içerir.',
    'line_3_4' => 'Yalnızca tek bir oturum için kullanılan çerezler vardır - bunlar artık kullanıcı web sitesinden ayrıldıktan sonra saklanmaz. Kalıcı çerezler, kullanıcı o web sitesine her döndüğünde saklanır ve yeniden kullanılır, ancak kullanıcı tarafından herhangi bir zamanda silinebilir.',
    'subtitle_4' => 'Çerezlerin kullanımı nasıl engellenir/devre dışı bırakılır',
    'line_4_1' => 'Çerezler, sorunsuz ve verimli bir İnternet deneyimi için en önemli araçlardan biridir ve her kullanıcının ihtiyaçlarına göre uyarlanmış kullanıcı dostu tarama deneyimleri oluşturmaya yardımcı olur. Çerezleri kabul etmeyi reddetmek veya devre dışı bırakmak bazı web sitelerinin kullanımını imkansız hale getirebilir. Çerezleri kabul etmeyi reddetmek veya devre dışı bırakmak artık çevrimiçi reklam almayacağınız anlamına gelmez, yalnızca bu reklamların tarama davranışınızın belirlediği şekilde ilgi alanlarınızı veya tercihlerinizi artık dikkate almayacağı anlamına gelir.',
    'line_4_2' => 'Çerezleri kabul etmeyi reddetmek veya devre dışı bırakmak, bazı web sitelerinde gezinmeyi veya kullanılmasını zorlaştırabilir veya imkansız hale getirebilir. Çerezleri kabul etmeyi reddetmek, artık çevrimiçi reklam almayacağınız anlamına gelmez.',
    'line_4_3' => 'Tarayıcınızı çerezleri otomatik olarak reddedecek şekilde ayarlayabilir veya yalnızca çerezlerin etkinleştirildiği bazı web sitelerini seçebilirsiniz. Ancak, örneğin, bu web sitesinde çerezleri kapatırsanız, formu doldururken sonraki adımları takip edemezsiniz.',
    'line_4_4' => 'Modern tarayıcılar, çerez ayarlarını değiştirme olanağı sunar. Çerez ayarlarını genellikle tarayıcınızın “seçenekler” sekmesinde veya “tercihler” menüsünde bulabilirsiniz.',
    'line_4_5' => 'Çerezler ve bunların nasıl devre dışı bırakılacağı hakkında daha genel bilgi için www.aboutcookies.org adresini ziyaret edebilirsiniz.',
    'subtitle_5' => 'Veri paylaşımı',
    'line_5_1' => 'Yasaların gerektirdiği şekilde, bu web sitesi aracılığıyla toplanan kişisel bilgileri ifşa etmemizin istenebileceği durumlar olabilir. Mahkeme kararları gibi kanun uygulama gerekliliklerine ve yasal süreçlere uymak için talep edilirse veya bu sizi veya başkalarının haklarını, mülkiyetini veya genel güvenliğini koruyabilirse bilgilerinize erişebilir, saklayabilir ve ifşa edebiliriz.',
    'subtitle_6' => 'Güvenli ve sorumlu çerez tabanlı gezinme için öneriler',
    'line_6_1' => 'Çerezleri devre dışı bırakmak artık kullanıcıların Youtube, Gmail, Yahoo ve diğerleri gibi en önemli web sitelerinden bazılarına erişmesine izin vermeyecektir. Çerezleri saklarken güvenli bir şekilde gezinmenize yardımcı olabilecek bazı tavsiyeler şunlardır:',
    'line_6_2' => '- Rahat bir güvenlik seviyesi sağlamak için tarayıcı çerez ayarlarınızı özelleştirin. Çerezler sizin için bir sorun değilse ve bu cihazı kullanan tek kişi sizseniz, tarama geçmişinizi ve kişisel erişim verilerinizi saklamak için uzun çerez saklama aralıkları ayarlayabilirsiniz..
- Cihazı veya bilgisayarı paylaşıyorsanız, tarayıcıyı her kapatıldığında bireysel tarama verilerinizi silecek şekilde ayarlamak isteyebilirsiniz. Bu, oturumu kapatırken tüm tarama verilerinizi silerken paylaşılan bilgisayarınıza çerez yerleştiren web sitelerine erişmenin bir yoludur.
- Bir casus yazılım önleme uygulaması yükleyin ve güncel tutun. Birçok casus yazılım önleme uygulaması web sitesi saldırısı tespiti içerir. Bu uygulamalar, tarayıcının tarayıcının güvenlik açıklarından yararlanabilecek veya tehlikeli yazılımlar indirebilecek web sitelerine erişmesini engeller. Tarayıcınızın güncel olduğundan emin olun. Birçok çerez tabanlı saldırı, eski tarayıcı sürümlerinin zayıf noktalarından yararlanır.',
    'line_6_3' => 'Çerezler her yerdedir ve internetteki yerel veya uluslararası en büyük ve en iyi web sitelerinden bazılarına erişmek istiyorsanız kaçınılamaz. Çerezlerin çalışma şeklinin ve size sağladıkları faydaların net bir şekilde anlaşılması, her zaman güvenli ve tatmin edici bir tarama deneyimine sahip olmanız için gerekli güvenlik önlemlerini alabilir.',
    'subtitle_7' => 'Haklarınız',
    'line_7_1' => 'wevote4.eu web sitesinin bir kullanıcısı olarak aşağıdaki haklara sahipsiniz:',
    'line_7_2' => '- Kişisel verilerin Commit Global tarafından işlenmesine ilişkin bilgi edinme hakkı;
- Talep üzerine ve yılda bir talep için ücretsiz kişisel verilere erişim hakkı;
- Talep üzerine ve ücretsiz olarak kişisel verilerin müdahale, düzeltilmesi, silinmesi veya taşınabilirliği hakkı;
- Kişisel verilerinizin kullanımıyla ilgili veri gizliliği konularında herhangi bir yetkili makama başvurma hakkı
- İtiraz hakkı ve otomatik bireysel karar verme sürecinin yanı sıra işlemeyi kısıtlama hakkı.',
    'line_7_3' => 'Bu politika, bütünüyle, siz ve Commit Global arasında bu sitenin kullanımıyla ilgili olarak imzalanan bir anlaşmayı teşkil eder.',
    'line_7_4' => 'Commit Global, bu politikayı herhangi bir zamanda, bildirimde bulunmaksızın veya kullanıcıların önceden kabulü olmaksızın revize etme ve güncelleme hakkını saklı tutar. Bu sayfada yer alan bilgilerle ilgili herhangi bir sorunuz varsa, lütfen bize yazın ',
    'line_7_5' => 'wevotefor.eu Hüküm ve Koşullarının bu sürümü 23 Mayıs 2024 tarihinden itibaren geçerlidir. ',
];
