<?php
return [
    'title' => 'Politica de Confidențialitate',
    'intro_1' => 'Vă respectăm confidențialitatea și recunoaștem că trebuie să păstrăm și să folosim informațiile dvs. în mod responsabil.',
    'intro_2' => 'wevote4.eu este un site web creat de Commit Global („Commit Global”, „noi”, „nostru”) cu scopul de a informa publicul cu privire la alegerile europene.',
    'intro_3' => 'Această Politică de Confidențialitate descrie modul în care colectăm, folosim și protejăm informațiile dvs. personale pe acest site web. Prin trimiterea informațiilor dvs. personale pe acest site web, sunteți de acord cu termenii din această politică de confidențialitate. Dacă nu sunteți de acord cu acești termeni, vă rugăm să nu utilizați site-ul nostru web.',
    'subtitle_1' => 'Colectarea datelor',
    'line_1_1' => '- Colectăm informații de la dvs. dacă accesați acest site printr-un browser obișnuit.
- Acest site utilizează cookie-uri (ex: Google Analytics) pentru a măsura și optimiza experiența pentru toți utilizatorii.
- Commit Global nu va dezvălui sau vinde datele dvs. personale niciunei terțe părți, cu excepția situațiilor obligatorii din punct de vedere juridic descrise în această Politică de confidențialitate.
- Commit Global va lua toate măsurile rezonabile pentru a vă proteja informațiile personale, deoarece aceasta este o preocupare majoră pentru noi.',
    'line_1_2' => 'Când vizitați wevote4.eu, vom colecta și stoca automat date despre vizita dvs. curentă. Aceste informații nu sunt identificabile personal. Informațiile pe care le putem colecta sunt: sistemul de operare de pe dispozitivul dvs., browserul pe care îl utilizați, paginile din wevote4.eu pe care le-ați vizitat, sursa vizitei dvs. (ex: Google, Facebook), data și ora vizitei dvs. și domeniul din care accesați internetul. Toate aceste informații sunt utilizate pentru a îmbunătăți în continuare experiența de navigare pe site-ul nostru web și pentru a înțelege preferințele vizitatorilor noștri. Nu vom colecta informații personale prin intermediul acestui site fără consimțământul dvs. expres.',
    'subtitle_2' => 'Integrări terțe',
    'line_2_1' => 'Commit Global utilizează Google Analytics pentru a înțelege mai bine modul în care vizitatorii navighează pe site-ul nostru web pentru a-și îmbunătăți experiența generală. Google Analytics nu colectează informații identificabile despre vizitatorii săi și nu procesăm datele colectate prin formularele noastre împreună cu datele furnizate de Google Analytics.',
    'line_2_2' => 'Google Analytics va plasa un cookie în browserul dvs. pentru a vă identifica ca vizitator unic și pentru a colecta informații despre navigarea dvs. în consecință. Acest cookie este utilizat exclusiv de Google, care, la rândul său, este restricționat să partajeze și să utilizeze aceste date prin propriile Termeni de utilizare Google Analytics și Politica de confidențialitate Google.',
    'subtitle_3' => 'Ce sunt cookie-urile',
    'line_3_1' => 'Un Cookie („browser cookie” sau „cookie HTTP”) este un fișier mic, o succesiune de litere și numere, care este stocat pe orice terminal cu acces la Internet (computere, telefoane mobile, tablete etc.) și este instalat la cererea unui server către un browser (ex: Internet Explorer, Chrome). „Cookie-urile” nu conțin programe software, viruși sau spyware și nu pot accesa informațiile de pe hard disk-ul utilizatorului. Un cookie constă dintr-un nume și conținut, durata existenței sale este limitată și poate fi accesat din nou de către serverul web atunci când un utilizator revine pe site-ul asociat cu acel server.',
    'line_3_2' => 'Cookie-urile salvează informațiile într-un fișier text mic, permițând unui site web să recunoască un browser. Serverul web va recunoaște browserul până când cookie-ul expiră sau este șters. Cookie-ul stochează informații importante care îmbunătățesc experiența de navigare (de exemplu, un număr de serie pentru donația dvs.). Cookie-urile nu solicită informații personale și nici nu identifică personal utilizatorii de internet.',
    'line_3_3' => '- Cookie-uri de sesiune - sunt cookie-uri stocate temporar în istoricul browserului unde sunt stocate până când utilizatorul părăsește site-ul respectiv sau închide fereastra browserului.
- Cookie-uri persistente - Acestea sunt stocate, pentru o perioadă predeterminată de timp, pe un hard disk al computerului sau pe un echipament similar. Cookie-urile persistente le includ pe cele plasate de un site web diferit de cel pe care utilizatorul îl vizitează la momentul respectiv, așa-numitele „cookie-uri terțe” - care pot fi utilizate anonim pentru a urmări interesele unui utilizator - permițându-le să primească reclame mai relevante pentru interesele sale.',
    'line_3_4' => 'Există cookie-uri care sunt utilizate exclusiv pentru o singură sesiune - acestea nu mai sunt stocate după ce utilizatorul a părăsit site-ul web. Cookie-urile permanente sunt stocate și reutilizate de fiecare dată când utilizatorul revine pe site-ul respectiv, dar pot fi șterse în orice moment de către utilizator.',
    'subtitle_4' => 'Cum să blocați/renunțați la utilizarea cookie-urilor',
    'line_4_1' => 'Cookie-urile sunt unul dintre cele mai importante instrumente pentru o experiență de internet perfectă și eficientă, ajutând la generarea de experiențe de navigare prietenoase adaptate nevoilor fiecărui utilizator. Refuzul acceptării cookie-urilor sau dezactivarea acestora poate face unele site-uri imposibil de utilizat. Refuzul acceptării cookie-urilor sau dezactivarea acestora nu înseamnă că nu veți mai primi reclame online, ci doar că aceste anunțuri nu vor mai ține cont de interesele sau preferințele dvs., așa cum sunt determinate de comportamentul dvs. de navigare.',
    'line_4_2' => 'Refuzul acceptării cookie-urilor sau dezactivarea acestora poate face ca unele site-uri web să fie dificil sau imposibil de navigat sau utilizat. Refuzul de a accepta cookie-uri nu înseamnă, de asemenea, că nu veți mai primi reclame online.',
    'line_4_3' => 'Puteți configura browserul dvs. să respingă automat cookie-urile sau puteți selecta doar unele site-uri web în care cookie-urile sunt activate. Dar, de exemplu, dacă dezactivați cookie-urile pe acest site web, nu puteți urma următorii pași în completarea formularului.',
    'line_4_4' => 'Browserele moderne oferă posibilitatea de a modifica setările cookie-urilor. De obicei, puteți găsi setările cookie-urilor în fila „opțiuni” sau în meniul „preferințe” al browserului dvs.',
    'line_4_5' => 'Pentru mai multe informații generale despre cookie-uri și despre modul de dezactivare a acestora, puteți vizita www.aboutcookies.org.',
    'subtitle_5' => 'Partajarea datelor',
    'line_5_1' => 'Pot exista situații în care, conform legii, ni se poate solicita să dezvăluim informațiile personale colectate prin intermediul acestui site web. Putem accesa, păstra și dezvălui informațiile dvs. dacă vi se solicită pentru a respecta cerințele de aplicare a legii și procesele legale, cum ar fi hotărâri judecătorești sau dacă sunt citate, sau dacă acest lucru vă poate proteja drepturile, proprietatea sau siguranța generală a dvs. sau a altora.',
    'subtitle_6' => 'Sfaturi pentru o navigare sigură și responsabilă bazată pe cookie-uri',
    'line_6_1' => 'Dezactivarea cookie-urilor nu va mai permite accesul utilizatorilor la unele dintre cele mai importante site-uri web, cum ar fi Youtube, Gmail, Yahoo și altele. Iată câteva sfaturi care vă pot ajuta să navigați în siguranță în timp ce păstrați cookie-urile:',
    'line_6_2' => '- Personalizați setările cookie-urilor browserului pentru a permite un nivel de securitate confortabil. Dacă cookie-urile nu reprezintă o problemă pentru dvs. și sunteți singura persoană care utilizează acel dispozitiv, puteți seta intervale lungi de păstrare a cookie-urilor pentru a stoca istoricul de navigare și datele dvs. personale de acces.
- Dacă partajați dispozitivul sau computerul, este posibil să doriți să configurați browserul pentru a șterge datele dvs. individuale de navigare de fiecare dată când sunt închise. Aceasta este o modalitate de a accesa site-urile web care plasează cookie-uri pe computerul dvs. partajat, în timp ce ștergeți toate datele dvs. de navigare la închiderea sesiunii.
- instalați o aplicație anti-spyware și păstrați-o actualizată. Multe aplicații anti-spyware includ detectarea atacurilor pe site. Aceste aplicații împiedică browserul să acceseze site-uri web care ar putea exploata vulnerabilitățile browserului sau să descarce software periculos. Asigurați-vă că browserul dvs. este actualizat. Multe atacuri bazate pe cookie-uri exploatează punctele slabe ale versiunilor vechi ale browserului.',
    'line_6_3' => 'Cookie-urile sunt peste tot și nu pot fi evitate dacă doriți să accesați unele dintre cele mai mari și mai bune site-uri de pe internet, locale sau internaționale. Înțelegerea clară a modului în care funcționează cookie-urile și beneficiile pe care le aduc vă poate lua măsurile de securitate necesare, astfel încât să aveți întotdeauna o experiență de navigare sigură și satisfăcătoare.',
    'subtitle_7' => 'Drepturile tale',
    'line_7_1' => 'În calitate de utilizator al site-ului wevote4.eu aveți următoarele drepturi:',
    'line_7_2' => '- Dreptul la informare cu privire la prelucrarea datelor cu caracter personal de către Commit Global;
- Dreptul de acces la datele cu caracter personal, la cerere și gratuit pentru o singură solicitare pe an;
- Dreptul de intervenție, rectificare, ștergere sau portabilitate a datelor cu caracter personal, la cerere și gratuit;
- Dreptul de a vă adresa oricărei autorități competente cu privire la problemele de confidențialitate a datelor în legătură cu utilizarea datelor dvs. cu caracter personal
- Dreptul la opoziție și procesul automat de luare a deciziilor individuale, precum și dreptul de a restricționa prelucrarea.',
    'line_7_3' => 'Această politică constituie, în întregime, un acord încheiat între dvs. și Commit Global cu privire la utilizarea acestui site.',
    'line_7_4' => 'Commit Global își rezervă dreptul de a revizui și actualiza această politică în orice moment, fără notificare sau acceptare prealabilă a utilizatorilor. Dacă aveți întrebări cu privire la informațiile conținute în această pagină, vă rugăm să ne scrieți la ',
    'line_7_5' => 'Această versiune a termenilor și condițiilor wevotefor.eu intră în vigoare începând cu 23 mai 2024. ',
];
